### ISSUE TITLE
Increase withdraw intervals amount

### ISSUE THREAD

**Issue by Nemo1369** [GolosChain/golos#103]
Increase withdraw intervals amount assuming every interval is a week. The final intervals amount depends on the community decision.

Related to #62

**Comment by serejandmyself** [comment]
Change to 20 weeks

**Comment by Nemo1369** [comment]
Fixed with 500dc2d

**Comment by Nemo1369** [comment]
Closed by 9370158

**Comment by Nemo1369** [comment]
Closed by e034270
