### ISSUE TITLE
Расширить вывод метода get_vesting_delegations параметром payout_strategy

### ISSUE THREAD

**Issue by gropox** [GolosChain/golos#1041]
Начиная с ХФ19 можно задать процент отчисляемый за делегированную СГ с кураторских. Одновременно можно задать способ начисления процента. В СГ делегировавшему или добавлять к уже делегированной СГ. К сожалению не видно, как в текущий момент установлен способ начисления - payout_strategy отсутствует в выхлопе метода get_vesting_delegations.

Добавить payout_strategy к get_vesting_delegations

**Comment by gropox** [comment]
Также невозможно установить этот параметр. Видимо потому, что он в не зарефлекшен

FC_REFLECT((golos::protocol::delegate_vesting_shares_with_interest_operation), (delegator)(delegatee)(vesting_shares)(interest_rate)(extensions));

**Comment by maslenitsa93** [comment]
PR #1316
