### ISSUE TITLE
delegate_vesting_shares_with_interest_operation doesn't allow to change payout strategy

### ISSUE THREAD

**Issue by afalaleev** [GolosChain/golos#1045]
Payout strategy doesn't exist in FC_REFLECT:

https://github.com/GolosChain/golos/blob/a88d70ef377bf2c6d9b9ac34f535633dc86e8cd8/libraries/protocol/include/golos/protocol/steem_operations.hpp#L1436

**Comment by maslenitsa93** [comment]
PR #1316
