### ISSUE TITLE
Fix error messages in delete_comment_operation for worker proposals/tspecs

### ISSUE THREAD

**Issue by afalaleev** [GolosChain/golos#1047]
https://github.com/GolosChain/golos/blob/f0967df43f26df4fae9bbaa47ac5823758c0cb4f/libraries/chain/steem_evaluator.cpp#L465

https://github.com/GolosChain/golos/blob/f0967df43f26df4fae9bbaa47ac5823758c0cb4f/libraries/chain/steem_evaluator.cpp#L471

Proposal and Tspec are linked to `post`, not to `comment`.

**Comment by maslenitsa93** [comment]
But:
https://github.com/GolosChain/golos/blob/golos-v0.20.0/libraries/protocol/include/golos/protocol/exceptions.hpp#L224-L227
cannot_delete_comment_...
cannot_delete_comment_...
cannot_delete_comment_...
cannot_delete_comment_...

delete_**comment**_operation -> Cannot delete **comment**...

**Comment by afalaleev** [comment]
It is for common cases to show error about comment, because it will require to check a type of comment (post or comment).
But in case of worker proposal and tspec it is a error, because we know that proposal and tspec are attached to post.

**Comment by maslenitsa93** [comment]
PR #1054
