### ISSUE TITLE
worker_proposal_operation should validate type.

### ISSUE THREAD

**Issue by afalaleev** [GolosChain/golos#1051]
There are three types:

https://github.com/GolosChain/golos/blob/f0967df43f26df4fae9bbaa47ac5823758c0cb4f/libraries/protocol/include/golos/protocol/worker_proposal_operations.hpp#L10-L14

But only two of them are valid for an operation, and `type` should be validated:

https://github.com/GolosChain/golos/blob/f0967df43f26df4fae9bbaa47ac5823758c0cb4f/libraries/protocol/worker_proposal_operations.cpp#L7-L10

**Comment by maslenitsa93** [comment]
PR #1058
