### ISSUE TITLE
Add worker result WIP state

### ISSUE THREAD

**Issue by maslenitsa93** [GolosChain/golos#1175]
WIP state should be implemented via disapprove of result.

On disapprove of result, consumption should not refund. Techspec should not close. Result should not be deleted, because disapprover isn't author of it. But techspec state is changing `complete` -> `work`.

After it, techspec author can again call `worker_result_operation` (but only with same post because it has approves/disapproves), to change state `work` -> `complete` again.
Witnesses can again approve/disapprove result. But previous approves/disapproves are storing and counting. (Yes, if 1st witness will disapprove - result will be disapproved and author should be call `worker_result_operation` again.)

**Comment by afalaleev** [comment]
The workflow of the tspec became complex, because this issue is wrong.
Author of tspec can mark result of work as WIP, but this state should be informative for witnesses, not block, and witnesses can unfreeze funds by disapproving of work

**Comment by afalaleev** [comment]
Logic described in the issue is wrong.
