### ISSUE TITLE
Add unit tests on create worker techspec 

### ISSUE THREAD

**Issue by afalaleev** [GolosChain/golos#1180]
Covered cases:

- [x] Create worker tspec on not-exist post
- [ ] Create worker tspec on post with closed cashout window (post should be in cashout window, only in this case it has rshares)
- [x] Create worker tspec on comment
- [x] Create worker tspec on not-exist proposal
- [x] Create worker tspec on proposal with approved tspec
- [x] Create worker tspec on task/premade work

Add validating of fields in worker tspec object.

**Comment by maslenitsa93** [comment]
> Create worker tspec on post with closed cashout window (post should be in cashout window, only in this case it has rshares) 

Separated: https://github.com/GolosChain/golos/issues/1194
