### ISSUE TITLE
Add operation to disapprove work

### ISSUE THREAD

**Issue by maslenitsa93** [GolosChain/golos#1193]
This operation is for worker techspec in state `work`, or `complete`.
In state `work` it has no result yet, or has disapproved result (#1175).
In state `complete` it has result. Witnesses can disapprove this result. But more hard impact is to disapprove the work. It is useful, for instance, if techspec author instantly re-creates result after disapprove and witnesses can't catch moment of `work` state.

Work approves/disapproves are not removing when result (re-)created, or disapproved, etc. They are living due whole lifecycle of techspec.
If work is bad, different witnesses are disapproving it in different times, disapproves are accumulating, and final work disapprove occurs. 

On final work disapprove, consumption is refunding, and techspec is closing. Changing worker not available, because author of techspec should control worker and if work disapproved - it is his problem, too.

**Comment by afalaleev** [comment]
The issue is wrong, because it based on wrong issue #1175 .
Author of tspec shouldn't have abilities to block unfreezing of funds by witnesses.
