### ISSUE TITLE
Add unit tests on create duplicate of worker tspec

### ISSUE THREAD

**Issue by afalaleev** [GolosChain/golos#1207]
Covered cases:
- [x] Create worker tspec on post on which proposal already linked
- [x] Create worker tspec on post on which other worker tspec already linked
- [x] Create worker tspec on post on which worker result already linked

**Comment by maslenitsa93** [comment]
@afalaleev 

>  Create worker tspec on post on which other worker tspec already linked

It is modify of techspec.

> Create worker tspec on post on which proposal already linked
> Create worker tspec on post on which worker result already linked

It is not prohibited in our code. Prohibited only to create result on post with premade-result and vice-versa.
Also, in premade result worker result and worker techspec have same post.

**Comment by afalaleev** [comment]
Yep, you should add tests show its possible to create techspec on already linked posts.

**Comment by maslenitsa93** [comment]
@afalaleev "Create worker tspec on post on which other worker tspec already linked" is not possible because post is unique index inside same multi_index (techspec). It will work as modification of same techspec. Remove it from issue.
