### ISSUE TITLE
Merge logic of approving work with approving of techspec

### ISSUE THREAD

**Issue by maslenitsa93** [GolosChain/golos#1248]

**Comment by afalaleev** [comment]
Unusable case.

**Comment by maslenitsa93** [comment]
@afalaleev Why? It allows to stop work and unfreeze funds if techspec author willn't publish result by some cause.

**Comment by afalaleev** [comment]
It is not consistent. 
Witnesses:
1. approve freezing of funds
2. approve payments from freezed funds
3. unfreeze funds

If implement this issue, the witnesses can unfreeze tokens by two operations - approve_tspec and approve_result. It is strange...
See #1251
