### ISSUE TITLE
worker_proposal_evaluator allows change type of proposal with techspecs

### ISSUE THREAD

**Issue by boostmultifruit** [GolosChain/golos#1307]
Following check is added:
```
            GOLOS_CHECK_LOGIC(wpo->state == worker_proposal_state::created,
                logic_exception::cannot_edit_worker_proposal_with_techspecs,
                "Cannot edit worker proposal with techspecs");
```
Exception named "Cannot edit worker proposal with techspecs" but actually it disallows editing only with approved techspec.
1. Create premade proposal
2. Create premade techspec
3. Change it type
4. Create task techspec ??

**Comment by maslenitsa93** [comment]
PR #1310
