### ISSUE TITLE
Add operation to start transit to CyberWay

### ISSUE THREAD

**Issue by afalaleev** [GolosChain/golos#1348]
- Witnesses send transaction with transit_to_cyberway operation
- When 16 of top19 witnesses sign the operation the transit starts
- Node should wait until last sign fixed in LIB
- Each node which sign the transaction stops and generate genesis for CyberWay

**Comment by gropox** [comment]
А почему не просто остановить ноду с принятием 21-ого ХФ? Зачем отдельную операцию? А то получается переезд в два приема. Нужда в дополнительной операции мне не очевидна.
