### ISSUE TITLE
Extend JS operation serializer to support fixed_string<>

### ISSUE THREAD

**Issue by Nemo1369** [GolosChain/golos#156]
steemit_protocol_request_account_recovery = new Serializer( 
    "steemit_protocol_request_account_recovery"
    recovery_account: 14static_variantIJNS_12fixed_stringISt4pairImmEEEEEE
    account_to_recover: 14static_variantIJNS_12fixed_stringISt4pairImmEEEEEE
    new_owner_authority: steemit_protocol::authority
    extensions: set future_extensions
)

14static_variantIJNS_12fixed_stringISt4pairImmEEEEEE -> string

**Comment by AKorpusenko** [comment]
Yet another one js_name for fc::fixed_string<>. Please, check is that what's needed
