### ISSUE TITLE
Refactor plugin architecture to appbase

### ISSUE THREAD

**Issue by Nemo1369** [GolosChain/golos#159]
We want to refactor our plugins to use appbase and modularize our API stack. This will move us away from the single threaded limitations of FC cooperative multitasking. Using Boost threading and ASIO, we will be able to run each API request in a dedicated thread to parallelize API processing.

This is a huge problem currently as we are regularly requesting data that is not in cache. The single threaded nature of FC cooperative multitasking means that the entire process waits on a cache miss.

This refactor will also make the jsonrpc code separate from the websocket code, potentially allowing us to support different rpc and endpoint specs in the future without less effort.

**Comment by kotbegemot** [comment]
on depnds #172

**Comment by kotbegemot** [comment]
#195

**Comment by kotbegemot** [comment]
1. redesign rpc for secondary domestic use
2. implementation of the API for tolstoy
............
API:
- auth_util
- block_info
- raw_block
- languages
- market_history
- tags
