### ISSUE TITLE
Implement key-value storage plugin

### ISSUE THREAD

**Issue by Nemo1369** [GolosChain/golos#160]
Single-purposed plugin specially for CyberFund.

**Comment by litvintech** [comment]
#### We need to implement plugin which purpose to:
1. show the example how to extend core logic of golos using custom operations
2. implenent experemental features in case of cyber•Fund, there are:

#### case for cybernode and chain indexing (high priority)
1. data - system, block number, block hash, ipfs hash-link to raw block data, timestamp, account which wrote data, custom tag (ext), json_meta for optional metadata (ext)
2. logic - create, update, delete
3 api - get all stored information about system (in range too, pagination), get by block number, get by block hash, get by ipfs link, get all information by account, get by timestamp (with range too)
- so indexing by system, block number, block hash, ipfs hash, timestamp, account

#### case for cyberfund app: verification of address (medium priority)
1. data - system, address, tag, timestamp, account which wrote data, json_meta for optional metadata (ext)
2. logic - create, update, delete
3. api - get all addresses by system, get all addresses by tag, by timestamp (in range too), by account who verified, get by address
- so indexing by system, address, tag, timesamp, account which wrote the data

#### case for golos ssh system auth provider (low priority)
1. data - account (not account of golos, in general case), pubkey, tag, timestamp, account which wrote the data
2. logic - create, update, delete
3. api - get by account, by pubkey, by tag, by timestamp
- so indexing by system, address, tag, timestamp, account which wrote the data

#### case for golos dns system (low priority)
1. data - url (in golos domain name space, uniq), ip address, tag, timestamp, json_meta (ext), account which wrote data
2. logic - create, update, delete
3. api - get by url, ip address, tag
- so indexing by url, ip address, tag, timestamp, account which wrote the data
