### ISSUE TITLE
Disable custom_json_operation in core

### ISSUE THREAD

**Issue by litvintech** [GolosChain/golos#165]

**Comment by kotbegemot** [comment]
Please provide more information about the task.
From the title of the task is not understood smysal.

**Comment by gropox** [comment]
Why should custom_json be disabled? I am about to use it in production after next HF. Do you plan to introduce "key-value storage" used instead? If some scripts already using that feature (custom_json), it can not be disabled easily, because all data should be then migrated.

**Comment by gropox** [comment]
The second tought, custom_json allows to keep data overtime unchanged. I can for example store account's vesting shares growth overtime and create a graph based on that data. Key-Value storage sounds to be simple. Will be it possible to store several instances of same key, or use a composed key?

**Comment by Nemo1369** [comment]
Nope, we are not going to disable custom_json_operation. It is just a research issue for @litvintech.

**Comment by kotbegemot** [comment]
I do not see the problem.
