### ISSUE TITLE
fc/src/rpc/cli.cpp:117:1: warning: control may reach end of non-void function

### ISSUE THREAD

**Issue by Nemo1369** [GolosChain/golos#183]
```std::string cli::exec_command(const std::string &command)```

**Comment by AKorpusenko** [comment]
Fixed that. Made a commit to fc\183 (https://github.com/GolosChain/fc/commit/a3f8ff9ad76b5c8d631cb438ade95b9ef4abe96b).

**Comment by Nemo1369** [comment]
Fixed
