### ISSUE TITLE
cli_wallet: follow команда добавляет к following "@"

### ISSUE THREAD

**Issue by gropox** [GolosChain/golos#189]
![image](https://user-images.githubusercontent.com/26039472/30271806-f5a28f20-96f1-11e7-9155-0744e3307dc3.png)

![image](https://user-images.githubusercontent.com/26039472/30271730-a164ab28-96f1-11e7-8b11-fbd5bdeee363.png)

В результате follow_api не находит эту запись.

**Comment by Nemo1369** [comment]
Fixed with d1f5e0a
