### ISSUE TITLE
Smoothen reward distribution to O(nlog(n))

### ISSUE THREAD

**Issue by pavelit** [GolosChain/golos#193]

**Comment by Nemo1369** [comment]
@pavelit May become not required after #173 implementation.

**Comment by Nemo1369** [comment]
The whole discussion moved to #283

**Comment by AntonBliznets** [comment]
https://golos.io/ru--golos/@goloscore/novosti-golos-core-tekhnicheskoe-zadanie-na-modelirovanie-ekonomiki-golos
