### ISSUE TITLE
Fix the cli_wallet to work with the new api

### ISSUE THREAD

**Issue by kotbegemot** [GolosChain/golos#195]
Support json-rpc 2.0

**Comment by gropox** [comment]
Пожалуйста добавьте возможность в команде sell указать order_id. Без этого команда создает ордер с order_id = 0 и в итоге невозможно создать больше одного ордера через кошелек. 

`signed_transaction sell(string seller_account, string base, string quote, double rate, double amount, bool broadcast)`

`limit_order_create   {"owner":"investor-18","order_id":0,"amount_to_sell":"0.002 GBG","`

```
13 N5boost16exception_detail10clone_implINS0_19error_info_injectorISt11logic_errorEEEE: could not insert object, most likely a uniqueness constraint was violated
could not insert object, most likely a uniqueness constraint was violated: 
    {"op":{"owner":"investor-18","order_id":0,"amount_to_sel
```

**Comment by kotbegemot** [comment]
@gropox This requires a separate task.

**Comment by AKorpusenko** [comment]
@gropox the current issue is not specified for fixing such problem. Please create an issue in Goloschain/golos and we will research this question a bit later.

**Comment by AKorpusenko** [comment]
Now what about current issue. 
New code from ```steem/develop``` :
1. Patched  ```api_connection.hpp```
2. Added ```remote_node_api.hpp```
3. Added ```remote_node_api.cpp```

**Comment by AKorpusenko** [comment]
So, the main problem is to patch ```libraries/wallet```

**Comment by kotbegemot** [comment]
@Nemo1369 
not working market history api
not working subscribe mechanism

**Comment by kotbegemot** [comment]
dependence  #321
