### ISSUE TITLE
cli_wallet:  добавить возможность в команде sell указать order_id

### ISSUE THREAD

**Issue by gropox** [GolosChain/golos#198]
Пожалуйста добавьте возможность в команде sell указать order_id. Без этого команда создает ордер с order_id = 0 и в итоге невозможно создать больше одного ордера через кошелек. 

`signed_transaction sell(string seller_account, string base, string quote, double rate, double amount, bool broadcast)`

`limit_order_create   {"owner":"investor-18","order_id":0,"amount_to_sell":"0.002 GBG","`

```
13 N5boost16exception_detail10clone_implINS0_19error_info_injectorISt11logic_errorEEEE: could not insert object, most likely a uniqueness constraint was violated
could not insert object, most likely a uniqueness constraint was violated: 
    {"op":{"owner":"investor-18","order_id":0,"amount_to_sel
```

**Comment by Nemo1369** [comment]
Fixed with 5792cdc
