### ISSUE TITLE
Documentation mention unused env var USE_WAY_TOO_MUCH_RAM

### ISSUE THREAD

**Issue by bitfag** [GolosChain/golos#204]
USE_WAY_TOO_MUCH_RAM variable is not handled in the code. Peviously there was a check in 
contribution/golosd.sh

```
if [[ "$USE_WAY_TOO_MUCH_RAM" ]]; then
    STEEMD="/usr/local/golosd-full/bin/golosd"
fi
```
but it was removed in fc618c5701002e6c5c7e9987a83f5e282ef6d843

So, basically p2p/full node instructions in the README is outdated.

**Comment by Nemo1369** [comment]
@bitfag Fixed. We don't want to configure the daemon memory consumption with compile-time or argument list options right now - there is stuff to deal with about it. I mean, bugfixes about illiterate graphene memory leaks, replacing the terribly architected data management system. So I've just removed the unused env variable from readme.
