### ISSUE TITLE
Где запрограммирован процесс снятия голоса за Делегата спустя какое-то время

### ISSUE THREAD

**Issue by On1x** [GolosChain/golos#205]
Дублирую вопрос с Телеграм-чата:
> Посмотрел в коде, ничего про снятие голосов за witness через месяц или три не нашел. Может плохо смотрел
вопрос будет ли в ХФ сброс голосов за делегатов, если  - да, то где этот кусок кода

покажите файл (можно ссылкой на строчку в гитхабе) - где это происходит.

обсуждалось, что после того как кто-то сделает witness vote - через 3 месяца голос будет снят автоматически
отложенные операции уже есть (в recovery_account, например)

**Comment by serejandmyself** [comment]
As far as i understand its a f up by the dev team. This issue should be implemented as planned and should be watched for #111
