### ISSUE TITLE
PoW mining is broken

### ISSUE THREAD

**Issue by bitfag** [GolosChain/golos#211]
In the current version 0.16.4 pow mining is broken. It described in russian [here](https://golos.io/ru--golos/@primus/pow-maining-na-golose-umer-da-zdravstvuet-pow-maining-instrukciya-po-mainingu-dlya-tekh-kto-khochet-poprobovat-no-u-nego-ne) and in other articles.

To get pow mining working there is a patch available https://github.com/abitmore/steem/commit/73660037eb1965d4cd309959d4c654580805cda0

**Comment by Nemo1369** [comment]
@bitfag PoW mining is not broken. The link you've posted is just a bunch of shotcuts.

Moreover, you can find the shortcut built into a golos-v0.16.4 in here: https://github.com/GolosChain/golos/tree/150-mining-shortcut

Anyway, we are on our way to replace the useless equihash pow computations with something (I'ill announce it a little bit later) new.
