### ISSUE TITLE
Uniqueness of permlink

### ISSUE THREAD

**Issue by 21xhipster** [GolosChain/golos#213]
Do permalink should be unique or not? tx.id 10439552 & tx.id 10438316. Same author, same category, same permalink. If not, what is unique id of any post and comment?

**Comment by VIM-Arcange** [comment]
I do not find any post/comment having duplicate author/permlink
When multiple "comment" transactions have the same author/permlink, the first one is the original and subsequent are updates.

**Comment by Nemo1369** [comment]
@21xhipster According to https://github.com/GolosChain/golos/blob/177-asset-data-storage/libraries/chain/include/steemit/chain/comment_object.hpp#L275-L280 comment_objects have unique composite (author, permlink) key.
