### ISSUE TITLE
Witness price feed never expire

### ISSUE THREAD

**Issue by Gandalf-the-Grey** [GolosChain/golos#220]
During today's talks about expired (?) price feeds I realized that Golos might be prone to the same issue we had on Steem which caused that outdated feeds wasn't actually expired (https://github.com/steemit/steem/issues/822).

https://github.com/GolosChain/golos/blob/05e9d403b6155ec98991e871da4f701b449d2c59/libraries/chain/database.cpp#L2874-L2882

so as stated in the original issue:
>_"Once a witness published a price feed,_ **`wit.last_sbd_exchange_update < now + STEEMIT_MAX_FEED_AGE`** _will always be_ **`true`** _and_ **`!wit.sbd_exchange_rate.is_null()`** _will always be_ **`true`**_, thus the price feed will never expire."_

The fix should be as simple as replacing:
**`wit.last_sbd_exchange_update < now + STEEMIT_MAX_FEED_AGE && !wit.sbd_exchange_rate.is_null()`**
with
**`now < wit.last_sbd_exchange_update + STEEMIT_MAX_FEED_AGE && !wit.sbd_exchange_rate.is_null()`**
of course while keeping in mind the hardfork logic (i.e. if has_hardfork etc.)

**Comment by Nemo1369** [comment]
Fixed with 4cc67383c6db41fbc0fec220ed0514b6ae4925c5

**Comment by bitfag** [comment]
Please include this bugfix in upcoming 0.17 HF

**Comment by AKorpusenko** [comment]
Done in #553.
Closing this issue.
