### ISSUE TITLE
To make a tool to be able to view daily / weekly and montly transactions for any side user (not for internal use)

### ISSUE THREAD

**Issue by serejandmyself** [GolosChain/golos#226]

**Comment by Nemo1369** [comment]
@serejandmyself Sounds like a blockchain statistics plugin task

**Comment by serejandmyself** [comment]
Can you give me now a place where a side user can see this? It needs to be more simple. A good example is how we show our live supply to CMC

**Comment by serejandmyself** [comment]
done by muhazzz
