### ISSUE TITLE
Subscription error

### ISSUE THREAD

**Issue by wind33ru** [GolosChain/golos#233]
При попытке подписаться на пользователя на его странице возникает ошибка:
custom_json_operation<0, 17, 0>
![1](https://user-images.githubusercontent.com/33452416/32491956-9f6c8c96-c3c9-11e7-8768-94d40e420c90.png)

**Comment by wind33ru** [comment]
Так же некоторые моменты не локализованы, например:
1) При умышленном указании более 5 тегов - missing translation: ru.use_limited_amount_of_categories
2) Перейдя по ссылке из личной страницы, где можно посмотреть тех, на кого подписан, можно заметить нелокализованное "Followed".
![image](https://user-images.githubusercontent.com/33452416/32492288-ce7fdb40-c3ca-11e7-9480-0a85e120e7eb.png)

**Comment by b1acksun** [comment]
Ошибки локализации  - это клиент
Спасибо, исправим

**Comment by Nemo1369** [comment]
Same as #231

**Comment by wind33ru** [comment]
Я так понимаю, что слева на скриншоте - выбор локализации клиента. При переключении вообще ничего не происходит. Так же в настройках есть пункт смены языка - там меньше список, чем вышеописанный.
![image](https://user-images.githubusercontent.com/33452416/32492491-81a55952-c3cb-11e7-9d7a-c10416446235.png)

**Comment by wind33ru** [comment]
При создании актива не получается создать нецелое число "Сумма назначенных активов". То есть, число 12.444, к примеру, после точки нельзя ничего вписать. А если пользоваться запятой - 12,444, то цена обнуляется.
![image](https://user-images.githubusercontent.com/33452416/32492701-480b3382-c3cc-11e7-8e0e-8278a4f25426.png)

**Comment by wind33ru** [comment]
Кстати, то же самое "custom_json_operation<0, 17, 0>" вылезает при попытке блокировки пользователя.

**Comment by b1acksun** [comment]
fixed https://github.com/GolosChain/tolstoy/commit/5de7c6f03f7f6cf493c69ff47905f395c55fc2ba

**Comment by wind33ru** [comment]
@Nemo1369 Ребят, я немного прозевал момент, мой профиль на Голосе: @wind33
