### ISSUE TITLE
Не создается актив

### ISSUE THREAD

**Issue by wind33ru** [GolosChain/golos#235]
![image](https://user-images.githubusercontent.com/33452416/32493324-7362b13e-c3ce-11e7-8de2-72b079929ae3.png)
Не создается актив, пробовал с разными параметрами, в любых случаях указывается то, что необходима конкретная сумма - 1726272 golos.

**Comment by Nemo1369** [comment]
Not a bug, but a feature discussed in #108

**Comment by Tristamoff** [comment]
Увеличь число символов в имени актива до 8.

**Comment by b1acksun** [comment]
fixed https://github.com/GolosChain/tolstoy/commit/b11bf7dc518a4db8b78db9421ef810a688754e06
