### ISSUE TITLE
Rename on Russian and add the explanation about errors in transactions at domestic market

### ISSUE THREAD

**Issue by vista7** [GolosChain/golos#236]
Здравствуйте, дамы и господа разработчики! Предлагаю в тестовом новом хардфорке переименовать на русский язык (Голос - нацелен на русскоговорящих, ведь) уведомление об ошибках транзакций на внутреннем рынке. 
Сейчас эти уведомления об ошибках выглядят так: "**Transaction broadcast error**." Скриншот: 
![default](https://user-images.githubusercontent.com/33452731/32493744-aeb2e56a-c40a-11e7-8a98-96081ce1c548.png)

Это уведомление появляется когда не хватает средств в кошельке, допустим, или когда не правильно разместил заказ (ордер). 
Предлагаю перевести это уведомление на что-то вроде "**Ошибка при выполнении транзакции**". И было бы неплохо добавлять ещё короткое пояснение (тоже на русском) - почему операция транзакции сорвалась: недостаточно средств, к примеру,  и т.д. 

Думаю, это будет полезно всем Голосянам! А то, многие, наверное не понимают что такое Transaction broadcast error и при каких ситуациях оно появляется.

**Comment by Nemo1369** [comment]
Core issue #230 was connected to this. Fixed for now, closed.
