### ISSUE TITLE
Ошибка при торговле активами, отличными от GOLOS

### ISSUE THREAD

**Issue by Tristamoff** [GolosChain/golos#237]
Создал активы [AFDFDFDDSFSDF](https://testnet.golos.io/asset/AFDFDFDDSFSDF) и [QQQQQQQQ](https://testnet.golos.io/asset/QQQQQQQQ)
![](https://i.imgur.com/RsuiRHj.png)

Ордера на продажу создаются, а на покупку нет.
И в форме создания ордера на покупку(AFDFDFDDSFSDF) в "подсказке" всегда актив **GOLOS**(должен быть QQQQQQQQ)

**Comment by Nemo1369** [comment]
Known issue (#230).
