### ISSUE TITLE
Impossible to share (repost) post! Repost bug

### ISSUE THREAD

**Issue by vista7** [GolosChain/golos#238]
Заметил новую ошибку в тестовом хардфорке: невозможно поделиться постом (сделать репост). Вылазит ошибка **custom_json_operation<0, 17, 0>** . Эта ошибка проявляется как при попытке репоста из ленты постов (актуальное, новое и т.д.), так и при попытке репоста внутри самого поста. Скриншот: 
![default](https://user-images.githubusercontent.com/33452731/32494538-be8baa78-c40d-11e7-9627-e285121cb6ad.png)

**Comment by Nemo1369** [comment]
Same as #231

**Comment by vista7** [comment]
Nemo1369 , да, уведомление об ошибке вылазит похожее, но сам баг то другой)

**Comment by Nemo1369** [comment]
Duplicates #231

**Comment by vista7** [comment]
мой аккаунт на Голосе - @aleos
