### ISSUE TITLE
Ошибка при подписке

### ISSUE THREAD

**Issue by bezborodkin** [GolosChain/golos#240]
Не получается подписаться на пользователя. Выдаётся ошибка "custom_json_operation<0, 17, 0>"
Кнопка "подписаться" при этом меняется на "отписаться", но фактически подписки не происходит. 
Ошибка одинаково проявляется и при попытке подписки через профиль пользователя, и при попытке подписки через клик на ник. 
Скриншот прилагаю. 
Мой ник на Голосе - bezborodkin.
![2017-11-07_15-49-43](https://user-images.githubusercontent.com/33454584/32495111-4ca8c2de-c3d5-11e7-8940-ad2e2d15de9a.png)

**Comment by vista7** [comment]
Это уже было, issue такой есть, разрабы знают о проблеме. Можете удалить свой issue

**Comment by Nemo1369** [comment]
Duplicates #231
