### ISSUE TITLE
При создании актива с коротким Тикером нет уведомления о комиссии.

### ISSUE THREAD

**Issue by zhenek73** [GolosChain/golos#242]
При создании актива с коротким Тикером нет уведомления о комиссии.
Поэтому при попытке создать такой актив - получаем ошибку 
`ffffffffff's balance of 0 GOLOS is less than required 1726272 GOLOS`
Таким образом пользователь не понимает в чем проблема и почему актив не создается

**Comment by Nemo1369** [comment]
Looks like a tolstoy issue. @b1acksun could you please duplicate the issue in a https://github.com/GolosChain/tolstoy repository?

**Comment by b1acksun** [comment]
fixed https://github.com/GolosChain/tolstoy/commit/b11bf7dc518a4db8b78db9421ef810a688754e06
