### ISSUE TITLE
Increase the number of tags in the posts

### ISSUE THREAD

**Issue by vista7** [GolosChain/golos#243]
мой аккаунт на Голосе - @aleos
Дамы и господа разработчики, предлагаю в новом хардфорке (который мы сейчас тестируем) увеличить кол-во тегов в постах **хотя бы до 7-ми штук**. Можно и до 8-ми :) 
5 тегов - иногда бывает недостаточно, чтобы озвучить темы, которые заложены в посте. 

Скриношоты прикладывать не буду, и так всё понятно.

**Comment by Nemo1369** [comment]
Proposal is going to be implemented just after #122 implementation.

**Comment by vista7** [comment]
мой аккаунт на Голосе - @aleos

**Comment by afalaleev** [comment]
Closed by #752
