### ISSUE TITLE
Невозможно торговать пользовательскими активами

### ISSUE THREAD

**Issue by zhenek73** [GolosChain/golos#245]
При переходе на вкладку Активы и попытке Купить и продать пользовательские активы попадаем на страницу торговли ГБГ к Голос
![image](https://user-images.githubusercontent.com/6372495/32496661-707551b0-c3e3-11e7-812c-2fc3b61e6d6d.png)
![image](https://user-images.githubusercontent.com/6372495/32496671-7cefbb2e-c3e3-11e7-97b1-8b6b10d76fcb.png)

**Comment by Nemo1369** [comment]
Seems like a tolstoy issue. @b1acksun?

**Comment by b1acksun** [comment]
I have created an [issue](https://github.com/GolosChain/tolstoy/issues/514) with all of this issues

**Comment by zhenek73** [comment]
@Nemo1369 мой аккаунт на @zhenek

**Comment by afalaleev** [comment]
Closed as issue for tolstoy.
