### ISSUE TITLE
не регистрируется тестовый аккаунт

### ISSUE THREAD

**Issue by borisss111** [GolosChain/golos#246]
При попытке создать нового пользователя, с любым набором символов в качестве ника выдает ключ для регистрации, под ником пишет некий cost  в GOLOS, цифры разные каждый раз, и ничего больше не происходит , все галки проставил. Два скрина. Пробовал несколько раз, картина повторяется, пробовал на ios 11 в Chrome, на ноуте с Windows 10 в chrome/
![img_1177](https://user-images.githubusercontent.com/33465720/32515224-8f92307c-c410-11e7-82e2-d2d189ca49f9.jpg)
![testnet](https://user-images.githubusercontent.com/33465720/32515256-a76deeac-c410-11e7-9263-2531cbc0c6ea.png)

**Comment by b1acksun** [comment]
Данная ситуация возникает из-за комиссии за регистрацию имени, в последующих версиях эта комиссия будет убрана

**Comment by borisss111** [comment]
Спасибо. Мне уже подсказали на Голос, что нужно сделать более длинный ник.
Увеличил количество символов и все получилось.

8 нояб. 2017 г. 12:14 пользователь "Igor Tkachenko" <
notifications@github.com> написал:
