### ISSUE TITLE
Постоянно выкидывает из акаунта

### ISSUE THREAD

**Issue by polyideic** [GolosChain/golos#247]
ник - @polyideic
Делаю репост, коммент или ап - постоянно выкидывает из моего аккаунта (а теперь заработало!)
+ не отображаются посты в ленте
+ в настройках публичного профиля нет возможности нажать кнопку Обновить - заработало!
+ не могу проверить Промо - нет золотых на счету
+ пропала кнопка Ответить на пост
![image](https://user-images.githubusercontent.com/8217102/32535527-6ced3084-c46b-11e7-923c-4d3caf6465c1.png)
могу отвечать только в своем посте
попробовал продвинуть свой пост. сняло 1 золотой, но в промо ничего не отобразилось ((( не работает пока...

**Comment by Nemo1369** [comment]
Not a chain issue, but an issue connected to test network daemon relaunch.
