### ISSUE TITLE
сразу открывается редактирование поста 

### ISSUE THREAD

**Issue by mazurolga** [GolosChain/golos#248]
ник @mazurolga

тестирую на testnet.golos.io
когда открываешь свой пост, то почему-то сразу включается редактирование поста, а не просто его отображение 
<img width="1440" alt="2017-11-08 12 08 00" src="https://user-images.githubusercontent.com/33477455/32535976-0f071fda-c47e-11e7-9d48-666d3cbefb51.png">
<img width="1440" alt="2017-11-08 12 08 07" src="https://user-images.githubusercontent.com/33477455/32535978-13efb0c0-c47e-11e7-8eef-83259e6260e3.png">

**Comment by b1acksun** [comment]
can't reproduce issue
