### ISSUE TITLE
Couldn`t parse int64_t

### ISSUE THREAD

**Issue by allfory0u** [GolosChain/golos#254]
Мой ник на Голосе - **allforyou**
Голос показывает эту ошибку при попытке обновления актива с подстановкой в **сумму назначенных активов** огромного числа. На фронтенде нет ограничений по вводу в это поле, поэтому можно ввести число любой длины. <hr>
![screenshot_6](https://user-images.githubusercontent.com/17462020/32570054-a6d96ed8-c4cb-11e7-9a74-107f65bdc2ea.jpg)<hr>
А при попытке сохранить это выбивает ошибку:
![screenshot_7](https://user-images.githubusercontent.com/17462020/32570085-bcfc7570-c4cb-11e7-8c53-5f7af20b0976.jpg)<hr>
![default](https://user-images.githubusercontent.com/17462020/32570126-da7a8682-c4cb-11e7-98f7-106ca783de6f.gif)
<hr>
Похожее происходит и при создание актива, только ошибка другая:

![screenshot_4](https://user-images.githubusercontent.com/17462020/32570268-58737b70-c4cc-11e7-9f41-21b6fb38e27a.jpg)<hr>
![screenshot_5](https://user-images.githubusercontent.com/17462020/32570281-632e9cca-c4cc-11e7-966f-0152fab3d9bf.jpg)<hr>
![default](https://user-images.githubusercontent.com/17462020/32570305-6f201504-c4cc-11e7-8992-5e72dc4c7a50.gif)

**Comment by allfroyou** [comment]
Мой ник на Голосе - **allforyou**

**Comment by allfroyou** [comment]
Мой ник на Голосе - **allforyou**

**Comment by b1acksun** [comment]
fix in https://github.com/GolosChain/tolstoy/commit/9c3bf3891828d41af48314d8aa7f72963ba2fe03
