### ISSUE TITLE
ХФ 0.2 При попытке создать пост происходит автоматический выход из аккаунта

### ISSUE THREAD

**Issue by professor-fortran** [GolosChain/golos#261]
Блог на ГОЛОС-е: https://golos.blog/@prof.fortran

Если войти в аккаунт
![0](https://user-images.githubusercontent.com/32443152/32655470-ac1bd0d0-c61e-11e7-92ab-c14fb18fbc3d.png)
не поставив галочку "Оставить меня залогиненным"
![1](https://user-images.githubusercontent.com/32443152/32655503-d1822e8c-c61e-11e7-87e9-4ed55b8a6591.png)
и после этого попытаться создать пост
![2](https://user-images.githubusercontent.com/32443152/32655521-f33dc16c-c61e-11e7-875d-a9c984469e64.png)
то после ввода тегов и нажатия кнопки "Обновить пост"
![3](https://user-images.githubusercontent.com/32443152/32655531-fef4bc86-c61e-11e7-9fef-7f13fad305f2.png)
меня выкидывает из аккаунта
![4](https://user-images.githubusercontent.com/32443152/32655573-2c019e7e-c61f-11e7-91f9-6d4ad68e51b1.png)
Видимо, умерла сессия, что явно не должно происходить таким образом, т.к. иначе работать с ГОЛОС становится невозможно.

Если после этого снова зайти в свой аккаунт (в Блог)
![5](https://user-images.githubusercontent.com/32443152/32655625-6f9b8762-c61f-11e7-95e8-c67222044b70.png)
то можно видеть, что никакой пост не был создан
![6](https://user-images.githubusercontent.com/32443152/32655645-881e4ee6-c61f-11e7-92d5-b6f35759cf60.png)

**Comment by Nemo1369** [comment]
@professor-fortran Thank you for the suggestion, but not really a chain issue. The trouble described was connected to some test network infrastructure issues. Fixed for now.
