### ISSUE TITLE
ХФ 0.2 Невозможно создать пост

### ISSUE THREAD

**Issue by professor-fortran** [GolosChain/golos#262]
Если войти в аккаунт и поставить при входе галочку "Оставить меня залогиненным", то при попытке создать новый пост любым из способов на картинке ниже

![0](https://user-images.githubusercontent.com/32443152/32656823-70a864ae-c624-11e7-9cf9-6e2f062bca30.png)

после нажатия кнопки "Обновить пост"

![1](https://user-images.githubusercontent.com/32443152/32656861-8fa2906e-c624-11e7-9784-82720378da0c.png)

не происходит переброса на вкладку "Новое", как это обычно бывает

![2](https://user-images.githubusercontent.com/32443152/32656902-b913bd10-c624-11e7-82b6-97688c531ab3.png)

а в моем блоге поста не появляется

![3](https://user-images.githubusercontent.com/32443152/32656933-d30d93a8-c624-11e7-94a7-003065637d07.png)

**Comment by vista7** [comment]
Про это уже давно знают и работают. Можете закрыть свой issue, он является повтором.

**Comment by professor-fortran** [comment]
Дайте ссылку, я что-то не нашел

**Comment by NickShtefan** [comment]
Работа по данному вопросу ведется в рамках [этого issue](https://github.com/GolosChain/tolstoy/issues/453)
