### ISSUE TITLE
ХФ 0.2 Исчезновение поста из списка новых через 1 час

### ISSUE THREAD

**Issue by professor-fortran** [GolosChain/golos#265]
Через 1 час после публикации пост исчезает из списка новых. 
Вот пост через 59 минут после публикации
![0](https://user-images.githubusercontent.com/32443152/32678039-d2a93168-c671-11e7-8d58-e1aa44391d81.png)
Через минуту пост пропадает
![1](https://user-images.githubusercontent.com/32443152/32678057-e0628c50-c671-11e7-9b9c-992734b7a0a7.png)
С одной стороны, это логично, т.к. он уже не новый, но, с другой стороны, получается, что пост пропадает вообще. Его больше нет ни в одном списке: ни  в новых, ни в актуальных. Короче говоря, его нет нигде. Вот это не очень правильно. По идее, в списке "Новое" должны быть вообще все посты, отсортированные по дате и времени, которые должны подгружаться по мере скроллинга вниз

**Comment by Nemo1369** [comment]
@professor-fortran This is just a test network restrictions. Not an issue.
