### ISSUE TITLE
Возможно опечатка "...10 basic_exception: tion\nitr != _by_name.end()..." > лишнее tion\n

### ISSUE THREAD

**Issue by KorzunAV** [GolosChain/golos#267]
json-rpc:
{"method":"get_schema","params":[],"jsonrpc":"2.0","id":1}
ответ хф 17:
{"id":1,"error":{"code":1,"message":"10 basic_exception: tion\nitr != _by_name.end(): no method with name 'get_schema'\n   .....
неожиданный кусок текста в ответе "tion\n"
ответ хф 16  :
{"id":1,"error":{"code":1,"message":"10 assert_exception: Assert Exception\nitr != _by_name.end(): no method with name 'get_schema'\n ...

ps. попутно замечание - хотелось бы получать ответы об ошибках с уникальным кодом (нужно для локализации текста ошибок). Сейчас приходится привязываться к полю message и парсить его. Как результат при изменении текстовок.. например "10 assert_exception" > "10 basic_exception" клиентский код может полететь к чертям...  как альтернатива > отдельный файл список ошибок, что бы можно было все текстовки получить в одном месте, а не выскребать по коду.

**Comment by Nemo1369** [comment]
@KorzunAV Known minor issue with static exceptions message definition with boost::mpl::string. Still important though. Thanks a lot.

Talking about exception messages standardisation, it is a known community wish and has a separate issue #218. Coming in version 0.17.1.

**Comment by afalaleev** [comment]
Closed by #741
