### ISSUE TITLE
PoW mining is not enabled in v0.17.0RC5 code 

### ISSUE THREAD

**Issue by primusd** [GolosChain/golos#270]
I've added Pull request #269 to enable PoW mining again into v17 RC5 code.

**Comment by Nemo1369** [comment]
@primusd I would really appreciate if you would stop calling this an "Enablement". It is just a set of dirty-hacky shortcuts to perform PoW computations faster. As far as my experiments show, the trouble with mining is not about shortcuts availability. If these hacks were a trouble, I would have applied them back in July (https://github.com/GolosChain/golos/tree/150-mining-shortcut). Can you confirm these hacks help?

**Comment by Nemo1369** [comment]
Closed according to #269 merge.
