### ISSUE TITLE
Totally remove key changing code

### ISSUE THREAD

**Issue by bitfag** [GolosChain/golos#274]
Changing keys for any account via hardfork mechanism should not be used ever. We need to get rid of the key changing code involving in processing `compromised_accounts`

libraries/chain/database.cpp:
```cpp
                   for (const std::string &acc : hardfork16::get_compromised_accounts()) {
                        const account_object *account = find_account(acc);
                        if (account == nullptr) {
                            continue;
                        }

                        update_owner_authority(*account, authority(1, public_key_type(
                                "GLS8hLtc7rC59Ed7uNVVTXtF578pJKQwMfdTvuzYLwUi8GkNTh5F6"), 1));

                        modify(get<account_authority_object, by_account>(account->name),
                               [&](account_authority_object &auth) {
                                   auth.active = authority(1, public_key_type(
                                           "GLS8hLtc7rC59Ed7uNVVTXtF578pJKQwMfdTvuzYLwUi8GkNTh5F6"), 1);
                                   auth.posting = authority(1, public_key_type(
                                           "GLS8hLtc7rC59Ed7uNVVTXtF578pJKQwMfdTvuzYLwUi8GkNTh5F6"), 1);
                               });
```

**Comment by tomarcafe** [comment]
Как возвращать деньги инвестору, потерявшему ключи? Предположим он может доказать, что он это он?

**Comment by On1x** [comment]
Nobody can't change keys in blockchain with any reason. It's about blockchain mechanism.

**Comment by tomarcafe** [comment]
let the flame begin!

**Comment by On1x** [comment]
@tomarcafe Это его проблемы. Он знал, на что идет. Потерял ключи = потерял деньги. Иначе к блокчейну никакого доверия.

**Comment by tomarcafe** [comment]
мне кажется, надо нафиг отменять эту дурню с комментированием на английском.

как пишет в чате vvk - лучше бы подтянуть описания комитов

**Comment by tomarcafe** [comment]
@On1x и тут я так пониманию команда голоса попадает в нехорошую западню - плохо продаётся серьезным инвесторам такая инвестиция.

**Comment by Chiliec** [comment]
Ага, а следующем ХФ ещё кому-нибудь сменят? 😃

**Comment by tomarcafe** [comment]
@Chiliec прецеденты, к сожалению, были.

**Comment by Nemo1369** [comment]
@bitfag Changing the lost keys set of LiveJournal pre-claimed accounts was a consensus stuff. Do you really think we need to remove this?

**Comment by VIM-Arcange** [comment]
@Nemo1369 A consensus? Which were the parties of this consensus?

**Comment by Nemo1369** [comment]
@VIM-Arcange It was announced even for 16-th version. And 16-th version worked fine with it. Two additional accounts were removed, now it is just a LiveJournal users list.

**Comment by Chiliec** [comment]
Why this code generally exists? It's a blockchain or what? If you lost your keys — it's your fault, create another account or goodbye. Nobody tries to embed such bookmarks in the hardfork code of Bitcoin, what's wrong with Golos blockchain?

**Comment by bitfag** [comment]
Such a code creates a "bed smell" and bad reputation and should be removed and forgotten as a bad dream.

**Comment by VIM-Arcange** [comment]
@Nemo1369 You are not replying to the question "Which were the parties of this consensus?"

**Comment by Nemo1369** [comment]
@VIM-Arcange @bitfag @Chiliec @On1x Account public keys reset removed.

**Comment by VIM-Arcange** [comment]
@Nemo1369 Thank you for the feedback

**Comment by bitfag** [comment]
Why HF-16 related code was not removed?
 Is it intended to be a historical reminder?
 https://github.com/GolosChain/golos/blob/master/libraries/chain/database.cpp#L4641

**Comment by Nemo1369** [comment]
@bitfag It is not going to be removed because of backward compatibility requirements.

**Comment by bitfag** [comment]
Backward compatibility with what? Please describe in more detail.

As I understand, replaying blockchain with removed HF-16 related key-changing code will result in reverting "compromised accounts" keys back to the previous versions. And problem may arise whether keys was manually changed again via the built-in mechanism after HF-change. Thus, node may reject these key-changing transactions as invalid, so it may result in chain split. Am I correct?
