### ISSUE TITLE
Seems like parent asset restriction logic doesn't work

### ISSUE THREAD

**Issue by AlexShkor** [GolosChain/golos#275]
Here I've found that in the check " the only owner of parent asset can create nested assets" seems to be a mistake. We should query an asset by prefix, not by we are querying by new symbol name, which for sure doesn't exist (checked above).

https://github.com/GolosChain/golos/blob/b0a2fda1a9a2a983ac7a981beb43f0821eaea56d/libraries/chain/evaluators/asset_evaluator.cpp#L38-L40

**Comment by Nemo1369** [comment]
Fixed in golos-v0.17.0
