### ISSUE TITLE
Transfer for empty user going to miners account

### ISSUE THREAD

**Issue by On1x** [GolosChain/golos#282]
If anyone using golos-js for transfer tokens to empty account they going to 0 id miners account.

@on1x on golos ;)

**Comment by On1x** [comment]
Seems that there is no any checks for empty login in blockchain and it's going to 0 id account.

**Comment by Nemo1369** [comment]
@On1x Not really an absence of empty logins check. Implemented in here: https://github.com/GolosChain/golos/blob/master/libraries/protocol/operations/transfer_operations.cpp#L23-L24

@b1acksun Looks like a golos-js issue.

**Comment by On1x** [comment]
Почему тикет закрыт? Проблема не решена.

**Comment by Nemo1369** [comment]
@On1x It is a https://github.com/GolosChain/golos-js issue. Could you please reopen the ticket in there?

@b1acksun Could you please reproduce the issue?
