### ISSUE TITLE
Fix golos description

### ISSUE THREAD

**Issue by tomarcafe** [GolosChain/golos#286]
here - https://github.com/GolosChain/golos#introducing-golos-beta

or explain what happens

is not PoW chain, is DPoS chain.

**Comment by tomarcafe** [comment]
@Nemo1369  any comment bout using PoW here? or your trolling is silent?

**Comment by Nemo1369** [comment]
@tomarcafe Not really an issue, but would be great to get it fixed. So it is fixed for a master branch.
