### ISSUE TITLE
Implement repost removal

### ISSUE THREAD

**Issue by litrbooh** [GolosChain/golos#294]
Невозможность удалить репост несет две проблемы:
1) Если автор полностью изменил пост, например, слово "ЙУХ" написал в заголовке, ты не можешь это уже удалить из своего блога.
2) Если случайно репостнул не то, или не из того аккаунта, то удалить невозможно.

**Comment by asuleymanov** [comment]
ДА думаю стоит внести изменения по данному вопросу. Очень часто бывает вариант с изменением поста и соответственно изменение мнения репостера (тот кто сделал репост) к нему.

**Comment by t3ran13** [comment]
+1
вот сегодня репостнул котика. а потом в комментах глянул что он мошенник.
НУЖНО! очень!

**Comment by Nemo1369** [comment]
Seems like a follow_plugin enhancement. May be implemented in a softfork.

**Comment by vista7** [comment]
@t3ran13 котик оказался мошенником или автор?)

**Comment by vista7** [comment]
Ну вообще идея хорошая, я об этом тоже думал уже не один раз. Но как сделать возможность удалять репост, если он записывается в блокчейн? Это возможно?

**Comment by Nemo1369** [comment]
@vista7 Of course we are talking about the removal from the current database state, not from the chain, just like comment removal. It is possible.

**Comment by litrbooh** [comment]
@afalaleev 
возьмете в 19тый?

**Comment by afalaleev** [comment]
Можем предложить включить в 19-ый. Включать или не включать решает сообщество.

**Comment by litrbooh** [comment]
@afalaleev , так и нужно сделать

**Comment by afalaleev** [comment]
Closed by #751
