### ISSUE TITLE
Дополнительные бенефициары по выплатам за посты и комменты

### ISSUE THREAD

**Issue by 21xhipster** [GolosChain/golos#30]

**Comment by serejandmyself** [comment]
@21xhipster Нужна конкретика. Если речь о мотивации на уровне выплат, то тогда это в баунти, если надо придумать мотивацию на уровне БЧ, скажем % или решение о котором говорил Дэн, думаю стоит уточнить в коментах

**Comment by 21xhipster** [comment]
[Вот](https://github.com/steemit/steem/issues/773) конкретика. Планируем 17 хардфорк

**Comment by serejandmyself** [comment]
С тех пор уже понятно стало

**Comment by serejandmyself** [comment]
Имплементировано в 17 ХФ
