### ISSUE TITLE
Убрать функционал смены темы в настройках

### ISSUE THREAD

**Issue by zhenek73** [GolosChain/golos#301]
Функционал смены темы работает, но он настолько не красив и выгшлядит таким костылем, что портит впечатление о площадке. Посмотрите как выглядит например сайт, с включенной красной темой

![image](https://user-images.githubusercontent.com/6372495/33234263-3305d1ca-d23d-11e7-817d-0489241bbd95.png)

При этом я вижу по коллегам блоггерам начинающим, что некоторые играют с этой настройкой и оставляют себе одну из тем, в итоге видят этот очень не красивый вид.

Также хотел бы обратить внимание на кнопку Приглашения
![image](https://user-images.githubusercontent.com/6372495/33234281-775033ca-d23d-11e7-94a2-375827d254ab.png)

Она также не работает, поэтому не нужна - очень сильно сбивает с толку новичков. Я неделю искал, кто мне объяснит почему она не работает и пришел тогда к выводу что это глюк, сайт же просто альфаверсия - тоже сильно портит впечатление.

**Comment by Nemo1369** [comment]
Looks like a tolstoy issue. @b1acksun @pavelit

**Comment by Nemo1369** [comment]
@b1acksun It is a frontend issue.
