### ISSUE TITLE
Глюк при снятии голоса за делегата.

### ISSUE THREAD

**Issue by zhenek73** [GolosChain/golos#302]
На тестнете проверить этого не могу, пока там нет делегатов. Но на текущей версии Голоса заметил такой глюк: при снятии голоса с делегата, копка так и остается подсвеченной, буд-то я голос не снял. 

В консоле в этом случае вот такая ошибка наблюдается
![image](https://user-images.githubusercontent.com/6372495/33234340-a7ed2172-d23e-11e7-82fc-87f4c8cd9b79.png)

Скорее всего ошибка перекочевала и на новую версию сайта

**Comment by Nemo1369** [comment]
@b1acksun It is a frontend issue.
