### ISSUE TITLE
При создании актива нет ограничение на ввод суммы назначенных активов

### ISSUE THREAD

**Issue by zhenek73** [GolosChain/golos#303]
При создании актива нет ограничение на ввод суммы назначенных активов. Хотя например в поле Максимальное колличество такое ограничение стоит и ошибка выдается сразу.

![image](https://user-images.githubusercontent.com/6372495/33234364-2e57fb1a-d23f-11e7-899a-c559b8d4f53f.png)

**Comment by zhenek73** [comment]
https://github.com/GolosChain/golos/issues/254 
The same issue is already exist

**Comment by b1acksun** [comment]
fix in https://github.com/GolosChain/tolstoy/commit/9c3bf3891828d41af48314d8aa7f72963ba2fe03
