### ISSUE TITLE
Необходимо предупреждение о том, что пользователь пытается покинуть страницу

### ISSUE THREAD

**Issue by zhenek73** [GolosChain/golos#304]
При создании пользовательского Ассета довольно трудно и долго приходится заполнять и продумывать все поля. При этом стоит случайно нажать на любую из кнопок - как мы сразу покидаем страницу, и вернуться уже нельзя - данные не сохраняются.

Здесь очень не хватает стандартного предупреждения "Вы собираетесь покинуть страницу, все не сохраненные данные будут потеряны. Продолжить?" 

Уже несколько раз приходилось переделывать из-за этого.

**Comment by Nemo1369** [comment]
Looks like a @b1acksun issue

**Comment by Nemo1369** [comment]
@b1acksun It is a frontend issue.
