### ISSUE TITLE
Баг при редактирование прав пользовательского ассета

### ISSUE THREAD

**Issue by zhenek73** [GolosChain/golos#305]
При редактировании пользовательского ассета  мы видим предупреждение "ПРЕДУПРЕЖДЕНИЕ: Права доступа могут быть только отключены, однажды отключив, Вы не сможете их реактивировать!"

Но, отменив все права и сохранив ассет, я легко смог добавить права снова и сохранить изменения.

![image](https://user-images.githubusercontent.com/6372495/33234998-6c5f200a-d249-11e7-8089-e35bffbecd38.png)

Заодно заметил и еще один глюк: при выставлении максимальной комиссии рынка есть возможность задать отризательное значение 
![image](https://user-images.githubusercontent.com/6372495/33235030-d3e56bf8-d249-11e7-9c2b-c8528043463e.png)

Сохранить такие изменения нельзя - вылетает ошибка, но в интерфейсе меняется. Не критично.

**Comment by Nemo1369** [comment]
Seems like a duplicate of #234

**Comment by Nemo1369** [comment]
Seems like a frontend issue, @b1acksun. I'm closing this according to #234 duplicate available.
