### ISSUE TITLE
После закрытия окна выплат, пропадает стрелочка и возможность посмотреть информацию о выплате

### ISSUE THREAD

**Issue by zhenek73** [GolosChain/golos#310]
![image](https://user-images.githubusercontent.com/6372495/33245979-b2d6a050-d328-11e7-84ea-89a45ef99277.png)

Вот пост который я написал вчера и сегодня. У свежего поста стрелочка, и нажав на нее я вижу информацию по окну выплат и количеству. А у нижнего поста такой стрелочки нет и я не могу узнать, сколько было получено за него гбг. Возможно это за счет того, что там ноль конечно.

**Comment by Nemo1369** [comment]
@b1acksun That is the frontend issue.
