### ISSUE TITLE
Информация об ошибке появляется на другом слое страницы и ее не видно

### ISSUE THREAD

**Issue by zhenek73** [GolosChain/golos#311]
Когда я открываю пост и пишу более одного коммента в 20 секунд, то информация об ошибке, которое обычно выезжает слева, находится на слое под тенью, в результате чего становится не читаемая
![image](https://user-images.githubusercontent.com/6372495/33246035-61ce8bf4-d329-11e7-9495-e4e89a8f22e4.png)

В этом месте дублируется, но например здесь 
![image](https://user-images.githubusercontent.com/6372495/33246053-b22da292-d329-11e7-90ed-00e707973552.png) 
при попытке удалить комментарий с ответом, уже не читаемая ошибка и без дубликата.

Также возможно имеет смысл убирать кнопку Удалить у комментария, на который появился ответ, впрочем достаточно и ошибки.

**Comment by Nemo1369** [comment]
@b1acksun That is the frontend issue.

**Comment by Bacher** [comment]
Issue уже не актуально, сейчас ошибки выглядят вот так:

![screen shot 2018-06-21 at 12 45 20](https://user-images.githubusercontent.com/2598671/41711552-053d788a-7551-11e8-8e3e-3cd82f7c5acf.png)
