### ISSUE TITLE
Отсутствует информация об ошибке при не правильной загрузке изображения

### ISSUE THREAD

**Issue by zhenek73** [GolosChain/golos#312]
При попытке загрузить большое изображение в комментарий или в сам пост, изображение не загружается, хотя проценты идут. В итоге пользователь не получает ошибку и не знает в чем дело, либо размер слишком большой, либо формат. 

Необходимо добавить сообщение вроде: "изображение не загружено. максимальный размер 1200 на 980 точек" Либо "максимальный размер 300кб". Иначе не понятно. Это очень мешает новичкам создавать посты с фотографиями.

**Comment by VIM-Arcange** [comment]
@zhenek73 Эти проблемы связаны с веб-интерфейсом

Пожалуйста, используйте следующий репозиторий: https://github.com/GolosChain/tolstoy

**Comment by zhenek73** [comment]
Ой. Сейчас я уже не могу перенести в репозиторий веб-клиента?

**Comment by b1acksun** [comment]
Я перенесу

**Comment by zhenek73** [comment]
Спасибо, буду внимательнее.
