### ISSUE TITLE
HF0.2 Market API, Wrong prices

### ISSUE THREAD

**Issue by gropox** [GolosChain/golos#315]
On testnet, stand 02.12.2017 00:34 GMT

1. I created a new asset FCKFCKFCK without fraction part and issued 40 tokens of that asset.
2. Went to the market GOLOS-FCKFCKFCK
3. Created order for selling 1 FCKFCKFCK for 3 GOLOS

Result: GUI shows selling price 0.003000, amount to sell UIA: **1000.000**, rest amount 39 FCKFCKFCK

![image](https://user-images.githubusercontent.com/26039472/33509365-31b5c514-d701-11e7-98e8-faaba2c92530.png)

Same shows cli_wallet

![image](https://user-images.githubusercontent.com/26039472/33509374-4a588b24-d701-11e7-9a45-6d23d3834e82.png)

And market API

![image](https://user-images.githubusercontent.com/26039472/33509527-c3e3f5ae-d702-11e7-9e4c-7f57eb0f7f7d.png)

**Comment by Nemo1369** [comment]
@gropox Some fixes introduced in 1b1ad10315.

**Comment by Nemo1369** [comment]
Fixed with 1b1ad10315
