### ISSUE TITLE
Let user adjust curators reward percent

### ISSUE THREAD

**Issue by bitfag** [GolosChain/golos#324]
As we see, upvote selling, kickback programs like upvote50-50 and upvote100 and boosters clearly shows us we need to let users define curators reward %.

So I propose to implement possibility to set custom curation reward percent to avoid relying on 3rd-party scripts and services.

Probably should go into next protocol upgrade.

**Comment by vista7** [comment]
@bitfag мысль интересная, но может вы для начала сами попробуете отказаться от этого безумия в виде бустеров? upit-бустер - это же ваш проект? Бустеры уничтожают экономику Голоса: новички и средний класс стали ещё более нищими (выплаты упали в два раза у всех), а бустероманы и продавцы лайков - жиреют день ото дня. Очень показательноя социальное расслоение.

А вообще, лучше установить кураторство по умолчанию на уровне 65/35 или 63/37, это может по крайней мере значительно повлиять на отказ от откатных схем типа 50/50. 
Давать пользователю самостоятельно устанавливать процент вознаграждения - считаю не правильным, это не решит проблемы откатов.

**Comment by Nemo1369** [comment]
@bitfag @vista7 Was planned even in April to be implemented as a part of #120

**Comment by bitfag** [comment]
Another interesting idea: curation % may depend on total payout. Bigger payout -> bigger curation percent.
https://golos.io/ru--razvitieproekta/@yurgent71/ideya-plavayushchie-kuratorskie-na-golose

**Comment by litrbooh** [comment]
А я читаю, что куратор должен выбирать процент кураторских в отведенных делегатами пределах.

**Comment by bitfag** [comment]
@litrbooh мне уже тоже этот вариант больше нравится. Это логично - кто владеет стэйком, тот и решает, какой % дать.

**Comment by bitfag** [comment]
Можно сделать как в VIZ - делегаты устанавливают минимальный и максимальный кураторский процент, который может выставить автор.

**Comment by afalaleev** [comment]
@bitfag спасибо!

Самый простой вариант, который мы можем включить в этот ХФ 
- Выставление минимального и максимального процента кураторских выплат делегатами.
- Выбор процента кураторских выплат автором. Предположим, что автор будет стимулировать голосовать кураторов за его пост через увеличенный процент кураторских выплат.

Есть другие варианты выбора кураторских - но мы не успеем сделать их в этом ХФ:
- Выбор % куратором, и результирующий процент - средневзвешенная величина.
- Добавить кривую для процента кураторских, с зависимостью от rshares поста.
- И т.д.

**Comment by maslenitsa93** [comment]
- [ ] Add properties for min and max curation rewards percent to `chain_properties`. (Including **API**: `chain_api_properties` and cli_wallet)
- [ ] To calculate median, use algorithm... TODO
- [ ] Add curation percent field  as an **extension** to `comment_options_operation`
- [ ] Add curation percent field to `comment_object` (including **API**: `comment_api_object`)
- [ ] Add HF
- [ ] Use comment's curation percent field in database.cpp (in comment cashout helper), instead of value from `get_curation_rewards_percent()` (if HF applied)
- [ ] Also in `discussion_helper`
- [ ] Fix unit-tests
- [ ] Write unit-tests

**Comment by bitfag** [comment]
Есть такая проблема что кураторское распределение сильно неравномерное, см #677. Плавающий кураторский процент при текущей модели распределения кураторских будет давать интересные эффекты.

**Comment by afalaleev** [comment]
На линейную, чтобы эффектов не было?

**Comment by bitfag** [comment]
@afalaleev с линейной эффектов не будет, но проблема в том что сейчас нет полной концепции как система должна работать в целом, крутятся разные параметры, при этом по сути отсутствуют обоснования вида "Мы хотим получить то-то и то-то, для этого мы меняем X, Y, Z", по идее это требует обсуждения.

* С не-линейной кураторской кривой есть стимул голосовать рано, соревнуясь за кураторские. Но если кит не играет, ему проще так же продавать апы как сейчас.
* С линейной кривой момент голосования становится не важен
* sqrt-кривая - некий промежуточный вариант, где награда размазывается более равномерно, в то же время первым голосующим достаётся всё равно несколько больше

**Comment by afalaleev** [comment]
@bitfag текущая кривая - она заточивалась под однодневное окно выплат и под другую схему курирования, в которой кит награждал тех, кто нашел хороший пост. сейчас в курирование мало кто играет. 

если ситуация не поменяется, то кураторскую поменять нужно, а на какую - я согласен, нужно обсуждать с сообществом. 
правда по-моему, проголосуют за линейную. 

при голосовании за фичи ХФ-19 на кураторскую кривую внимание не обратили.

в любом случае, в случае принятия ХФ-19 обстановка на платформе поменяется из за изменения поведения штрафного окна, а нам по любому доставлять следующий ХФ в ближайшее время, так как воркеров к текущему ХФ мы доставить не успели.
