### ISSUE TITLE
HF0.2 fraction part of numbers still wrong interpreted!

### ISSUE THREAD

**Issue by gropox** [GolosChain/golos#328]
1. created asset with 3 fraction numbers

![image](https://user-images.githubusercontent.com/26039472/33913619-d733b888-df9a-11e7-8e5b-0943fb515ae6.png)

2. if the token issued with wrong number of zeros after dot, wrong amount calculated by cli wallet

Before
![image](https://user-images.githubusercontent.com/26039472/33913823-b8a7ddd0-df9b-11e7-89da-d2d150236199.png)

Issue asset executed with 10.00000 GBG
![image](https://user-images.githubusercontent.com/26039472/33913872-e6329c68-df9b-11e7-82a8-33889ff9db70.png)

But in operation are 1000.000 GBT written

Another example with GOLOS
![image](https://user-images.githubusercontent.com/26039472/33913956-2cb52340-df9c-11e7-92d4-9de86406e3d4.png)

The operation was accepted!
![image](https://user-images.githubusercontent.com/26039472/33913975-418e4602-df9c-11e7-9b29-7ef127212b94.png)

![image](https://user-images.githubusercontent.com/26039472/33914010-6490c51c-df9c-11e7-9568-fbd6855dca5c.png)

**Comment by Nemo1369** [comment]
@gropox Fixed with 3ac8fb7. Would really appreciate additional testing.
