### ISSUE TITLE
Can't reserve asset

### ISSUE THREAD

**Issue by b1acksun** [GolosChain/golos#330]
Trying to reserve asset with precision = 4

`"asset_reserve",{"payer":"b1acksun","amount_to_reserve":"100.0000 QWERTYUI","extensions":[]}]`

throws an exception:

`10 basic_exception: tion
delta.decimals == precision: 
    {}
    th_a  account_object.cpp:23 adjust_balance`

**Comment by romanlanskoj** [comment]
the same 
o.asset_to_issue.get_decimals() == a.precision:

**Comment by Nemo1369** [comment]
@romanlanskoj Thanks for the issue suggestion. A known one, fixing now.

**Comment by Nemo1369** [comment]
Fixed with 6c004991f5
