### ISSUE TITLE
Reduce the number of posts a day to three

### ISSUE THREAD

**Issue by vista7** [GolosChain/golos#332]
Здравствуйте, дамы и господа разработчики и остальные участники Гитхаба Голос. 
Знаю, что в новом хардфорке было увеличено кол-во постов в день с 4 до 8-ми, считаю это поспешным и не очень правильным решением в сложившейся на Голосе экономической ситуации. 
Некоторые пользователи сейчас сильно злоупотребляют бустерами, постя по 3-4 бесполезных поста в день, с целью накатить на пост бустер и заработать на этом побольше. Из-за этого всего идёт довольно ощутимый перекос пула наград. 
Если максимальное кол-во постов увеличится до 8-ми в день, то это лишь усугубит ситуацию... Думаю, не нужно объяснять почему. Те, кто сейчас злоупотребляют бустерами, начнут ещё больше ими злоупотреблять (постя уже не по 3-4 поста в сутки, а по 7-8), перекос пула станет ещё ощутимей для всех. 

Предлагаю снизить максимальное кол-во постов **до 3-х в сутки**! Возможно, нужно будет и прописать в коде такую фишку, чтобы 4-й пост нельзя было написать вообще, стояла какая-нибудь заглушка на это дело.
Серьёзно. Никому не нужны 8 постов в день! Уверен, что практически никто не будет писать столько постов в день, лишь некоторые пользователи будут злоупотреблять этой возможностью ради бустеров.
Да, есть такие аккаунты типа "Голос Медиа" и rblogger, которые постят по 3-4 поста в сутки с подборками некоторых постов и новостей мира. Думаю, им хватит и 3 поста в сутки, чтобы уложить в них свои подборки и основные новости. Остальным простым пользователям - 8 постов в сутки не нужны.

Тема довольно серьёзная, прошу отнестись к ней с вниманием. Если не в этом ХФ снизить кол-во постов, так в следующем софт-форке точно нужно этим заняться.

**Comment by Nemo1369** [comment]
@vista7 These changes are going to become a part of #120. It means, these business-logic stuff is going to be a commitee-configurable.

**Comment by afalaleev** [comment]
Not popular issue.
