### ISSUE TITLE
некорректно работает метод получения постов через тег (get_discussions_by_trending)

### ISSUE THREAD

**Issue by epexa** [GolosChain/golos#335]
в тестнете создал пост с тегом ico, если [перейти в блог](https://testnet.golos.io/@epexa) (получение постов по автору), то он есть.
однако если вызвать через API метод  для получения постов по тегу, например через golos.js: ``golos.api.getDiscussionsByTrending({tag: ['ico'], limit: 10}, console.log);``
то возвращает какой-то не правильный (если параметр tag) или пустой (если параметр select_tags) результат...
![image](https://user-images.githubusercontent.com/2198826/34048911-809e04fa-e1c6-11e7-96d4-cdb37e27cc81.png)

**если использовать параметр select_tags, то всё равно не находит посты!**
![image](https://user-images.githubusercontent.com/2198826/34049406-589e971a-e1c8-11e7-847f-000078ccb709.png)
**кстати если посмотреть тут https://testnet.golos.io/trending/ico , то тоже самое...**

мой ник на голосе - [epexa](http://golos.io/@epexa)

**Comment by afalaleev** [comment]
Fixed in #509
