### ISSUE TITLE
Решить проблему с монополизацией майнинга

### ISSUE THREAD

**Issue by gamerate** [GolosChain/golos#34]
В данный момент и в Голос и в steem 99%+ блоков в майнинге добывает 1 или 2 человека (gtx-1080-sc-ххх и penguin-хх) которые либо используют некоторый пока не известный баг либо используют недоступный другим людям код для GPU майнера.
Хотя на безопасность системы в целом это влияет не очень существенно (20 других блоков  создают делегаты), но за счет этого мы теряем вовлечение майнеров в систему - без использования этих багов или кода для GPU майнить не имеет какого либо смысла - 1 блок в неделю на самом мощном сервер это видимо сейчас предел. Кроме этого это создает прецедент несправедливости, когда награду за майнинг получают не вполне честным путем.
Как именно можно решить эту проблему не вполне очевидно но думать над её решением мне кажется стоит.

**Comment by 0n0t0le** [comment]
Решить можно лишь сборкой и публикацией своего GPU майнера...

**Comment by ValeryLitvin** [comment]
Состояние ситуации:
1. эксплуатация бага
2. приватный gpu-майнер
@penguin сделал пулл-реквест, который закрывает первый пункт
[когда все треды используют один и тот же nonce]
https://github.com/GolosChain/golos/pull/37

Предлагаю протестировать и по результатам выплатить баунти @penguin

**Comment by gamerate** [comment]
Если я правильно понял описание бага, он просто ухудшает майнинг на машинах с более чем 1 ядром, но не объясняет монополизации очереди, если эффективность майнеров понижена в 2-8 раз они все равно бы смогли иногда создавать блоки.
GPU майнер может быть легендой - gtx-1080-sc aka supercomputing в прошлый раз монополизировал майнинг с помощью бага (когда перешли на pow2) вероятно и в этот раз он тоже использует баг - причем возможно не тот который нашел @penguin.

**Comment by serejandmyself** [comment]
@21xhipster @ValeryLitvin будет ли проблема актуальна для 0.16 ?

**Comment by gamerate** [comment]
В данный момент на стиме проблемы с монополией нет, но насколько я понимаю, дело просто в том, что пока никто не написал GPU майнер (или наоборот написал и всем дал - но последнего я не слышал, хотя внимательно не разбирался).

**Comment by serejandmyself** [comment]
В стиме проблема исчезла после ХФ16

**Comment by 21xhipster** [comment]
Майнинга не будет
