### ISSUE TITLE
Why is some data not being written to all nodes?

### ISSUE THREAD

**Issue by vikxx** [GolosChain/golos#342]
@gropox pointed out an interesting case:

```
author = "tapeur";
permlink = "zaglavnyi-post-proekta-tapeur-informaciya-grafiki-plyushki-post-otkrytie";
```

On my four full nodes plus goldvoice and @primusd node - `active_votes` for post above is empty.
On ws.golos.io node, is ok,  `active_votes`  has data.

How can this be? Problem of seeds? Or what?

**Comment by gropox** [comment]
The querstion is about get_content method. Seems that newly synced nodes return correct content with filles "active_votes" attribute. Some early synced nodes return emtpy "active_votes" array.

**Comment by VIM-Arcange** [comment]
My full node got this post and the related votes

**Comment by afalaleev** [comment]
It depends on `clear-votes` flag.
