### ISSUE TITLE
account_statistics plugin

### ISSUE THREAD

**Issue by kotbegemot** [GolosChain/golos#353]
Add account_statistics plugin and refactor it to support the appbase and new json_rpc.

**Comment by AKorpusenko** [comment]
This is a copy of #345

**Comment by AKorpusenko** [comment]
Made a mistake. Sorry

**Comment by AKorpusenko** [comment]
There is no need to backport this plugin from 17.1, because it doesn't make sense to implement an empty plugin...
Closing the issue
