### ISSUE TITLE
метод get_ticker возвращает название переменных стима

### ISSUE THREAD

**Issue by epexa** [GolosChain/golos#369]
![bug](https://user-images.githubusercontent.com/2198826/35320298-5736f8f4-00f4-11e8-8a61-a759780e9c00.jpg)
_результат:_
```js
highest_bid: "1.35494596841230242"
latest: "1.38888888888888906"
lowest_ask: "1.35999418604651168"
percent_change: "0.80645161290323919"
sbd_volume: "1898.029 GBG"
steem_volume: "1404.829 GOLOS"
```
переменые **sbd_volume** и **steem_volume** нужно переименовать в **gbg_volume** и **golos_volume** соответственно.

https://github.com/GolosChain/golos/blob/65ca130c70882f3d92e01344cb1116b84ddf0273/libraries/plugins/market_history/include/steemit/market_history/market_history_api.hpp#L30

**Comment by gropox** [comment]
Надо учесть, что если начать переименовывать переменные, то придется так же адаптировать сторонние приложения и есть сомнения, что люди охотно будут этим заниматься. 

golosd
golos.steemstats.com
golosdb.com
mssql база данных
ноды bittrex, rudex и другие шлюзы

и менее крупные проекты.

**Comment by epexa** [comment]
@gropox как вариант сделать с совместимостью, добавить корректные названия переменных и оставить старые, до какой-нибудь версии (пока все не переделают).

**Comment by VIM-Arcange** [comment]
> оставить старые, до какой-нибудь версии (пока все не переделают).

If you go this way, then things will never change ;)
Either change then names or not.
