### ISSUE TITLE
The cli_wallet does not correctly create transaction.

### ISSUE THREAD

**Issue by kotbegemot** [GolosChain/golos#395]
**Steps to reproduce**
![screenshot-2018-02-02-01-26-05](https://user-images.githubusercontent.com/958279/35777993-9d59db6c-09c8-11e8-9feb-6d162ca63f26.png)

**Actual results**
![screenshot-2018-02-02-00-57-21](https://user-images.githubusercontent.com/958279/35777992-95156322-09c8-11e8-9458-577888f6e3ad.png)

**Expected result**
cli_wallet returns success on create an account.

**Comment by zxcat** [comment]
JSON-RPC `network_broadcast_api` `broadcast_transaction` fails the same way

**Comment by afalaleev** [comment]
@zxcat Yes, you are right the problem is in compatibility with old protocol. Tomorrow, we will create an issue with returning of old protocol for network_broadcast_api.

**Comment by zxcat** [comment]
yeah, I've already discovered it, here is my hotfix #399

**Comment by zxcat** [comment]
Note: #399 fixes only `broadcast_transaction` (checked via websockets). But `cli_wallet` use `broadcast_transaction_synchronous`, which still don't work. There is something else broken in addition to input parameters, so transaction expires and `golosd` crashes.

**Comment by zxcat** [comment]
works for me now for *good* transactions. still crashes if transaction can't be run (e.g. trying to transfer more funds than have)

**Comment by afalaleev** [comment]
@zxcat can you show an example of transaction which crashes?

**Comment by afalaleev** [comment]
@zxcat can you confirm that you are see the same as described in #402.

**Comment by zxcat** [comment]
`cli_wallet` looks ok now, but `golosd` either crashes or spams with exception loop and crashes then.
Steps to reproduce:
1. I run testnet, *cyberfounder* user have no GBG.
2. Run `cli_wallet -C "unlock 123 && transfer cyberfounder \"null\" \"0.123 GBG\" \"{}\" true"`
Result:
![mutex-fail](https://user-images.githubusercontent.com/550974/35978031-ad1c4974-0cf5-11e8-9305-deaea80b9bec.png)

```
560008ms th_a       network_broadcast_api.cpp:162 on_applied_block     ] 13 N5boost16exception_detail10clone_implINS0_19error_info_injectorINS_10lock_errorEEEEE: boost: mutex lock failed in pthread_mutex_lock: Invalid argument
rethrow boost: mutex lock failed in pthread_mutex_lock: Invalid argument:
    {"what":"boost: mutex lock failed in pthread_mutex_lock: Invalid argument"}
    th_a  network_broadcast_api.cpp:162 on_applied_block
1560008ms th_a       database.cpp:1012             notify_applied_block ] Caught exception in plugin: 13 N5boost16exception_detail10clone_implINS0_19error_info_injectorINS_10lock_errorEEEEE: boost: mutex lock failed in pthread_mutex_lock: Invalid argument
rethrow boost: mutex lock failed in pthread_mutex_lock: Invalid argument:
    {"what":"boost: mutex lock failed in pthread_mutex_lock: Invalid argument"}
    th_a  network_broadcast_api.cpp:162 on_applied_block
```

You can see transactions send by running that command, then some blocks produced, then assertion fail in a promise.

Sometimes it crashes instantly, sometimes starts to spam that error message each block.

3. If it's not crashed yet, executing valid transaction will kill `golosd`:
`[1]    44278 segmentation fault  ../programs/golosd/golosd -d testnet165`

**Comment by afalaleev** [comment]
@zxcat Thank you 👍In your case golosd crashes in the same place as in case from #402

**Comment by zxcat** [comment]
@afalaleev, yeah, looks the same
