### ISSUE TITLE
[0.16.5] Default logging configuration is broken

### ISSUE THREAD

**Issue by bitfag** [GolosChain/golos#416]
While starting the daemon with default config, I'm getting an error:
```
testnet_1  | 464073ms th_a       main.cpp:131                  main                 ] Error parsing logging config
```

To reproduce, just build a testnet `docker build -f ./share/golosd/docker/Dockerfile-debug -t golos-0.16.5-testnet:latest .` and start it.

**Comment by kotbegemot** [comment]
The boost init parser  does not fully support the init rfc .
He corrected to look at the https://github.com/GolosChain/golos/pull/423 .

**Comment by bitfag** [comment]
Confirmed.
