### ISSUE TITLE
Proposal for API update

### ISSUE THREAD

**Issue by NickShtefan** [GolosChain/golos#440]
We need API update for private messaging implementation. 
Right now API request  can return 500 and more results, this leads to the complexity of lengthy responses to requests, and extremely inconvenient processing of incoming data. 
Is it possible to implement "paging" of API calls on blockchain side? 

Something similar to LIMIT in *sql databases? 
`SELECT * FROM table LIMIT 0,10`

**Comment by kotbegemot** [comment]
The api json-rpc  should be changed to the object design
```js
{
"limit":1,
"offset":1
}
```

**Comment by NickShtefan** [comment]
I think we need to refactor current json-rpc calls. The best way is using JSON-RPC 2.0 Specification.
You can find examples here http://www.jsonrpc.org/specification
