### ISSUE TITLE
API fixes for filters needed

### ISSUE THREAD

**Issue by NickShtefan** [GolosChain/golos#442]
There is a problem with filters on current API 
There are two parameters for `get_disscussions_by_*` methods
- select_tags
- filter_tags

If the first one does somehow work, then the second one does not work at all. 

There is a similar problem in other APIs, for example, the 
`get_account_history` method. It is not possible to specify a filter to get only transactions history.
`get_active_votes` method does not have a parameter with which you can specify the date for which you want to display the upvotes.

Methods `get_discussions_by_trending`, `get_discussions_by_created`, `get_discussions_by_active` and similar return a field with a full list of active_votes, which in turn can contain more than 1000 entries.
To display feeds in the client, this complete list is not needed, but only the number of upvotes for each post is needed.
The full list of the same pulls a half-megabyte (!!!) of useless data

**Comment by afalaleev** [comment]
Closed by #742
