### ISSUE TITLE
Ошибка сборки

### ISSUE THREAD

**Issue by dacom-dark-sun** [GolosChain/golos#45]
При сборке по скрипту из википедии, появляется ошибка:
                    ^
[ 65%] Building CXX object libraries/net/CMakeFiles/graphene_net.dir/peer_connection.cpp.o
[ 65%] Building CXX object libraries/net/CMakeFiles/graphene_net.dir/message_oriented_connection.cpp.o
virtual memory exhausted: Cannot allocate memory
libraries/chain/CMakeFiles/steemit_chain.dir/build.make:62: recipe for target 'libraries/chain/CMakeFiles/steemit_chain.dir/database.cpp.o' failed
make[2]: *** [libraries/chain/CMakeFiles/steemit_chain.dir/database.cpp.o] Error 1
CMakeFiles/Makefile2:1026: recipe for target 'libraries/chain/CMakeFiles/steemit_chain.dir/all' failed
make[1]: *** [libraries/chain/CMakeFiles/steemit_chain.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 65%] Linking CXX static library libgraphene_net.a
[ 65%] Built target graphene_net
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
cp: cannot stat 'programs/golosd/golosd': No such file or directory
cp: cannot stat 'programs/cli_wallet/cli_wallet': No such file or directory
mapalanet@instance-1:~$

**Comment by ValeryLitvin** [comment]
@mapalanet Какие характеристики твоей машины?

**Comment by mapalanet** [comment]
Облако гугл, 8гб оперативы + Ubuntu 16.04. 
Три недели назад собиралось нормально, в моих действиях по сборке тогда и сейчас отличий нет.

**Comment by AlekseiSmirnov** [comment]
вылазила эта же ошибка если на той же машине была запущена другая нода (даже под другим пользователем)

**Comment by dacom-dark-sun** [comment]
Да, это как всегда у меня проблема была) Вопрос закрыт)

**Comment by dacom-dark-sun** [comment]
UPD: Проблема решается добавлением оперативной памяти

**Comment by ruslansalikhov** [comment]
Или уменьшением количества потоков сборки. Потому около 3х гб на поток (если грубо говорить).
