### ISSUE TITLE
0.17.0 - get_block from database_api method doesn't return transactions any more? 

### ISSUE THREAD

**Issue by vikxx** [GolosChain/golos#468]
config.ini:
`plugin = social_network database_api network_broadcast_api`

`get_block 625` - method doesn't return transactions any more
`get_ops_in_block 625 false` - **resolve** (My fault, coz dpnds `account_history` plugin)

![get_ops_in_block](https://user-images.githubusercontent.com/26347159/37564325-5f6e34c8-2ac6-11e8-97f9-2df06f1ac326.PNG)
[screen.png](https://user-images.githubusercontent.com/26347159/37564325-5f6e34c8-2ac6-11e8-97f9-2df06f1ac326.PNG)

**Comment by gropox** [comment]
get_ops_in_block не работает если account_history не активирован

**Comment by vikxx** [comment]
> get_ops_in_block не работает если account_history не активирован

Да, этот момент я помню с 16.X
Сейчас идет синхронизация как раз с account_history и 625 блок уже есть в индексе, однако не работает. 
Подожду полной синхронизации и попробую еще раз.

**Comment by gropox** [comment]
get_block тоже странно, не возвращает транзакции. Точнее нету атрибута transactions. 

Тестировал с ws.testnet.golos.io

![image](https://user-images.githubusercontent.com/26039472/37564833-23decdd2-2a9e-11e8-8866-67ed94ed22fa.png)

Вот тоже самое, только с продакшена

![image](https://user-images.githubusercontent.com/26039472/37564849-6c6c5d26-2a9e-11e8-9fe4-a39d0ef145d8.png)

**Comment by gropox** [comment]
get_ops_in_block в тестнете работает

![image](https://user-images.githubusercontent.com/26039472/37564913-aa3636bc-2a9f-11e8-87f9-ac3c00a9953f.png)

**Comment by vikxx** [comment]
> get_block тоже странно, не возвращает транзакции
Да. 

Теперь набор плагинов:
`plugin = witness social_network database_api network_broadcast_api private_message raw_block json_rpc account_history market_history follow`

**`get_block` - не возвращает транзакции**

![1](https://user-images.githubusercontent.com/26347159/37565006-b6dc0ff0-2afd-11e8-8f80-408a07c66367.PNG)

`get_ops_in_block` - работает правильно
![2](https://user-images.githubusercontent.com/26347159/37565013-c539fcc4-2afd-11e8-811f-5ebdd7722157.PNG)

**Comment by vikxx** [comment]
Fixed. Tnx @afalaleev
