### ISSUE TITLE
В cli_wallet не работает метод list_my_accounts

### ISSUE THREAD

**Issue by primusd** [GolosChain/golos#474]
При попытке вызова list_my_accounts в cli_wallet выпадает ошибка:

Assert Exception (10)
method_itr != api_itr->second.end(): Could not find method get_key_references

    {"error":"Assert Exception (10)\nmethod_itr != api_itr->second.end(): Could not find method get_key_references\n","data":{"id":3,"error":{"code":-32002,"message":"Assert Exception (10)\nmethod_itr != api_itr->second.end(): Could not find method get_key_references\n","data":{"code":10,"name":"assert_exception","message":"Assert Exception","stack":[{"context":{"level":"error","file":"plugin.cpp","line":174,"method":"find_api_method","hostname":"","thread_name":"th_q","timestamp":"2018-03-24T12:40:31"},"format":"method_itr != api_itr->second.end(): Could not find method ${method}","data":{"method":"get_key_references"}}]}}}}
    th_a  state.cpp:36 handle_reply

**Comment by kotbegemot** [comment]
https://github.com/GolosChain/golos/pull/476
