### ISSUE TITLE
Segfault in cli_wallet on wrong http-request

### ISSUE THREAD

**Issue by afalaleev** [GolosChain/golos#497]
**Steps to reproduce**
1. Run `cli_wallet` with http-interface 
```bash
./cli_wallet  --server-rpc-endpoint="ws://127.0.0.1:8091" --rpc-http-endpoint="0.0.0.0:6789" --rpc-http-allowip=127.0.0.1
```
2. Send request via `curl`:
```bash
curl --data '{"jsonrpc":"2.0","method":"info","params":[ ]}' http://127.0.0.1:6789/rpc
```

**Actual results**
`cli_wallet` is segfaulted

**Expected results**
`cli_wallet` returns an error.

**Comment by zxcat** [comment]
Needs https://github.com/GolosChain/fc/pull/10 to be merged to, so I can set submodule properly

**Comment by kotbegemot** [comment]
https://github.com/GolosChain/golos/pull/520
