### ISSUE TITLE
Add snapshot generator

### ISSUE THREAD

**Issue by ValeryLitvin** [GolosChain/golos#5]

**Comment by ValeryLitvin** [comment]
1. Added snapshot_state structure
2. Added get_account_summary method to database_api which returns account_summary
3. Added generate_snapshot method to wallet which generates snapshot and saves it to json file

**Comment by ValeryLitvin** [comment]
https://github.com/GolosChain/golos/tree/5-snapshot-generator
This branch started from golos master branch which was up-to-date with steemit/steem master at 19.09.2016
We are not going to merge this branch. This branch only for snapshot purpose

**Comment by abitmore** [comment]
Amounts in savings and/or market orders won't be in the snapshot?
