### ISSUE TITLE
Restore get_order_book() format

### ISSUE THREAD

**Issue by bitfag** [GolosChain/golos#507]
vik discovered `get_order_book()` format change. Please restore old behavior.

```
Было:
{ price: 'X.X', quote: XX, base: XX } 

Стало:
{ price: 'X.X', steem: XX, sbd: XX }
```

**Comment by kotbegemot** [comment]
https://github.com/GolosChain/golos/pull/510

**Comment by afalaleev** [comment]
We added method market_history::get_order_book_extended(), because market_history::get_order_book() is already exist.
