### ISSUE TITLE
Develop binary unpacking methods for database objects 

### ISSUE THREAD

**Issue by AKorpusenko** [GolosChain/golos#518]
Figure out how to properly call `fc::raw::unpack` for database objects which inherit chainbase object or develop if it's impossible with the current code. Most likely that many overloads for `unpack` methods should be added :hammer:

**Comment by kotbegemot** [comment]
Check the ability to use in boost::container::allocator tests.
https://www.boost.org/doc/libs/1_58_0/doc/html/boost/container/allocator.html

**Comment by kotbegemot** [comment]
Check the possibility of using:
https://github.com/steemit/steem/blob/develop/libraries/chainbase/include/chainbase/chainbase.hpp
https://github.com/steemit/steem/blob/develop/libraries/chainbase/include/chainbase/allocators.hpp

**Comment by kotbegemot** [comment]
@AKorpusenko

**Comment by AKorpusenko** [comment]
This issue is not valid. There is no need to develop unpack methods as the only case when it's needed is reflect tests. And for reflection tests there is enough features to get correct result of `fc::raw::pack` of any database object. So this task should be closed.
