### ISSUE TITLE
Incorrect error description STEEMIT_OWNER_UPDATE_LIMIT 

### ISSUE THREAD

**Issue by Vik-BC** [GolosChain/golos#522]
Config has a update limit for **owner authority** (and also for master password change )

`#define STEEMIT_OWNER_UPDATE_LIMIT  fc::minutes(60)`
https://github.com/GolosChain/golos/blob/master/libraries/protocol/include/golos/protocol/config.hpp#L240

 When I try to update the owner's key on mainnet less than 60 min, I get a non-correct message from the testnet...
`STEEMIT_OWNER_UPDATE_LIMIT, "Owner authority can only be updated once a minute.");`
https://github.com/GolosChain/golos/blob/master/libraries/chain/steem_evaluator.cpp#L215

![capture](https://user-images.githubusercontent.com/26347159/38420912-3b5484cc-3a0a-11e8-80fe-d9d4bcceea2b.PNG)

Why there is no expected
`STEEMIT_OWNER_UPDATE_LIMIT, "Owner authority can only be updated once an hour.");`
from
https://github.com/GolosChain/golos/blob/master/libraries/chain/steem_evaluator.cpp#L1985

**Comment by afalaleev** [comment]
PR #547
