### ISSUE TITLE
Huge traffic to blog_log file during sync

### ISSUE THREAD

**Issue by t3ran13** [GolosChain/golos#524]
It is free RAM(user 47%) and CPU(used 5%) and read data from blog_log (ssd with read 36mb/s) and write only 1mb. 

It is looks like blog_log reading have to optimase (using RAM??)

it has huge influence to write/read bloks, skiping of blocks, syncing and using nodes at all.

Make priority for it

**Comment by t3ran13** [comment]
2750517ms ntp        ntp.cpp:177                   read_loop            ] ntp_delta_time updated to -749 us

**Comment by t3ran13** [comment]
https://github.com/GolosChain/golos/issues/88

**Comment by t3ran13** [comment]
https://habrastorage.org/webt/zi/39/yz/zi39yzjikeghcs5enamr4czh5g8.png

реплей забивает чтение с диска постепенно, в то время когда во время синка сразуже упирается в скорость диска. Т.е. блок лог слишком часто читается, в разы чаще shared_memory, что очень странно.

**Comment by afalaleev** [comment]
PR #612
