### ISSUE TITLE
private_message plugin causes a mass error on api nodes: "terminate called after throwing an instance of 'fc::assert_exception'"

### ISSUE THREAD

**Issue by vikxx** [GolosChain/golos#529]
Many users reported problems with own API nodes
loop restarts with an error
**`terminate called after throwing an instance of 'fc::assert_exception'`**

![capture](https://user-images.githubusercontent.com/26347159/38485255-0020d708-3c3e-11e8-8724-bf0284da4cd1.PNG)

**Comment by vikxx** [comment]
As reported by users, problem in private messages api

**Comment by vikxx** [comment]
Deleting plugin from `config.ini` restores work
![capture](https://user-images.githubusercontent.com/26347159/38485690-939cd940-3c3f-11e8-853a-4d634d4ae015.PNG)

**Comment by asuleymanov** [comment]
Скорее всего к проблеме привела обычная отправка private_message.
Строка которую я отправлял ниже.

`jsonString := "[\"private_message\"," +
        "{\"from\":\"" + from +
        "\",\"to\":\"gbot\"" +
        ",\"from_memo_key\":\"GLS5kc9FKrjBsPchpTeX84KdDVHa9pJ21PgLZCux8uDfFyqWBGZWx\"" +
        ",\"to_memo_key\":\"GLS5SVBL6qTTiaD1qbxNFqksfxzdenAok2ToNc4uCTXKXLVrNQRnx\"" +
        ",\"sent_time\":0" +
        ",\"checksum\":0" +
        ",\"encrypted_message\":\"" + hex.EncodeToString([]byte("test")) + "\"}]"`
