### ISSUE TITLE
увеличить число тегов в посте

### ISSUE THREAD

**Issue by t3ran13** [GolosChain/golos#534]
https://github.com/GolosChain/tolstoy/issues/625#event-1565965178

Сейчас из поста обрабатываются первые 5 тегов, нужно сделать хотя бы на парочку больше

**Comment by gropox** [comment]
Это ограничение golos.io

**Comment by litrbooh** [comment]
@gropox 
ты не прочитал ссылку
https://github.com/GolosChain/tolstoy/issues/625#issuecomment-380070216

**Comment by litrbooh** [comment]
@t3ran13 , наверно надо как-то по другому сформулировать ищью,  что надо доработать API, чтобы оно позволяло каталогизировать по большему числу тегов в посте.

**Comment by t3ran13** [comment]
Я хочу больше тегов. Делайте что хотите, но дайте мне это))

**Comment by gropox** [comment]
Уже сейчас можно задать хоть сколько тэгов. Катологизация контента по тэгам в ноде не нужна, как мне кажется. 

С ростом числа тэгов будет расти потребление памяти.  Кому надо, пускай сам и каталогизирует контент как ему удобнее и подходяще для его целей. 

По крайней мере пока не сделают нормальную базу данных, с джойнами, увеличивать число обрабатываемых тэгов нодой не стоит.

**Comment by pavelit** [comment]
Мама, а inmemory база данных с джойнами существует?

Нет сынок, это фантастика.

**Comment by litrbooh** [comment]
@gropox 
Как можно делать серьезное приложение, с каталогом на 5 тегов? Или каждый должен тогда как Толя, делать БД и самому лопать теги?

**Comment by gropox** [comment]
@litrbooh Я все понимаю. Просто считаю, что с в настоящее время используемой базой данных это повлечет за собой больший расход памяти. Имхо.

Ко всему прочему tags функционал слили в social_network плагине, в месте с get_content.  Так как мне лично поиск по тэгам не нужен в моей ноде, статистики тоже. Не всем это надо.

Ну ладно тэги сами по себе и фильтрация по тэгам нужны в блоГчейне, но статистики мне кажется субъективны.  

Потому надо функционал разнести для начала по разным плагинам или сделать гибче настраиваемым. Мне лично наравится, если нода работает не потребляя кучи памяти. А паразитам конечно все равно сколько нода жрет, мне жалко golos.io и @vik-а содержащих полные ноды.

**Comment by t3ran13** [comment]
@gropox голос.io само от этого выйграет) имхо, но апп с малым количеством тегов в то время когда карабли бороздят просторы вселенной... это уже 90е=)

**Comment by afalaleev** [comment]
Closed by #752

**Comment by t3ran13** [comment]
вынестите число тегов в конфиг ноды
не все апп будут использовать 15 тегов, но у всех будет уходить память под их хранение, должна быть гибкость по аналогии с аккаунт хистори
