### ISSUE TITLE
Проанализировать работу private_message plugin

### ISSUE THREAD

**Issue by marijadia** [GolosChain/golos#538]
Понять как работет private_message plugin и какие данные необходимы для него. 
Протестировать плагин на принятие этих данных и корректную отработку по ним. Убедиться в отсутствии ошибок.

**Comment by zxcat** [comment]
Плагин обрабатывает `custom_json` вида
```
[
  "private_message", 
  {
    "from": name1,
    "to": name2,
    "from_memo_key": memo1,
    "to_memo_key": memo2,
    "sent_time": int1,
    "checksum": int2,
    "encrypted_message": msg
  }
]
```
После поверхностных проверок объект кладётся в бд. При этом не проверяются поля `checksum`, `encrypted_message`, а `sent_time` проверяется только на отличие от 0.

Кроме того, плагин предоставляет два метода: `get_inbox` и `get_outbox`, каждый из которых принимает `(string name, time_point newest, uint16_t limit)`, где `name` — имя аккаунта, `newest` — минимальное время получения сообщения, `limit` — число сообщений для возврата. Методы возвращают массив сообщений, в которых имя получателя/отправителя совпадает с переданным `name`.

Шифрование, работа с контрольной суммой, получение сообщений двустороннего диалога должны производиться на стороне клиента.

**Comment by zxcat** [comment]
Как по мне, плагин избыточен (лишние поля `from_memo_key`, `to_memo_key`, `sent_time`, `checksum`) и дублирует имеющиеся в `transfer` возможности. То есть нет смысла хранить отдельно объекты сообщений, с этим прекрасно справляется `transfer`. Но у `transfer` не хватает удобных методов выборки `get_inbox` и `get_outbox`.
В то же время у `transfer` есть плата за сообщение и более дорогой `market_bandwidth` для пользователя, что автоматически отсекает спам-ботов.

Приватные сообщения не должны быть дешёвыми, т.к. каждое сообщение (в отличие от постов/комментов), не даёт сети (всей) чего-либо ценного, оно даёт ценность только двум участникам диалога. И в то же время на поддержку сообщений требуются ресурсы всей сети.
