### ISSUE TITLE
Move comment body, title, and metadata to separate object

### ISSUE THREAD

**Issue by kotbegemot** [GolosChain/golos#541]
Our undo database is naive but safe and copies the entire old object. The dynamic fields in the comment object can be very large and copying them can be expensive. Each vote modifies the rshares of the comment object and requires a copy of the entire object. The reduce needless copying, the dynamic fields in the comment object (body, title, metadata) that are rarely changed, should go in their own object and reconstructed when queried by an API.

- [x] Split comment object
- [x] Adapt comment evalutators
- [x] Adapt social_network plugin
- [ ] Adapt mongo_db plugin - doesn't exist in 18.0
- [x] Adapt follow plugin

**Comment by afalaleev** [comment]
Tested. No bugs found.
