### ISSUE TITLE
Implement unicode tags support

### ISSUE THREAD

**Issue by serejandmyself** [GolosChain/golos#55]

**Comment by 21xhipster** [comment]
Не совсем понимаю, как это относится в `golosd`?

**Comment by Nemo1369** [comment]
tags_plugin stores primary and supplementary tag names in a one-byte-element string, so it disables Unicode usage.

С уважением,

Михаил Комаров
nemo1369@gmail.com

**Comment by Nemo1369** [comment]
Closed as already implemented.
