### ISSUE TITLE
comment object separate object : Split comment object

### ISSUE THREAD

**Issue by kotbegemot** [GolosChain/golos#554]
https://github.com/GolosChain/golos/issues/541
- [ ] add comment_content_object
- [ ] add index comment_content_object
- [ ] update evalutators

**Comment by vpavliv** [comment]
Duplicate 
https://github.com/GolosChain/golos/issues/541

**Comment by afalaleev** [comment]
There were no changes, because it is duplicate issue. Move to Done.
