### ISSUE TITLE
Please publish LOW MEM on docker hub

### ISSUE THREAD

**Issue by gropox** [GolosChain/golos#556]
Please publish LOW MEM on docker hub like 0.17.2_lowmem or build like steemit two different kinds of golosd in same docker image - full and lowmem

**Comment by afalaleev** [comment]
GolosCore publishes 3 types of docker images:
1. goloschain/golos:latest
1. goloschain/golos:latest-testnet
1. goloschain/golos:latest-lowmem
1. goloschain/golos:latest-mongo

https://github.com/GolosChain/golos/blob/master/.travis.yml
