### ISSUE TITLE
Настроить сегмент 

### ISSUE THREAD

**Issue by serejandmyself** [GolosChain/golos#56]

**Comment by 21xhipster** [comment]
@tomarcafe Давай передадим дела по этому таске ребятам. У нас там же много чего сделано

**Comment by tomarcafe** [comment]
@serejandmyself заводите организацию в сегменте

**Comment by serejandmyself** [comment]
Я так понял @21xhipster уже создал и выслал мне счет, но я пока не получил. Как получу, оплатим сразу, чтобы можно было людей приглашать

**Comment by serejandmyself** [comment]
@21xhipster @tomarcafe Выслал приглашение на настройку

**Comment by 21xhipster** [comment]
Не имеет отношение к этому проекту. Перенес [сюда](https://github.com/GolosChain/golosment/issues/1)
