### ISSUE TITLE
Write an API reference

### ISSUE THREAD

**Issue by serejandmyself** [GolosChain/golos#57]
API reference + Guidlines etc

Решить как мерджить на лендинг

**Comment by 21xhipster** [comment]
Имеет смысл начать [отсюда](https://github.com/GolosChain/dev/issues/1)

**Comment by serejandmyself** [comment]
http://api.doc.developers.golos.io/?Javascript#introduction

**Comment by 21xhipster** [comment]
Круто! Мой и Валеркин текст туда надо добавить

**Comment by serejandmyself** [comment]
@pavelit

**Comment by pobedite** [comment]
Тексты в студию! Я добавлю.

**Comment by pavelit** [comment]
Тексты в студию! Я добавлю.

**Comment by serejandmyself** [comment]
Так они у тебя есть )

Я так понимаю речь об этом https://github.com/GolosChain/dev/blob/master/docs.md @21xhipster ?
