### ISSUE TITLE
Remove forever empty fields from discussion

### ISSUE THREAD

**Issue by AKorpusenko** [GolosChain/golos#572]
Figure out what fields in `social_network` plugin are always empty. After that delete such ones to clean the API.

**Comment by AKorpusenko** [comment]
Following fields have been deleted from `social_network::discussion`:
- `reblogged_by` 
- `first_reblogged_by`
- `first_reblogged_on`

**Comment by afalaleev** [comment]
I'm sorry, but we can't do it. We should fix filling of `reblogged_by`:  #327

**Comment by afalaleev** [comment]
Not tested, because issue was closed as invalid.
