### ISSUE TITLE
Move extra methods from social_network to tags plugin

### ISSUE THREAD

**Issue by AKorpusenko** [GolosChain/golos#580]
Leave
- `get_content`
- `get_content_replies`
- `get_all_content_replies`
- `get_account_votes`
- `get_active_votes`
in `social_network`, **all others** move to `tags` plugin

**Comment by afalaleev** [comment]
PR #632

**Comment by afalaleev** [comment]
PR #632

**Comment by afalaleev** [comment]
Tested. No bugs found.
