### ISSUE TITLE
Проблема синхронизации ноды после мержинга 15 и 16 хардфорков с chainbase

### ISSUE THREAD

**Issue by ValeryLitvin** [GolosChain/golos#59]
В данный момент наблюдается проблема с синхронизацией ноды в текущей сети в последнем релизе после мержинга кода 15 и 16 хардфорков с chainbase и shareddb

**Comment by ValeryLitvin** [comment]
https://github.com/GolosChain/golos/tree/59-node-sync

**Comment by Nemo1369** [comment]
Closed by 66b4329da8d6091cc5d483ba2b06073e3c2969cd
