### ISSUE TITLE
Add API method to get received vesting delegations

### ISSUE THREAD

**Issue by zxcat** [GolosChain/golos#592]
> Если можно, добавьте метод для получения делегированной СГ с точки зрения получателя.
>
> Сейчас имплементирован только один метод get_vesting_delegations, он возвращает делегированную СГ другим пользователям, а нужен еще метод, который бы возвращал полученную СГ, что будет нужнее. К примеру для вознаграждения вкладчиков. К примеру get_vesting_receivings :) or get_vesting_receptions or get_vests_receved
>
> Иначе для учета полученной СГ сторонним приложениям придется городить свой учет полученной СГ, что потребует либо сканирование истории либо запись полученной СГ в своей базе данных (либо дописывания плагина самому).

https://github.com/GolosChain/golos/issues/535#issuecomment-383726572

**Comment by afalaleev** [comment]
Tested. No bugs found.
