### ISSUE TITLE
get_accounts return error "unknown key"

### ISSUE THREAD

**Issue by AKorpusenko** [GolosChain/golos#599]
In branch `golos-v0.18.0` calling `database_api::get_accounts` returns such error:
```
{
    "jsonrpc": "2.0",
    "error": {
        "code": -32000,
        "message": "unknown key"
    },
    "id": null
}
```
with this curl response: 
```curl -s --data-binary '{"jsonrpc": "2.0","method":"call","params":["database_api", "get_accounts" [["cyberfounder"]]]}' -H 'content-type: text/plain;' http://0.0.0.0:8090 | json_reformat``` 

Repeat the bug this way:
1. golos-v0.18.0 
2. `cmake -DBOOST_ROOT=/opt/boost_1_58_0 -DBUILD_GOLOS_TESTNET=ON'
alias cmake_testnet='cmake -DBOOST_ROOT=/opt/boost_1_58_0 -DCMAKE_BUILD_TYPE=Debug -DBUILD_GOLOS_TESTNET=TRUE -DBUILD_SHARED_LIBRARIES=FALSE -DLOW_MEMORY_NODE=FALSE -DCHAINBASE_CHECK_LOCKING=FALSE -DCLEAR_VOTES=TRUE`
3. `make golosd`
4. use `share/config/debug_config.ini` 
5. `./golosd`
6. `curl -s --data-binary '{"jsonrpc": "2.0","method":"call","params":["database_api", "get_accounts" [["cyberfounder"]]]}' -H 'content-type: text/plain;' http://0.0.0.0:8090 | json_reformat`

Look at 
https://github.com/GolosChain/golos/commit/674306810e4282bdaa9ba1af2ed8c3c38d688226#diff-6b48264620c926ea581a987a9c713c3cR61
and 
https://github.com/GolosChain/golos/blob/golos-v0.18.0/libraries/chain/database.cpp#L2937

**Comment by afalaleev** [comment]
Tested. No bugs found.
