### ISSUE TITLE
Add limitation on title and memo fields in proposal.

### ISSUE THREAD

**Issue by afalaleev** [GolosChain/golos#629]
- Limit size of proposal title to 256 symbols.
- Limit size of proposal memo to 4096 symbols.

**Comment by afalaleev** [comment]
PR #630

**Comment by zxcat** [comment]
Tested. No bugs found.

**Comment by zxcat** [comment]
Btw, we can move magic numbers to defines like `#define STEEMIT_MAX_MEMO_SIZE                   2048`, `#define STEEMIT_MAX_PERMLINK_LENGTH             256` or reuse such defines.
