### ISSUE TITLE
cli_wallet doesn't export commands for transaction builder

### ISSUE THREAD

**Issue by afalaleev** [GolosChain/golos#633]
**Steps to reproduce**
1. `./cli_wallet --server-rpc-endpoint="ws://127.0.0.1:8091"`
2. call command: `begin_builder_transaction`

**Actual results**
cli_wallet returns error about wrong command 

**Expected results**
cli_wallet returns ID of `transaction builder`

**Comment by afalaleev** [comment]
PR #634

**Comment by zxcat** [comment]
[Tested](https://github.com/GolosChain/Qa/blob/master/TestCase/ProposalTransactions/cli_wallet.md), no bugs found in this issue.
Found bug related to parent issue #542, see #671
