### ISSUE TITLE
Malformed tx in cli_wallet propose_builder_transaction

### ISSUE THREAD

**Issue by zxcat** [GolosChain/golos#636]
If `propose_builder_transaction` command fails, the following (fixed) `propose_builder_transaction` will nest `proposal_create` inside `proposed_operations`.

Steps to reproduce:
1. On fresh testnet node create accounts and fund them (optional, if accs not exist):
```
create_account cyberfounder alice "" true
create_account cyberfounder bob "" true
create_account cyberfounder cat "" true
transfer cyberfounder bob "101.000 GOLOS" "" true
transfer_to_vesting cyberfounder alice "1.000 GOLOS" true
transfer_to_vesting cyberfounder bob "1.000 GOLOS" true
```
2. Begin builder transaction. Note `0` (following `add_operation_to_builder_transaction`) should be replaced with id returned by `begin_builder_transaction`
```
begin_builder_transaction
add_operation_to_builder_transaction 0 ["transfer", {"from":"alice", "to":"cat", "amount":"100.000 GOLOS", "memo":"part one"}]
add_operation_to_builder_transaction 0 ["transfer", {"from":"bob", "to":"cat", "amount":"100.000 GOLOS", "memo":"part two"}]
```
3. `preview_builder_transaction 0` — shows correct transaction with 2 ops.
4. Run `propose_builder_transaction`, which will fail
```
lock
propose_builder_transaction 0 alice test "memo" "2018-05-11T09:15:00" "2018-05-11T09:14:00" true
```
6. `preview_builder_transaction 0`

**Expected results**
`preview_builder_transaction 0` shows the same tx as in step 3

**Actual results**
`preview_builder_transaction 0` shows nested proposal

**Comment by afalaleev** [comment]
Tested. No bugs found. Move to Done.

**Comment by afalaleev** [comment]
Add issue about small improvement for a proposal builder in cli_wallet #669
