### ISSUE TITLE
Simplify proposals nesting in cli_wallet

### ISSUE THREAD

**Issue by zxcat** [GolosChain/golos#641]
It's possible to create proposals with `propose_builder_transaction`. In addition, this command wraps it's `builder_transaction` in `proposal_create` operation. But there is no simple method to nest several sibling proposals inside parent proposal.

Solution: add command to copy operation between `builder_transaction`s, so `proposal_create` operation can be pushed to arbitrary place of other `builder_transaction` (parent).

**Comment by afalaleev** [comment]
PR #642

**Comment by afalaleev** [comment]
Tested. No bugs found.
