### ISSUE TITLE
Not all ops applied on proposal transaction approve

### ISSUE THREAD

**Issue by zxcat** [GolosChain/golos#644]
[Testcase](https://github.com/GolosChain/Qa/blob/master/TestCase/ProposalTransactions/fail_to_apply.md).

Here is some issues:
1. Transaction fails:
```
proposal_evaluator.cpp:157    do_apply             ] Proposed transaction jim::fund failed to apply once approved with exception:
----
10 assert_exception: Assert Exception
_db.get_balance(from_account, o.amount.symbol) >= o.amount: Account does not have sufficient funds for transfer.
    {}
    th_0  steem_evaluator.cpp:933 do_apply
    {"proposal.author":"jim","proposal.title":"fund"}
    th_0  database_proposal_object.cpp:43 push_proposal
----
Will try again when it expires.
```
But first transfer applied and pushed to blockchain.

2. Executing any `proposal_update` again (`approve_proposal jim fund {"active_approvals_to_add":["jim"]} true`), will push another `transfer` to blockchain.

**Comment by afalaleev** [comment]
PR #645
