### ISSUE TITLE
Move get_feed_history to database_api

### ISSUE THREAD

**Issue by afalaleev** [GolosChain/golos#651]
Return two methods from witness_api to database_api:
- get_current_median_history_price
- get_feed_history

**Comment by zxcat** [comment]
Why? They are light enough can be useful for witness

**Comment by afalaleev** [comment]
This is common information for all users, not only for witnesses.

**Comment by afalaleev** [comment]
Discussed in the development team. 
The `witness_api`- plugin is very very light, it doesn't create any additional indexes, so it can be enabled without any additional load on the server. 
Moving these methods back to the `database_api`-plugin will made `database_api` too complicated.
When
