### ISSUE TITLE
Request of steemit-imported accounts with get_key_references returns an empty array

### ISSUE THREAD

**Issue by primusd** [GolosChain/golos#66]
В клиенте cli_wallet (v16.3) некорректно работает команда list_my_accounts

Она не видит и, соответственно, не выдаёт информацию об аккаунтах, перенесённых в Голос из Стима на этапе генезиса сети (файл snapshot5392323.json).

Работа с ключами этих аккаунтов в cli_wallet при этом происходит нормально, т.е. все команды, требующие соответсвующих ключей (Active, Posting и т.п.) отрабатывают нормально, если ключи есть в файле wallet.json

Не работает именно команда list_my_accounts

Баг не критичный для сети, хардфорка не требует, но исправить нужно, т.к. это доставляет неудобства при работе с сетью из командной строки клиента.

**Comment by tomarcafe** [comment]
есть предположение, что это связано с метадатой.

так вышло, что у генезис-аккаунтов по умолчанию в json_metadata записывалась строка, которую json-парсер обламывается распознать

**Comment by Nemo1369** [comment]
@tomarcafe Хорошее предположение, однако в таком случае подобное поведение следовало ожидать и в 14.2, ведь в указанной ревизии аналогичное содержание json_metadata присутствует: https://github.com/GolosChain/golos/blob/golos-v0.14.2/libraries/chain/database.cpp#L2707

В любом случае, я проверю это предположение.

**Comment by primusd** [comment]
По-моему, проблема в том, что в новом плагине [account_by_key](https://github.com/GolosChain/golos/blob/master/libraries/plugins/account_by_key/account_by_key_plugin.cpp) нет условия поиска аккаунтов, созданных при [старте сети](https://github.com/GolosChain/golos/blob/golos-v0.14.2/libraries/chain/database.cpp#L2679)

Эти аккаунты не попадают ни в одну из категорий операций account_create_operation, pow_operation или pow2_operation, поэтому плагин их и не находит.

**Comment by Nemo1369** [comment]
Fixes with replaying the blockchain

**Comment by Nemo1369** [comment]
Will be fixed with a #75.

**Comment by Nemo1369** [comment]
Closed with ab81eceacbfdf91b01546a643067b4cc967be289
