### ISSUE TITLE
Improve history-ops filters usability

### ISSUE THREAD

**Issue by zxcat** [GolosChain/golos#668]
**1. Simplify `history-whitelist-ops` and `history-blacklist-ops` config options**.
Values of this options are operation names. But it's not obviously, that they should be set as `vote_operation`, `transfer_operation`, etc…

Propose change this behavior to support simple `vote`, `transfer`, etc… values.  
*(add `+ "_operation"`: [source code](https://github.com/GolosChain/golos/blob/1b2eb43f3f6e4f78aa771c4ffd35ce249775bccf/plugins/operation_history/plugin.cpp#L199))*

**2. Allow usage of `history-start-block` config option alone**
The current logic makes it hard to use `history-start-block` without black/whitelist filters. Whitelist filter activated by default, so it's needed to fill it with all possible operations.

Propose change default behavior, so blacklist filter will be activated by default. In this case filter can be empty, and `history-start-block` will work as expected without any additional options.
*([source code](https://github.com/GolosChain/golos/blob/1b2eb43f3f6e4f78aa771c4ffd35ce249775bccf/plugins/operation_history/plugin.cpp#L138))*

**Comment by afalaleev** [comment]
PR #778
