### ISSUE TITLE
Foreign key approval prevents proposal from apply

### ISSUE THREAD

**Issue by zxcat** [GolosChain/golos#671]
**Adding foreign (not required to sign) key approval makes proposal impossible to apply until that key approval removed**

```
begin_builder_transaction
add_operation_to_builder_transaction 0 ["transfer", {"from":"alice", "to":"bob", "amount":"1.000 GOLOS", "memo":"to bob"}]
add_operation_to_builder_transaction 0 ["transfer", {"from":"bob", "to":"alice", "amount":"1.000 GOLOS", "memo":"to alice"}]
propose_builder_transaction 0 alice test671 "" "2018-05-23T15:50:00" "1970-01-01T00:00:00" true
get_proposed_transactions alice 0 10
```
Here `required_active_approvals` field contains `["alice", "bob"]`.
Let's add alice's approval and public key of initminer:
```
approve_proposal alice test671 {"active_approvals_to_add":["alice"], "key_approvals_to_add":["GLS58g5rWYS3XFTuGDSxLVwiBiPLoAyCZgn6aB9Ueh8Hj5qwQA3r6"]} true
get_proposed_transactions alice 0 10
```
And add required bob's approval:
```
approve_proposal alice test671 {"active_approvals_to_add":["bob"]} true
get_proposed_transactions alice 0 10
```

**Expected result:** proposal applied successfully.

**Actual result:** proposal still exists and waiting approvals, ignoring that
`"required_active_approvals": ["bob","alice"],`, `"available_active_approvals": ["bob","alice"]`

***
*Note: Proposal will be applied on initminer public key remove:  
`approve_proposal alice test671 {"key_approvals_to_remove":["GLS58g5rWYS3XFTuGDSxLVwiBiPLoAyCZgn6aB9Ueh8Hj5qwQA3r6"]} true`*
***

Ref: #542, #633

**Comment by afalaleev** [comment]
PR #680

**Comment by zxcat** [comment]
Tested, found not related bug in cli_wallet #699. Move to Done
