### ISSUE TITLE
Optional field `reputation` in API methods results

### ISSUE THREAD

**Issue by afalaleev** [GolosChain/golos#674]
It is not useful to have more than one API methods with same name but with different results. Now we have `get_accounts` in `follow` and `database_api`. All difference is in the field `reputation`. To increase flexibility we can make one API method in `database_api`, but with optional field `reputation`. If a node has enabled plugin `follow` the method should return a value  in the `reputation`, if `follow` plugin is disabled a result shouldn't have a field `reputation`.

**Comment by afalaleev** [comment]
PR #675

**Comment by zxcat** [comment]
Tested, bug found: #688
