### ISSUE TITLE
Change default value for GOLOS_CREATE_ACCOUNT_WITH_GOLOS_MODIFIER to 1

### ISSUE THREAD

**Issue by afalaleev** [GolosChain/golos#697]
Currently, the default value is 30.
It is too big, and will change create account fee on start of HF 18.

The fee for the creation of account without delegation is:
```
30 * account_creation_fee
```
After change from `30` to `1`, it will be the same as before HF 18:
```
1 * account_creation_fee
```

The fee for the creation of account with delegation is:
```
30 * 5 * account_creation_fee
```
After changing `30` to `1`, the creation with delegation will require 5 account_creation_fees, from which 1 creation fee can be paid for creation and 4 account_creation_fees should be delegated:
```
1 * 5 * account_creation_fee
```

**Comment by afalaleev** [comment]
PR #698

**Comment by zxcat** [comment]
Tested, no bugs found
