### ISSUE TITLE
cli_wallet can't sign tx if account have account_auths added

### ISSUE THREAD

**Issue by zxcat** [GolosChain/golos#699]
**Steps to reproduce:**
1. Add bob into alice's account_auth *(change key to alice's public key)*
```
begin_builder_transaction
add_operation_to_builder_transaction 0 ["account_update", {"account":"alice", "posting":{"weight_threshold":1,"account_auths":[["bob",1]],"key_auths":[["GLS6UADxV2WAAmZxGNd7AKCPW9fXoL2XqrUYBS1Y3Ptyf3v4D9BJb",1]]} }]
sign_builder_transaction 0 true
```
2. Try create post from alice
```
post_comment alice test699 "" test "Test post!" "<h1>title!</h1><p>hello!</p><hr>test..." "{}" true
```

**Expected result**: post created

**Actual result**: `cli_wallet` fails with assert
```
10 assert_exception: Assert Exception
it != approving_account_lut.end():
    {}
    th_0  wallet.cpp:724 operator()
```

**Comment by maslenitsa93** [comment]
Why you putting bob into `account_auths` and want a successful post creation? What's a purpose?

**Comment by zxcat** [comment]
@maslenitsa93, it's just to reproduce bug here. Real usage can be multisigs or posting delegation (give other account rights to posting from yours).

Bug is that cli_wallet can't sign tx if account have additional auths

**Comment by BaroH4er** [comment]
**v0.18.4**

Try create post from alice:
```
post_comment alice test699 "" test "Test post!" "<h1>title!</h1><p>hello!</p><hr>test..." "{}" true

```
#### Result: 
`post created`

![2018-07-27 15-37-54](https://user-images.githubusercontent.com/21989598/43321015-4b23b30e-91b3-11e8-9e02-782b731761dd.png)


- [x] Fixed
