### ISSUE TITLE
Create a list of id's for side web clients in order to identify incoming posts 

### ISSUE THREAD

**Issue by serejandmyself** [GolosChain/golos#71]
To be written inisde json.metadata 

- [ ] golos.io : 89bd085674beca223acfb023d5ce260d43382d5ed1b7140bb4da35211802e122

- [ ] platform.molodost.bz : c980682dd264dc6912522059f8697e60e98a7ed5e393dc510facf082a00b42a7

- [ ] mapala.net : 7a6c51a5881189ecb21f9357400999be27570d030e241de0a04bc517748a0ef6

- [ ] golos.rubtc.info : 8fe7a7fdc63e4de1f7cd498d543415381980af400e1667c379e0d2141313d4e3

- [ ] esteem.ws : 35e377365f5734b0a741c3bc02f3b37c0af3a040aac6a539d19fd4b1956e852e

**Comment by testzcrypto** [comment]
Please use app param in **json_metadata**, for [example](https://steemd.com/tx/3a304d38919c6bddaefbcff7684b9752930d05e9): {"tags":["news","life","people","politics","world"],"image":["https://i.imgsafe.org/2d0e32a6bb.jpeg"],**"app":"steemit/0.1"**,"format":"markdown"}

Last chart count posts by app: https://steemdata.com/charts

**Comment by 21xhipster** [comment]
Если честно не понимаю зачем писать ключи в каждый пост. @testzcrypto говорит правильные вещи. Это компактнее, понятнее и удобнее.

**Comment by serejandmyself** [comment]
Ну так это мы и собираемся использовать...

**Comment by 21xhipster** [comment]
Исходя из issue это не понятно

**Comment by Nemo1369** [comment]
@testzcrypto That is the key we would like to store the identifier in. But the identifier would be a sha256 hash.

**Comment by 21xhipster** [comment]
@Nemo1369 Какой в этом смысл?

**Comment by feruzm** [comment]
what @testzcrypto proposed is the standard that all Steem projects use, I don't see point of having separate hash for it. If there is no `app` section in post `json_metadata` then it is considered to be published from cli_wallet or other apps which can be asked to follow standard.

https://golos.io/ru--golos/@good-karma/standartnyi-i-otkrytyi-json-dlya-doverennye-rabochie-processy-v-golos

**Comment by Nemo1369** [comment]
@feruzm @testzcrypto @21xhipster Oh well, there are no any technical reason to store a hash in the 'app' key. Let us just store a client name according to a standard.
