### ISSUE TITLE
Bug with cli_wallet and witnes_update

### ISSUE THREAD

**Issue by t3ran13** [GolosChain/golos#713]
if i try broadcast witnes_update i get 

Assert Exception (10)
api_itr != _registered_apis.end(): Could not find API witness_api

wtf? i did not read info, i send trx

**Comment by zxcat** [comment]
@t3ran13, is `witness_api` plugin enabled on your node?
when you call `update_witness`command in `cli_wallet`, it's not direct broadcast. `cli_wallet` first reads some data from node, including `get_witness_by_account`.

You can broadcast directly using transaction builder (`begin_builder_transaction`, `add_operation_to_builder_transaction`, `sign_builder_transaction`) or use external libs like `golos-js`

**Comment by t3ran13** [comment]
get_witness_by_account is not necessary, node checks keys when got trx

**Comment by zxcat** [comment]
`get_witness_by_account` required to get previous value of `url` field. if you pass to `update_witness` `null` value as url , previous on will be used.

It's possible to improve this logic so `get_witness_by_account` will be called only if url=null
