### ISSUE TITLE
Получить в cli_wallet все пары ключей для конкретного пользователя

### ISSUE THREAD

**Issue by muhazzz** [GolosChain/golos#722]
В cli_wallet сейчас очень неудобно сделан вывод ключей - list_keys вываливает гору ключей для абсолютно всех аккаунтов, при чём в разброс и без подписи их типов. Если нужно создать нового юзера через cli_wallet и передать ему все пары его ключей, то использование cli_wallet превращается в ад - 
приходится каждый раз извращаться, запрашивать сначала список публичных ключей юзера через get_account <username>, выписывать оттуда паблики куда-то, а потом по list_keys искать и сопоставлять все эти паблики.
Супер неудобно!

Удобно было бы:
1. Либо добавить в list_keys вывод владельца каждого ключа и их типы (active, posting, memo, etc.)
2. Либо добавить параметр list_keys username, чтобы получить все ключи для конкретного пользователя (но указание типов всё равно нужно и в этом случае)
3. Либо сделать и 1 и 2 - самый удобный вариант

**Comment by afalaleev** [comment]
PR #757
