### ISSUE TITLE
Simplify votable delegation parameters

### ISSUE THREAD

**Issue by zxcat** [GolosChain/golos#726]
Now we have multipliers to calculate delegation parameters:
```
account_creation_fee
create_account_with_golos_modifier
create_account_delegation_ratio
min_delegation_multiplier
```

This makes system flexible, but somewhat hard to understand.

To simplify, we can change this to absolute values:
```
account_creation_fee
create_account_min_golos_fee
create_account_min_delegation
min_delegation
```

All this values can be set in GOLOS.

* `account_creation_fee` — used only in `create_account` operation (as in previous HF)
* `create_account_min_golos_fee` — minimal fee (in GOLOS) payed when create account with delegation
* `create_account_min_delegation` — minimal GP delegation amount when create account with delegation (can be reduced if fee > `create_account_min_golos_fee`)
* `min_delegation` — minimal delegated GP

**Comment by bitfag** [comment]
What is the difference between `create_account_min_delegation` and `min_delegation`?

**Comment by zxcat** [comment]
@bitfag,
> What is the difference between create_account_min_delegation and min_delegation?

`create_account_min_delegation` — account creator delegates at least this amount
`min_delegation` — it's not related to account creation, just minimal amount anybody can delegate

**Comment by zxcat** [comment]
PR #728
