### ISSUE TITLE
Create system of numerical errors 

### ISSUE THREAD

**Issue by marijadia** [GolosChain/golos#741]
Локализация ошибок блокчейна:
Now we have only output of errors in text form. It is difficult to parse errors.
We need to create a standart of error codes. 
 
Related 
https://github.com/GolosChain/golos/issues/218
https://github.com/GolosChain/golos/issues/267

**Comment by s-medvedev** [comment]
В данный момент обработка ошибок ведется двумя разными способами:
- выкидывание исключений (диаграмму исключений см. ниже). Этот подход представлен:
  - в виде исключений от проекта STEEM
  - исключениями в библиотеке FC
  - немного есть в новом реализованном функционале, см. GOLOS_ASSERT & GOLOS_DECLARE_DERIVED_EXCEPTION
- проверкой условий макросом FC_ASSERT, который генерирует исключение fc::assert_exception
---
Все ошибки, которые выявляются макросом FC_ASSERT можно разделить на несколько категории:
- неподдерживаемая операция
- неверное количество аргументов переданных плагину. Как правило выполняется макросом CHECK_ARG_SIZE & CHECK_ARGS_COUNT. В некоторых местах проверка выполняется прямо в коде метода.
- невалидное значение параметра. В данном случае проверяются значения параметров на корректность (наличие недопустимых символов в именах аккаунтов, правильность записи единиц актива, длины комментариев и т.д.)
- превышение лимита на выдачу результата операции
- неверный JSON-API запрос: отсутствие необходимых полей запроса, запрос к несуществующему методу.
- неверная структура транзакции
- отсутствует указанный объект (например аккаунт или транзакция)
- отсутствие требуемого hardfork
- ошибки бизнес-логики. Сюда относятся неправильное использование клиентом бизнес-объектов (например попытка подписаться на себя). В данной категории можно выделить следующие подкатегории:
  - недостаточное количество активов для выполнения операции
  - превышение bandwidth (на размещение постов, голосование...)
- ошибки сервера (например отсутствует доступ до NTP-сервера)
- внутренние ошибки. Сюда попадают все ошибки, которые разработчик не предполагает, что будут возникать. Их можно разделить на следующие категории:
  - ошибки, прилетевшие из используемых библиотек. Данные ошибки должны транслироваться в одну из предыдущих ошибок, но если они не были пойманы, то могут дойти до пользователя.
  - недопустимое использование функций внутри кода. Если эта ошибка возникла, то это говорит о наличие ошибки в коде. Клиент с данной ошибкой не сможет самостоятельно ничего сделать, только показать разработчикам. Это как раз те проверки, которые должны были проверяться с использованием ASSERT.
- выполнение операции на заблокированном cli_wallet

На основе данных категорий предполагается сформировать иерархию классов ошибок. Данные классы ошибок будут содержать код ошибки, который будет передаваться клиенту в ответе JSON-API. Конкретные ошибки внутри категории будут разделяться по дополнительному полю.

---
Существующие исключения отображены на диаграмме (неиспользуемые исключения отображены серым цветом, исключения библиотеки STEEM не показаны):
![exception.png](https://images.zenhubusercontent.com/5b39de7eaf2e4e3c8d3cb122/22cf7779-1a30-4f13-bea7-71faa232c836)
