### ISSUE TITLE
To filter the history of user operations

### ISSUE THREAD

**Issue by marijadia** [GolosChain/golos#742]
Фильтрация данных с целью исключения или фильтрования истории операций пользователя:
There is no feature that allows to filter the history of user operations. We get a lot of not needed information, so there should be some tool to set filters by type of user operations, create clear name of operations, white/black lists etc. 
Related 
https://github.com/GolosChain/golos/issues/668
https://github.com/GolosChain/golos/issues/701
https://github.com/GolosChain/golos/issues/442

**Comment by afalaleev** [comment]
- [ ] Add index by (`operation type`, `direction`) in the `account_history`-plugin
- [ ] Add optional arguments to the API call `account_history::get_account_history`:
- list of operation names
- type of direction (`sender`, `receiver`, `any`)
- [ ] Add additional arguments to the cli_wallet

**Comment by afalaleev** [comment]
PR #841

**Comment by gropox** [comment]
Интересно, кто заказал такую фильтрацию по истории пользователя? По моему как то почти совсем бесполезно. Можно фильтровать только по имени пользователя и можно задать только направление "к", "от", "любое направление". 

Я лично добавят фильтр по имени операции, что более нужнее. Для того же golos.io было много полезнее. На разных страницах у них только специфичные операции отображаются из истории. И ясно, что всегда показывает только историю по одному пользователю. Сейчас golosio считает 2000 (может сейчас больше) записей, а от туда отфильтровывает transfer или curation_reward или author_reward.

По этой причине для golos.io я не вижу применению имплементированному фильтру, да и для себя лично.

Да еще жестко задан новыми параметрами dir и account. Можно же было через объект сделать, как в get_discussion... Понадобится добавить новые параметры и фильтры, будете наращивать и добавлять проверок if param > 5? Это же ад для API и для клиентов.

Мне помимо фильтра по операциям, хотелось бы еще иметь и фильтр по дате операции. min < timestamp  < max.

Но надеюсь, хотя бы сделайте фильтр одним, но гибким параметром

**Comment by afalaleev** [comment]
Да. Так оно и есть.
Это надо отрефакторить и добавить фильтрацию по индексам, а не так как сейчас.

**Comment by RostislavVel** [comment]
"...Можно фильтровать только по имени пользователя... " этого функционала в текущей версии кода нет (смотрите внимательнее).

По остальным вопросам - напишите конекретные требования по реализации, внесу исправления.

**Comment by gropox** [comment]
Да, точно, 5-й параметр это операция. Извиняюсь, почему то подмал, что это пользователь. 

По реализации, требовать не буду ) Я предлагаю фильтр не отдельными параметрами задавать, а как в других методах, вроде get_discussions_by... tags плагина. Объектом с гибкой структурой. ТОгда не надо будет менять API, что бы добавить еще один параметр.

Ну и еще одна хотелка, это возможность задания фильтра по дате. Мотивация в том, что довольно часто требуется история от определенной  временной метки, до другой заданной.  Что то вроде "min_time": "2018-07-01T00:00:00.000", "max_time": "2018-07-02T00:00:00.000". Ну и брать операции у которых min_time <= timestamp  < max_time .

**Comment by gropox** [comment]
И еще 2 момент, может я опять ошибаюсь, но мне кажется в тек. реализации надо завадавть поерацию полным именем, включая namespace, , лучше мне кажется без namespace задавать. Тем более висит неиспользуемая константа STEEM_NAMESPACE_PREFIX.

И еще, не лучше ли было удаление истории сделать в operation_history плагине. В account_history плагине сильно чисткой account_history_index не сэкономишь, так как в индексе account_history_index только ссылка хранится на операцию. А сами операции так и остаются в базе.

**Comment by RostislavVel** [comment]
1 - Namespace - поправлю
2 - уже реализовано.

**Comment by zxcat** [comment]
PR #742

**Comment by zxcat** [comment]
PR #918
