### ISSUE TITLE
Invalid value returned in net_votes for deleted comments

### ISSUE THREAD

**Issue by VIM-Arcange** [GolosChain/golos#746]
When calling get_content() on a deleted post or comment, the `net_votes` field an invalid value (should be zeroed)

**Example**:

author:     likam
permlink:  re-litrbooh-re-sheller-re-litrbooh-alxternativnaya-yekonomika-dlya-viz-i-golos-20180619t041754296z

![image](https://user-images.githubusercontent.com/21260036/41581695-a320090e-739f-11e8-8d1a-1fe3f86724d4.png)

Other values like `depth`, `children`, `mode`, `percent_steem_dollars` should also be zeroed

**Comment by afalaleev** [comment]
PR #760
