### ISSUE TITLE
An option of eliminating the post/comment reblog / удаление репоста комментария и поста

### ISSUE THREAD

**Issue by marijadia** [GolosChain/golos#751]
Need an ability of removing reblog of post or comment
Related https://github.com/GolosChain/golos/issues/294

**Comment by maslenitsa93** [comment]
Repost is the reblog.
[Only top level posts can be reblogged.](https://github.com/GolosChain/golos/blob/golos-v0.18.4/plugins/follow/follow_evaluators.cpp#L114)
Therefore issue should be "ability of removing repost of post", not "...of post or comment"
Yes?

All post's reblogs should be deleted on deletion of this post. Not with separate API/operation.
And we need a config flag to enable/disable this behaviour.
Yes?
