### ISSUE TITLE
Поправить в голос вики инфу о 18 ХФ

### ISSUE THREAD

**Issue by t3ran13** [GolosChain/golos#755]
не указано что метод get_trending_categories выпилили

**Comment by t3ran13** [comment]
из инфы акков исчезли поля
new_average_market_bandwidth
new_average_bandwidth

появились такие поля
    [lifetime_bandwidth] => 4426096000000
    [lifetime_market_bandwidth] => 21628640000000
или они были до этого?

**Comment by anazarov79** [comment]
Документ New_HardFork-HF18.md был дополнен текстом с перечнем удаленных методов в social_network. Метод get_trending_categories значится в числе удаленных.

**Comment by anazarov79** [comment]
Дополнил подраздел database_api текстом с перечнем удаленных и переименованных полей применительно к параметру bandwidth.
