### ISSUE TITLE
Два варианта делегирования через параметр

### ISSUE THREAD

**Issue by t3ran13** [GolosChain/golos#756]
навеяно постом от @litrbooh

https://golos.io/ru--golos/@litrbooh/ru-na-golose-poyavilosx-delegirovanie
> Что меня пугает. Голос скопировал реализацию делегирования со Стима, исправив небольшую дырку в части заряда батареи, а это значит, что при делегировании хозян ничего за это не получает. Хотя, я предлагал начислять ему его долю кураотрских. Получается, что делегирующий либо 100% альтруист, или они будет свою СГ сдавать в аренду. На мой взгляд это равносильно продаже апов. На Стиме делегирование вылилось в фактически в аренду СГ для самоапов. На Голосе это сделать сложнее, но можно - если брать на группу.

мне кажется его идея способна оживить экономику и заинтересовать многих инвесторов в делегировании силы обсалютно любому

но и текущую реализацию стоит сохранить.

предлагаю добавить параметр для указания кому будут уходить кураторские награды, не вижу каких-то технических трудностей для реализации, вродь как мелкая фича

**Comment by litrbooh** [comment]
@t3ran13 
Ну, эта идея сама по себе не имеет смысла в рамках текущей кураторской кривой. Это идея с кураторскими при делегировании актуальна при:
1) Сглаживании куратороской кривой, как минимум до состояния стима и ещё больше
2) Как минимум нужно отфиксировать кураторские в размере 25%, чтобы не было штрафа в пользу автора, а вообще ты знаешь, что я предлагаю минимум 50/50 на сделать.
3) Я бы ещё выкинул награду за СГ

Но это уже не просто фича, а изменение экономики. Но оно нужно.

**Comment by afalaleev** [comment]
Да, это возможно сделать. 
И да я согласен, если это делать нужно пересмотреть кураторскую кривую.

**Comment by gropox** [comment]
Вероятно это было бы удобным, если при делегировании СГ можно было бы указать процент кураторских, которые будут отчисляться делегировавшему СГ. От 0 - 100%. Тогда не надо будет писать стороннее приложение для учета и продажи делегированной СГ.

С другой стороны, это ничего не принесет на мой взгляд, так как получатель СГ будет тупо голосовать в первую минуту за посты, зарабатывая только на авторских вознаграждениях. В кураторские больше никто не играет судя по всему на голосе.

**Comment by t3ran13** [comment]
Ну не скажи, у нас используется только 20-40 силы, остальное купили и забвли. А так мб перед забытием начнут делегировать комуто)

**Comment by afalaleev** [comment]
- [ ] Extend `chain_properties_19`
- The maximum interest rate for delegated vesting shares (default 25%)
- [ ] Add calculation of median to `database::update_median_witness_props()`
- [ ] Add new operation `delegate_vesting_shares_with_interest_operation`
- delegator
- delegatee
- vesting_shares
- interest rate
- extensions
- [ ] Add evaluator for `delegate_vesting_shares_with_interest_operation`
- [ ] Add accumulated value of interest into `vesting_delegation_object`
- [ ] Add returing of delegated shares with accumulated value of interest
- [ ] Add calculation of delegated interest rate into `database::pay_curators()`
- [ ] Extend `update_chain_properties` command with maximum delegation interest rate in cli_wallet
- [ ] Add support of `delegate_vesting_shares_with_interest_operation` into cli_wallet
- [ ] Extend `info` command with maximum delegation interest rate in cli_wallet
- [ ] Add unit-tests for delegation interest rate

**Comment by litrbooh** [comment]
@afalaleev @t3ran13 @marijadia 
Идея про делегирование с возвратом кураторских была высказана, но не описана подробно. подробнее тут:
https://golos.io/goldvoice/@litrbooh/kak-dolzhen-rabotatx-mekhanizm-delegirovaniya-s-vozvratom-kuratorskikh

Делегирование с возвратом кураторских должно предусматривать дополнительные механизмы:

    возможность отказа от делегированных СГ с возвратом кураторских
    Установление процента бенефициарских на кураторские.

**Comment by afalaleev** [comment]
@litrbooh спасибо за подробное описание своего видения!

Мы планировали:
- Добавить процент на кураторские делегирующему
1. Процент назначается делегирующим.
1. Верхняя планка процента устанавливается делегатами.
1. Возврат процента осуществляется в момент возврата делегированной СГ
- Насчет отказа. Пока не было процента на делегированную СГ, смысла в отказе не было. Теперь есть необходимость:
- Добавить функцию отказа
- Пользователь может захотеть запретить делегировать ему СГ

**Comment by gropox** [comment]
Я все равно не понимаю смысл отказа.  В чем может быть негативный эффект?

**Comment by t3ran13** [comment]
Я тоже не вижу смысла в отказе.
Предлагаю сделать без отказа, и если прльзователи попросят - ввести потом.

А то сча накодим бессмысленного, а потом будем жаловаться что в коде фарш

**Comment by gropox** [comment]
@litrbooh, да это вариант нагадить. Хотя и так можно, без делегирования, хотя и менее эффективно

Интересен ещё момент, если делегатор делегирует, паравозник голосует и делегатор забирает сг.

**Comment by gropox** [comment]
Если делать отказ от делегирования, то надо ещё подумать как.

- Либо флаг выставлять в аккаунте, но тогда никто не сможет делегировать. А стоит включить делегирования, как зловред сразу может делегировать отслеживая операцию включения.

- Либо операцию делать возврата делегирования сг, но зловред может постоянно делегировать

- либо делать белый и черные списки, что   конечно более заморочено

**Comment by t3ran13** [comment]
Блин, давайте сделает по простому,а? Кураторских можно лишить и так покупкой апов, как сейчас делается.

А то с такими фантазиями о блек и вайт листах из таскина 5 минут получим задачу как с ассетами на год и без конца.

Попользуйтесь сперва простым а потом будите дорабатывать

**Comment by gropox** [comment]
Да, непонятно почему так сделали. Непонятно, как к такому решению пришли. И еще один пункт - набежавшие проценты не учавствуют в экономике, пока не отзовешь СГ.  То-есть делегаторы будут вынуждены чаще отзывать СГ, что бы получить заработанное непосильным трудом делегата. А тут еще и СГ блокируется на неделю.

**Comment by gropox** [comment]
А, нет, сорри, судя по этому коду процент сразу начисляется делатору на вестинговый счет

![image](https://user-images.githubusercontent.com/26039472/46300202-62a32400-c5a3-11e8-9b00-2b89cada3e85.png)

**Comment by t3ran13** [comment]
Я хз, в анонсе написано в момент отзыва

**Comment by afalaleev** [comment]
Набежавшие проценты участвуют в экономике.
Вот вы делегировали какую СГ "эффективному" куратору - он вам зарабатывает именно курированием, почему часть того, что он накурировал должна у него сразу изыматься?
Он же при следующем курировании заработает еще больше, так как проценты будут начисленны на всю сумму (делегированное + уже начисленные проценты).

**Comment by gropox** [comment]
Но делегатору от этого ни горячо ни холодно. Делегатор не спонсор, а вкладчик, ожидающий, что будет зарабатывать и рассчитывающий на  сложный процент.

**Comment by t3ran13** [comment]
Согласен с горохом.
Так же класический куратор получает выплату сразу за курирование, мы ведь не оставляем кураторские автору за посты на время Х, т.к. это сделает с ду апа автора с поста на 25% сильнее.
- глупая логика
- логика усложняющая код, и не представляющая интересы инвестора
- РЕАЛИЗОВАНА ЛОГИКА с потолка БЕЗ СОГЛАСОВАНИЯ С КОМЬЮНИТИ... Узнаю коре. Из простой хорошей нужно фичи сделать нечто гениальное, что никому не нужно)))

**Comment by afalaleev** [comment]
Автор зарабатывает написанием постов, размер его СГ никак не влияет на прибыль получаемую им за написание. Поэтому нет никакого смысла оставлять ему СГ, и это глупое сравнение.

- Логика не глупая, в сообществе есть те, кто предлагал именно такую реализацию. Когда куратор наращивая стек, увеличивает доход быстрее, чем он будет уходить в мертво-лежащий баланс у пассивных держателей СГ.
- Логика абсолютно код не усложняет. В системе уже есть учет кто, кому и сколько делегировал. И оно без разницы - складывать чиселки туда, или начислять напрямую делегатору.
- Без комментариев.

**Comment by jackvote** [comment]
Вместо установки процента отчисления кураторских от 0 до 100, предлагаю при делегировании указывать:
1. возврат процента сразу, при получении кураторских
2. оставлять процент делегату, с возвращением при отзыве, вместе со всей суммой через неделю.

Отслеживать вывод раз в неделю/месяц - много кода. Не понятно с какого момента начинать отсчёт, что именно выводить. Если выводимое перед выводом было  "замарано" апвотом, то вывод должен задерживаться на неделю. Это ещё лишний код. Я против этого.

При выводе по первому варианту - процент ещё не "замаран" и чистый моментально зачисляется инвестору.
По второму варианту - ждать неделю, но проценты будут работать на инвестора. Будут набегать проценты на проценты.

Таким образом у инвестора есть выбор. Или получать постоянный ручеёк и реинвестировать в других, или вложиться и отдыхать. Забрав всё спустя несколько месяцев с процентами.

**Comment by t3ran13** [comment]
@afalalee
Дай ссылку, хочу посмотреть кто просил такой вариант. И почему этот вариант не обсуждался нигде, и даже в ишью о нем ни слова не прошло?
- размер сг автора еще как влияет на прибыль - можно апать себя, можно продавать, чем больше у тебя сг тем больше у тебя фоловверов, а значит и читателец и апов)
- вы тогда в анонсе озвучили неправильно, выплата процентов идет сходу на счет делегированной суммы. Но в таких условиях при учтановке 100% получения профита делегировавшему, куратор не получит от этого никакой прибыли. Т.е. вы не правы. Я вообще сомневаюсь что найдется много альтруистов которые захотят кормить кураторов, и это станет мейнстримом. Мб кто-то из коре планирует делегировать безмоздмиздно другим?)
- я все время слышу о том что команда высокого уровня и работала ого-го где. Как команда высокого уровня сделала не то что просило сообщество да еще и забыла поинтересоваться мнением "заказчика"???

**Comment by gropox** [comment]
@afalaleev а выше, мной приведенный кусок кода, из последнего коммита, разве не начисление сразу на вестинговый счет делегатора? Может уже все сделано как и ожидается и спор этот бесполезен?

**Comment by t3ran13** [comment]
Горох, начисление идет на счет делегированной силы. Сразу.
Просто в анонсе написали неправильно.

Но при таком подходе все равно кураторы наврядли будет профит, а инвестору лучше отдавать прибыль сходу.

**Comment by afalaleev** [comment]
Да, спор бесполезен - ишью не доделана.  Мой косяк - что я не отревьюл целиком отчет о проделанной работе.

Есть разветвления логики, в которых нет единного мнения. @jackvote  примерно описал логику покрывающие кейсы для разных участников коммьюнити - от активных до пассивных держателей СГ.

- Вариант когда процент остается у того, кому делегировали. Он не сделан.
- Варинат когда перечисляется делегатору тоже не доделан - там математика прямо хромает.

Вся разница - в небольшом if-е куда начислять, и наличии виртуальной функции в случае начисления на счет делегированной СГ.

**Comment by litrbooh** [comment]
@jackvote 
> Вместо установки процента отчисления кураторских от 0 до 100, предлагаю при делегировании указывать:     возврат процента сразу, при получении кураторских

Да, наверно, так будет проще в коде и по сути. Делегирующий предлагает СГ и процент, не нравится - отказывайся.

> оставлять процент делегату, с возвращением при отзыве, вместе со всей суммой через неделю.
Вот тут не согласен. Если брать аналогию с банком, то возврат все суммы не должен коррелировать с возможностью забрать проценты.

@afalaleev @marijadia 
Прошу заметить, что сразу после голосования по фичам я предложил собрать дискорд и провести обсужение реализации фич. Но @marijadia сказала, что вопросы только у меня, а остальным всем понятно. 

Далее я просил сделать описание функционала по каждой фиче, чтобы понять что и как будет реализовано - этого тоже не сделано. 

Фактически мы возвращаемся в состояние год назад, когда ядро что-то кодит, а делегатов это потом не устраивает, т.е. мы теряем время. Моё мнение, что каждая фича сначала должна быть описана, потом голосование и потом реализация, вы делаете всё наоборот. Сначала голосуете, потом делаете, а потом начинаете выяснять "а что же вы хотели на самом деле".

**Что касается фичи и вопроса возврата:**
Вы когда в банк приходите, у вас есть выбор - проценты в конце, ежемесячная капитализация, или вы можете забирать проценты яжемесяцно. Вы почему-то хотите ограничить делегирубщего в одном варианте - проценты в конце? С чего вдруг, почему вы за него решаете как ему распоряжаться деньгами? С точки зрения пользователя, в идеале иметь кнопку-команду, которой я могу забирать свои проценты в тот момент когда захочу, или давайте мне их сразу.

**Comment by jackvote** [comment]
> Делегирующий предлагает СГ и процент, не нравится - отказывайся.
А зачем отказываться? В минусе всё равно не будешь.

Кстати, переношу из чата сюда:

> Вообще-то недельную отсрочку можно было бы считать не с момента отзыва, а с момента последнего апвота. last_vote_time

Согласен. Какой смысл ждать неделю, если куратор перестал апвотить шесть дней назад, и инвестор решил отозвать своё из-за его бездействия.

**Comment by afalaleev** [comment]
Никто никого не ограничивает одним вариантом - выплаты в конце, тем более что это миф про возможность изъять все только целиком, можно изымать частями.

Есть два варианта:
- Повышенный процент за счет начисления процентов на проценты. 
- Начисление процентов сразу делегатору.

Смысл отказа в том, что есть схема паразитирования - делегировать активному куратору и получать с него пассивную прибыль, при этом у куратора нет никакой возможности сбросить паразита. 
Есть те, кто хочет выбирать контент, а не зарабатывать на нем, для них - "В минусе не останешься" - аргументом не является.

**Comment by jackvote** [comment]
> Есть те, кто хочет выбирать контент, а не зарабатывать на нем, для них - "В минусе не останешься" - аргументом не является.

Те кто хочет выбирать контент и поощрять аторов должен быть благодарен возможности увеличению возможности поощрения этих авторов. Всё равно он не собирается на этом зарабатывать, так зачем отказываться? Тем более есть возможность самоапа с большей силой, что компенсирует все недополученные кураторские в тройном размере.

Опять же  выше было сказано:

> Процент назначается делегирующим.
> Верхняя планка процента устанавливается делегатами.

Можно упростить этот момент и сделать голосуемым параметром максимальный процент оставляемый куратору. И никаких назначений делегирующим.

Т.е. делегаты голосуют за 15%. С поста на делегированную СГ приходится какая-то сумма.
15% с неё зачисляется в кураторские куратору, 85% переводится инвестору по моему первому варианту или добавляются к делегированной СГ по второму варианту.

Если делегаты проголосуют за 0%, то инвесторы станут паразитами. Но: а что "но" я написал выше. В минусе куратор не остаётся. В любом случае в выигрыше, даже за счёт авторских.

**Comment by t3ran13** [comment]
> Смысл отказа в том, что есть схема паразитирования - делегировать активному куратору и получать с него пассивную прибыль, при этом у куратора нет никакой возможности сбросить паразита.
Есть те, кто хочет выбирать контент, а не зарабатывать на нем, для них - "В минусе не останешься" - аргументом не является.

слушайте, опять наичнается бред!
Вы в простом варианте эту ишью не сделали, как верно заметил @litrbooh , если вы сейчас начнете защиту от паразитов придумывать и делать не спрашивая, боюсь мы фичу даже зимой не увидим.

**Давайте исходить из того, что сперва сделаем фичу, посмотрим как она будет работать, если работать будет плохо и люди будут просить защиту, то будем делать "защиту". **Пока у нас защиты требуют вымышленные персонажи которые нерабы увеличению СГ.
И опять же, если жаловаться будет 1 человек на то что ему делегируют, то уж простите, разрабатывать защиту из-за 1 тоже не камельфо. У нас еще список фичь такой что коре будет чем и без этого заняться)

**Comment by zxcat** [comment]
на счёт отказа от делегированной СГ — люди просили ещё 4 месяца назад. где-то в постах перед ХФ•18

**Comment by gropox** [comment]
Просил один человек и при этом он не мог внятно объяснить почему, он объяснял, что гуманитарий и объяснить не может.

Не на говорить "люди просили" (argumentum ad populum не пройдет) ))

**Comment by zxcat** [comment]
При чём здесь "argumentum ad populum", былы конкретные возражения.
Да, я не понял, почему он был против, когда не было процента. Когда есть процент, все те возражения обретают некий смысл.

**Comment by t3ran13** [comment]
@zxcat
Я тут активничаю тоже не мало, и кроме литрбухи никто пока не хочет отказываться от делегированной сг.
Если есть другие, дай линки плиз.
Если коре желает, то может посвятить отдельный пост опросу на эту тему. 
Но  это логично делать после ввода основной системы, чб было видно после использования)

**Comment by anela1** [comment]
Поддержу   - логично  сделать выплату кураторских делегатору автоматом, как всем кураторам в момент выплаты всем, а не отдельным окном.

**Comment by jackvote** [comment]
> 
> 
> Поддержу - логично сделать выплату кураторских делегатору автоматом, как всем кураторам в момент выплаты всем, а не отдельным окном.

Только с возможностью выбора делегатором, автоматом ему сразу или с наращенеим процентов у куратора и выплаты всей суммы после отзыва.
