### ISSUE TITLE
Посты старше 7-ми дней не репостятся

### ISSUE THREAD

**Issue by litrbooh** [GolosChain/golos#763]
Раз уж у нас теперь посты редактруются и удалятся даже если они старше 7ми дней, то логично было бы, чтобы они ещё и репостились, если они старше 7-ми дней. Сейчас после 7ми дней отрепостить нельзя. 

Можно объединить задачу с возможность удалять репост.

**Comment by afalaleev** [comment]
This limitation exists only in clients. The blockchain doesn't have any limits to repost posts after cashout period.

**Comment by afalaleev** [comment]
В блокчейне нет ограничений - это ограничение в клиенте.
