### ISSUE TITLE
Node gets segfault when block_log and shared_memory are missing

### ISSUE THREAD

**Issue by AKorpusenko** [GolosChain/golos#772]
## Steps to reproduce ##
- build current 18.1 testnet
- run `golosd` with debug `config.ini` and block_log and shared_memory missing

## Actual result ##
```
/golos/thirdparty/fc/include/fc/optional.hpp:215: const T* fc::optional<T>::operator->() const [with T = golos::protocol::signed_block]: Assertion `_valid' failed.
```
## Excepted result ##
Node have to work fine

**Comment by afalaleev** [comment]
PR #773
