### ISSUE TITLE
Base exceptions and macros for enumerous error codes

### ISSUE THREAD

**Issue by afalaleev** [GolosChain/golos#786]
- [x] Exceptions
- [x] Macros

**Comment by s-medvedev** [comment]
Для тестирования сейчас реализована обработка ошибок в соответствии с новой схемой в следующих операциях:
- Добавление поста/комментария. Реализована обработка следующих ошибок:
  - неверные параметры (внутри steem_operations.cpp:comment_operation::validate()). В данном случае пользователю выдается ошибка `invalid_parameter`
  - ошибки, возникающие на этапе выполнения операции (то есть фактически . В данном случае пользователю выдается ошибка `tx_invalid_operation`, внутри которой находится описание нижележащего исключения:
    - проверка параметров (исключение `invalid_parameter`):
      - валидность `permlink` (данная проверка строже, чем на этапе валидации операции)
      - валидность `body` (пустое тело сообщения)
    - проверка бизнес-логики на этапе применения операции (исключение `logic_error`)
    - проверка bandwidth (исключение `exceeded_bandwidth`)
- Перевод средств. Реализована обработка следующих ошибок:
  - перевод на несуществующий аккаунт (исключение `missing_object`)
  - недостаточные полномочия (исключение `tx_missing_active_auth`)
  - сумма перевода превышает существующие средства (исключение `insufficient_funds`)
- Сбережение средств (операция `transfer_to_savings`)
  - перевод на несуществующий аккаунт (исключение `missing_object`)
  - недостаточные полномочия (исключение `tx_missing_active_auth`)
  - сумма перевода превышает существующие средства (исключение `insufficient_funds`)
- Перевод сбережений на основной счет (операция `transfer_from_savings`)
  - перевод на несуществующий аккаунт (исключение `missing_object`)
  - недостаточные полномочия (исключение `tx_missing_active_auth`)
  - сумма перевода превышает существующие средства (исключение `insufficient_funds`)
  - достигнуто ограничение количества запросов на вывод средств (исключение `logic_exception`)
- Операция из плагина: market_history::get_open_orders & get_order_book

**Comment by s-medvedev** [comment]
В соответствии с предложенной схемой, обработка ошибок на стороне клиента будет выглядить следующим образом.

При появлении ошибки во время выполнения операции, сервер выдает информацию об
ошибке в соответствии со спецификацией JSON-RPC 2.0 (https://www.jsonrpc.org/specification#error_object)

- **jsonrpc** - Строка, содержащая версию JSON-RPC протокола. Содержит значение "2.0".
- **id** - идентификатор запроса (берется из соответствующего поля запроса)
- **error** - структура, содержащая информацию об ошибке
	- **code** - число, идентифицирующее тип возникшей ошибки
	- **message** - строка, содержащая короткое описание ошибки
	- **data** - объект, описывающий ошибку 


Значения для поля **error.code**:
```
-32700	Parse error			Invalid JSON was received by the server. An error occurred on the server while parsing the JSON text.
-32600	Invalid Request		The JSON sent is not a valid Request object.
-32601	Method not found	The method does not exist / is not available.
-32602	Invalid params		Invalid method parameter(s).
-32603	Internal error		Internal JSON-RPC error.

-32000 to -32099 зарезервированы для ошибок сервера и имеют следующие значения:
-32000 	JSON_RPC_SERVER_ERROR
-32001 	JSON_RPC_NO_PARAMS
-32002 	JSON_RPC_PARSE_PARAMS_ERROR
-32003 	JSON_RPC_ERROR_DURING_CALL
-32004 	JSON_RPC_INSUFFICIENT_FUNDS
-32005 	JSON_RPC_MISSING_AUTHORITY
-32006 	JSON_RPC_MISSING_OBJECT
-32007 	JSON_RPC_LOGIC_ERROR
```

Объект, описывающий ошибку (поле **error.data**)

Ошибка, описывается в JSON-представлении в виде структуры с определенным набором 
полей. Поля, предназначенные для анализа ошибочной ситуации на стороне клиента,
представлены ниже. В данной структуре также присутствует ряд полей, содержащих 
информацию для технических специалистов, но структура, назначение и содержимое
этих полей не регламентируется и может быть изменено в дальнейшем.

Структура сообщения об ошибке:
```
{
	"code": 3000001,
	"message":"invalid operation in transaction",
    "name": "tx_invalid_operation",
    "stack": [
        {
			"context": { ... },
            "data": { ... },
            "format": "Invalid operation ${index} in transaction: ${errmsg}"
        }
    ]
},
```

- **code** - числовой код ошибки (берется из поля code при описании исключения)
- **message** - строка с описанием типа ошибки (берется из поля message при описании исключения)
- **name** - имя ошибки (имя класса исключения)
- **stack** - структура, описывающая дополнительную информацию об ошибке. Для клиента представляет интерес первый элемент данного массива. Для технических специалистов остальные элементы дают информацию о стеке вызовов, приведших к ошибке.
- **context** - описание контекста возникновения ошибки (строка, файл...)
- **data** - дополнительные информация об ошибке, структурированния в виде словаря
- **format** - строка форматирования сообщения об ошибке

_Поля **code**, **message** и **context** содержат информацию для разработчиков. Здесь приведены для полноты картины и в описании для клиентов будут отсутствовать._

Таким образом, для анализа ошибочной ситуации на стороне клиента мы предоставляем поля **name**, **format** и данные из словаря **data**.

В определенных ситуациях возможно вложение одной ошибки в другую. В таких случаях
пользователю необходимо для анализа ошибочной ситуации также разбирать вложенные
ошибки. Такое возможно при выполнении транзакции. К примеру, клиент получил ошибку 
невалидной операции в транзакции. При разборе это будет выглядит так:
```
	невалидная операция в транзакции, потому что:
		передан неверный параметр, потому что:
			символ % недопустим для permlink
```
При этом клиент может получить номер операции, имя параметра и причину, по которой
он считается неверным из дополнительной информации.

---
## Возможные ошибки (с описанией дополнительной информации):
Данный список ошибок мы будет специфицировать для клиентов. Для каждой ошибки
дается ее имя (соответствует имени классу исключения), список дополнительной
информации, размещаемой в поле data, а также возможные значения для перечислений.

### Ошибки, связанные с передачей параметров:

- **missing_object** - отсутствует запрошенный объект
	- **type** - тип отсутствующего объекта (account, block, transaction, ...)
	- **id** - идентификатор отсутствующего объекта

- **invalid_parameter** - неверное значение для параметра
    - **param** - наименование параметра
    - **value** - значение параметра (может отсутствовать, если есть сложности с его получением)
    - **errmsg** - сообщение об ошибке (берется из поля error.message)
    - **error** - ошибка, возникшая при проверке параметра

- **invalid_value** - неверное значение (внутреннее исключение для формирования логики
	обработки ошибок). Дополнительная информация не специфицируется, для клиента
	доступно только описание ошибки.

- **limit_too_large** - значение лимита слишком большое
	- **limit** - текущее значение
	- **max** - максимально допустимое значение


### Ошибки бизнес-логики:
Такие ошибки возникают, если клиент пытается выполнить операцию с валидными параметрами, но выполнение которой сейчас недопустимо по каким-то причинам.

- **logic_exception** - логическая ошибка
	- **err_id** - идентификатор ошибки (из каталога таких ситуаций)
		- reached_limit_for_pending_withdraw_requests
		- parent_of_comment_cannot_change
		- parent_perlink_of_comment_cannot_change

- **insufficient_funds** - недостаточно средств на счете
	- **account** - аккаунт
	- **balance** - счет (основные средства, сбережения, акции...)
	- **required** - требуемое количество

- **bandwidth_exception** - превышение пропускной способности
	- **bandwidth** - идентификатор превышенной пропускной способности
		- post_bandwidth - размещение постов
		- comment_bandwidth - комментирование
		- ...
	- **last** - время выполнения операции последний раз
	- **next** - следующее допустимое время выполнения операции

### Ошибки выполнения транзакции:
- **tx_invalid_operation** - невалидная операция в транзакции
	- **index** - индекс невалидной операции
	- **errmsg** - сообщение об ошибке, которое случилось при выполнении операции
	- **error** - ошибка, возникшая при выполнении операции

- **tx_missing_active_auth**, **tx_missing_owner_auth**, **tx_missing_postings_auth** - недостаточные привилегии пользователей
	- **id** - массив с идентификаторами пользователей

**Comment by s-medvedev** [comment]
И напоследок пример, как будет выглядить ответ. Данный ответ был получен на команду размещения поста из cli_wallet:
`post_comment alice "qwer%asdf" "" "test" "Title" "Body" "{}" true`

```
{
  "id": 55,
  "jsonrpc": "2.0"
  "error": {
    "code": -32603,
    "message": "invalid operation in transaction (3000001)\nInvalid operation 0 in transaction: Invalid parameter value (300004)\nInvalid value \"asdfasd%123\" for operation parameter \"permlink\": invalid value exception (300006)\nInvalid permlink character: %\n\n\n"
    "data": {
      "code": 3000001,
      "message": "invalid operation in transaction",
      "name": "tx_invalid_operation",
      "stack": [
        {
          "context": {
            "file": "database.cpp",
            "hostname": "",
            "level": "error",
            "line": 3632,
            "method": "_apply_transaction",
            "thread_name": "th_0",
            "timestamp": "2018-07-05T14:19:00"
          },
          "data": {
            "errmsg": "Invalid parameter value (300004)\nInvalid value \"asdfasd%123\" for operation parameter \"permlink\": invalid value exception (300006)\nInvalid permlink character: %\n\n",
            "error": {
              "code": 300004,
              "message": "Invalid parameter value",
              "name": "invalid_parameter",
              "stack": [
                {
                  "context": {
                    "file": "steem_evaluator.cpp",
                    "hostname": "",
                    "level": "error",
                    "line": 674,
                    "method": "operator()",
                    "thread_name": "th_0",
                    "timestamp": "2018-07-05T14:19:00"
                  },
                  "data": {
                    "errmsg": "invalid value exception (300006)\nInvalid permlink character: %\n",
                    "error": {
                      "code": 300006,
                      "message": "invalid value exception",
                      "name": "invalid_value",
                      "stack": [
                        {
                          "context": {
                            "file": "steem_evaluator.cpp",
                            "hostname": "",
                            "level": "error",
                            "line": 153,
                            "method": "validate_permlink_0_1",
                            "thread_name": "th_0",
                            "timestamp": "2018-07-05T14:19:00"
                          },
                          "data": {
                            "s": "%"
                          },
                          "format": "Invalid permlink character: ${s}"
                        }
                      ]
                    },
                    "param": "permlink",
                    "value": "asdfasd%123"
                  },
                  "format": "Invalid value \"${value}\" for operation parameter \"${param}\": ${errmsg}"
                }
              ]
            },
            "index": 0
          },
          "format": "Invalid operation ${index} in transaction: ${errmsg}"
        }
      ]
    },
  },
}
```

**Comment by s-medvedev** [comment]
PR #832
