### ISSUE TITLE
Refactor operation errors

### ISSUE THREAD

**Issue by afalaleev** [GolosChain/golos#790]
- [x] vote_operation
- [x] comment_operation
- [x] transfer_operation
- [x] transfer_to_vesting_operation
- [x] withdraw_vesting_operation
- [x] limit_order_create_operation
- [x] limit_order_cancel_operation
- [x] feed_publish_operation
- [x] convert_operation
- [x] account_create_operation
- [x] account_update_operation
- [x] witness_update_operation
- [x] account_witness_vote_operation
- [x] account_witness_proxy_operation
- [x] pow_operation
- [x] custom_operation
- [x] report_over_production_operation
- [x] delete_comment_operation
- [x] custom_json_operation
- [x] comment_options_operation
- [x] set_withdraw_vesting_route_operation
- [x] limit_order_create2_operation
- [x] challenge_authority_operation
- [x] prove_authority_operation
- [x] request_account_recovery_operation
- [x] recover_account_operation
- [x] change_recovery_account_operation
- [x] escrow_transfer_operation
- [x] escrow_dispute_operation
- [x] escrow_release_operation
- [x] pow2_operation
- [x] escrow_approve_operation
- [x] transfer_to_savings_operation
- [x] transfer_from_savings_operation
- [x] cancel_transfer_from_savings_operation
- [x] custom_binary_operation
- [x] decline_voting_rights_operation
- [x] reset_account_operation
- [x] set_reset_account_operation
- [x] delegate_vesting_shares_operation
- [x] account_create_with_delegation_operation
- [x] account_metadata_operation
- [x] proposal_create_operation
- [x] proposal_update_operation
- [x] proposal_delete_operation
- [x] chain_properties_update_operation

**Comment by afalaleev** [comment]
PR #845

**Comment by afalaleev** [comment]
PR #846

**Comment by afalaleev** [comment]
PR #847

**Comment by afalaleev** [comment]
PR #848

**Comment by zxcat** [comment]
PR #851, #852, #853, #854, #855

**Comment by s-medvedev** [comment]
PR #857

**Comment by zxcat** [comment]
PR #871, #874

**Comment by zxcat** [comment]
PR #876, #878, #880

**Comment by s-medvedev** [comment]
PR #881
