### ISSUE TITLE
Refactor erros in plugins

### ISSUE THREAD

**Issue by afalaleev** [GolosChain/golos#791]
- [x] account_by_key
- [x] account_history
- [x] block_info
- [x] chain
- [x] database_api
- [x] follow
- [x] market_history
- [x] network_broadcast_api
- [x] operation_history
- [ ] private_message
- [x] raw_block
- [x] social_network
- [x] tags
- [x] witness
- [x] witness_api

**Comment by s-medvedev** [comment]
PR #882

**Comment by s-medvedev** [comment]
PR #887
