### ISSUE TITLE
Configuration flag for storing account metadata

### ISSUE THREAD

**Issue by afalaleev** [GolosChain/golos#794]
Add the flag to configuration file to store the account metadata.
The flag should be defined in the chain-plugin.
Evaluators should get the configuration from the database.

As a result should be removing of IS_LOW_MEM around account_metadata.

**Comment by maslenitsa93** [comment]
Default is true?

**Comment by afalaleev** [comment]
I think that it will be good to add configuration list of account to store metadata. What do you think?

**Comment by maslenitsa93** [comment]
@afalaleev  It is a list of account names to store metadata, or to don't? And this is instead bool flag or together?

**Comment by afalaleev** [comment]
Yes, it is a list of account names to store metadata, instead of bool flag. What do you think?

**Comment by maslenitsa93** [comment]
@afalaleev I agree.

**Comment by maslenitsa93** [comment]
https://github.com/GolosChain/golos/pull/812
