### ISSUE TITLE
Add flag for storing memo in transfer from saving

### ISSUE THREAD

**Issue by afalaleev** [GolosChain/golos#797]
Add flag to configuration file to store memo from transfer.
Flag should be defined in chain-plugin.
Evaluators should get configuration from the database.

As a result should be removing of IS_LOW_MEM around transfer.

**Comment by maslenitsa93** [comment]
I think if flag disabled, following should be:
- All creations of savings_withdraw_object should write empty "" memo
- Mongo plugin should not create this field (same as now if IS_LOW_MEM defined)
Is it right?

**Comment by afalaleev** [comment]
If flag is disabled:
- All creations of savings_withdraw_object should **clear** memo 
- There are no creations in init_genesis
- Mongo plugin should not create this field

By default, memo should be saved.

**Comment by maslenitsa93** [comment]
PR https://github.com/GolosChain/golos/pull/822
