### ISSUE TITLE
Refactor clear_votes() to history depth

### ISSUE THREAD

**Issue by afalaleev** [GolosChain/golos#801]
Now, the `clear-votes`-option contains the block number from which votes should be cleared.
Need to add an additional option to store votes to history depth.

Conditions:
- if the option contains the value less then cashout window, votes should be cleared after cashout.
- if the option contains the value bigger then cashout window, votes should be cleared in the function called from the `database::_apply_block()`
- if the option contains the value 4294967296 votes shouldn't be cleared

Option should be defined in the chain-plugin.

Evaluator should get configuration from the database.

**Comment by zxcat** [comment]
PR #897
