### ISSUE TITLE
Implement functionality to edit/delete private messages

### ISSUE THREAD

**Issue by afalaleev** [GolosChain/golos#807]

**Comment by afalaleev** [comment]
PR #899

**Comment by BaroH4er** [comment]
**Testing is done.** result:

`send_private_message` - **OK**
`edit_private_message` - **OK**
`delete_inbox_private_message` - **OK**
`delete_inbox_private_messages` - **OK**
`mark_private_message` - **OK**
`mark_private_messages` - **OK**

`delete_outbox_private_message` - **Fail**
`delete_outbox_private_messages` - **Fail**
![image](https://user-images.githubusercontent.com/21989598/43959389-4f147408-9cb7-11e8-8137-b30214d2f8e8.png)

**Comment by afalaleev** [comment]
PR #929
