### ISSUE TITLE
Убрать задвоение параметров.

### ISSUE THREAD

**Issue by asuleymanov** [GolosChain/golos#808]
Сейчас есть две операции:
witness_update 
chain_properties_update

У них происходит задвоение устанавливаемых параметров, а именно:
account_creation_fee, maximum_block_size, sbd_interest_rate

Предлагаю убрать их из операции witness_update.

Они только путают. И по ошибке могут перебивать друг друга.

**Comment by zxcat** [comment]
Именно так сейчас и работает. Начиная с ХФ•18 `witness_update` больше не меняет голосуемые параметры. Можно поменять только ключ делегата и url.
В [release notes к v0.18.0RC2](https://github.com/GolosChain/golos/releases/tag/v0.18.0RC2) описывали, см. раздел "Limited using the method witness_update_operation"

**Comment by asuleymanov** [comment]
Т.е. правильно ли я понимаю. Теперь нет необходимости отправлять с помощью операции witness_update эти параметры? 
Т.е. я могу в библиотеке убрать это из операции и все будет работать нормально?

**Comment by zxcat** [comment]
@asuleymanov, всё верно, witness_update теперь их не обрабатывает. но из-за особенностей сериализации операций, их всё равно нужно передать на демон. Чтобы в нода не реагировала на это предупреждениями, можно указать значения по умолчанию:
```
"props": {
    "account_creation_fee": "0.001 GOLOS",
    "maximum_block_size": 131072,
    "sbd_interest_rate": 1000
}
````

Ключ деактивации ноды: `GLS1111111111111111111111111111111114T1Anm`

**Comment by asuleymanov** [comment]
По поводу witness_update ясно. А планируется это убрать?

Как в таком случае сериализуется ключ дезактивации как строка или как public_key?
