### ISSUE TITLE
fix method get_transaction_hex

### ISSUE THREAD

**Issue by t3ran13** [GolosChain/golos#823]
it serialize with signature, it have not

> Alex Korzun, [06.07.18 21:51] 
Проверить правильность сериализации транзакции можно отправив ее на database_api.get_transaction_hex однако стоит знать, что сейчас get_transaction_hex работает с ошибкой -> сериализует так же и поле signatures которое сериализовать не надо + к возвращенному байт массиву надо прибавить chain_id байтмассив..

**Comment by afalaleev** [comment]
- `database_api::get_transaction_hex(trx)` returns binary serialized transaction without signature
- `database_api::get_transaction_digest(trx)` returns sha256 digest for chain_id+transaction

The value of `chain_id` is already exist in result of `database_api::get_config`:
```
➜  cli_wallet git:(golos-v0.19.1) ✗ curl --data '{"method":"call","params":["database_api","get_config",[]],"jsonrpc":"2.0","id":0}' http://localhost:8090/rpc   | python -mjson.tool | grep CHAIN_ID
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  4231  100  4149  100    82   289k   5857 --:--:-- --:--:-- --:--:--  295k
        "STEEMIT_CHAIN_ID": "5876894a41e6361bde2e73278f07340f2eb8b41c2facd29099de9deef6cdb679",
```
