### ISSUE TITLE
Fix 'get_accounts' response 

### ISSUE THREAD

**Issue by NickShtefan** [GolosChain/golos#825]
При запросе get_accounts мы получаем информацию о количестве постов и комментариев в одном поле - post_count, при этом поле comment_count всегда приходит пустым. 

![image 6](https://user-images.githubusercontent.com/6249597/42442965-d47f606e-8374-11e8-80a4-6e3788807125.png)

**Comment by jackvote** [comment]
> В версии HF-19.0 этот недостаток устранен. Был доработан метод get_accounts для корректной записи данных в соответствующие поля при создании поста и комментария. Поле comment_count содержит количество комментариев, а поле post_count — только количество постов.

Недостаток устранён не полностью.
Хотелось бы ещё и количество репостов. Так как они также содержаться в блоге аккаунта, но их количество приодится вычислять через get_blog

**Comment by afalaleev** [comment]
Reblogs aren't core objects, it is an other functionality implemented in follow plugin. 
We already have issue #955 for it.

**Comment by jackvote** [comment]
Почему бы не сделать их основным объектом заодно? Если это стабильная и востребованная функция? И в клиентах отображается именно в блоге, среди постов. Т.е. рассматривается, практически, как копия чужого поста в своём блоге. С автоматической ссылкой на первоисточник.

И для кого даётся ответ на немогучем? Когда ишью и комментарий созданы на родимом. :-)

**Comment by afalaleev** [comment]
Потому что они не влияют на экономику. 
Это социальный компонент чейна, а не экономический, как и сам блог, поэтому и подход к его обработке другой.

Поэтому данная задача закрыта. 
По реблогам открыта другая задача #955
