### ISSUE TITLE
account_create_with_delegation

### ISSUE THREAD

**Issue by asuleymanov** [GolosChain/golos#827]
Возникает ошибка
```
Создание пользователя as-test4 с помощью операции "account_create_with_delegation"
Ошибка операции : call failed: jsonrpc2: code -32003 message: Assert Exception (10)
is_asset_type(delegation, VESTS_SYMBOL): Delegation must be GESTS
```
Хотя в операции используется GESTS
`cls.AccountCreateDelegation(user1, user3, userPassword[user3], client.SetAsset(50000, "GESTS"), client.SetAsset(5.0, "GOLOS"))`

**Comment by zxcat** [comment]
а какое значение возвращает `client.SetAsset(50000, "GESTS")`? для GESTS надо 6 знаков после запятой

**Comment by asuleymanov** [comment]
Пробовал и такую команду 
`cls.AccountCreateDelegation(user1, user3, userPassword[user3], client.SetAsset(50000.000000, "GESTS"), client.SetAsset(5.0, "GOLOS"))`
А вообще там составляющая из float и string

**Comment by afalaleev** [comment]
Можно увидеть транзакцию в том виде, в котором она в чейн уходит?
По библиотечным вызовам сложно понять, где проблема.

**Comment by asuleymanov** [comment]
Вот такие данные в логе
```
2018/07/10 11:57:36 Создание пользователя as2 с помощью операции "account_create_with_delegation"
2018/07/10 11:57:36 &{5.000 GOLOS 500.000 GESTS as1 as2 0xc042184360 0xc042184380 0xc0421843a0 GLS5W2a5isp8Uc4wN2XvSRrN9EtVHyzHWgJLkcDKu4ukNvZshgzNm &types.AccountMetadata{Profile:types.ProfileJSON{Name:"", ProfileImage:"", CoverImage:"", Gender:"", About:"", Location:"", Website:""}} []}
```

**Comment by asuleymanov** [comment]
При этом процедура 
`cls.AccountCreate(user1, user2, userPassword[user2], client.SetAsset(5.0, "GOLOS"))`
отрабатывает нормально.
Т.е. проблемма как раз в проверке GESTS.

**Comment by zxcat** [comment]
> `500.000 GESTS`

надо заменить на `500.000000 GESTS`. Видимо `client.SetAsset()` не знает, что для GESTS нужно 6 знаком, и делает 3 знака для всех ассетов

**Comment by asuleymanov** [comment]
т.е. хотите сказать то это так жестко прошито?
Если это так, то это неправильно. Я могу вообще без нулей указать. Такого не должно быть.
**Сегодня конечно же проверю чтобы при GESTS выдавало 6 нулей. Но все равно это не правильно.**

**Comment by zxcat** [comment]
Это наследие стимита или даже битшар. Мне тоже не особо нравится такая странная зависимость. Сделано это было, видимо, чтоб точность ассета сразу была видна в строке. Для простой, однозначной и универсальной десериализации, без необходимости где-то хранить список возможных ассетов и соответствующее число знаков после запятой.
То есть получается, что `1.000 GESTS` и `1.000000 GESTS` — это два совершенно разных ассета, один "GESTS с 3 знаками после запятой", второй — "GESTS с 6 знаками после запятой"

**Comment by asuleymanov** [comment]
Ясно. Вечером проверю с 6 нулями. Посмотрим как пойдет.
Но думаю стоит задуматься и как то это поправить. Очень странно что 1 из 3 валют обрабатывается по своему.

**Comment by asuleymanov** [comment]
Проверил. Действительно когда передаешь 6 нулей все проходит нормально. 
Но все равно мне кажется это надо исправить.

**Comment by gropox** [comment]
Это нормально. Все же это не пользовательский интерфейс, а АПИ. Проще проверить данные и не надо в ноде заниматься медитированием по поводу введённого. Следующим шагом можно разрешить вместо точки запятую, как это в некоторых странах принято. Потом попросить убрать имя ассета, так как и так из контекста ясно. Лишняя морока, за два года ни кому не помешало.

Работает и ладно. Потом добавят комьюнити токены, может СГ можно будет пользовательскими токенами пополнять? Опять переделывать?

**Comment by asuleymanov** [comment]
Думаю что если добавят комьюнити токены. То все надо будет переделывать все равно.
И скорее всего к варианту который хотели внедрить еще зимой.
