### ISSUE TITLE
Move non-consensus indices (by_last_update, by_author_last_update) from golos::chain::comment_index to social_network-plugin

### ISSUE THREAD

**Issue by afalaleev** [GolosChain/golos#828]
There are two non-consensus indices (`by_last_update` and `by_author_last_update`) in the golos::chain::comment_index, which are protected by the precompile condition `IS_LOW_MEM`. 

Steps to remove IS_LOW_MEM mode:
- [x] Create a new structure `comment_last_update_object` in the `social_network`-plugin with fields: `comment` (comment_object_id), `parent_author`, `author` and `last_update`
- [x] Remove fields `last_update` and `active` from the `comment_object`
- [x] Move initialization of `last_update` and `active` from evaluators to the `social_network`-plugin
- [x] Create a new index for the `comment_last_update_object` with two indicies: `by_last_update` and `by_author_last_update`
- [x] Change type of `last_update` in API objects (`comment_api_object` and `discussion`) to optional
- [x] Add initialization of moved fields in API objects (`comment_api_object` and `discussion`) to the `discussion_helper`
- [x] Add a configuration flag `store-comment-last-update`. The default value is `true`
- [x] Fix unit tests

**Comment by maslenitsa93** [comment]
PR https://github.com/GolosChain/golos/pull/888
