### ISSUE TITLE
Mongo Add collections with transfer information

### ISSUE THREAD

**Issue by afalaleev** [GolosChain/golos#830]
Add the following collections to mongo database:

- [x] transfer_to_vesting (add information about GESTS value from dynamic_global_properties)
- [x] transfer_to_savings
- [x] fill_convert_request
- [x] liquidity_reward
- [x] interest
- [x] fill_vesting_withdraw
- [x] fill_order
- [x] fill_transfer_from_savings

**Comment by maslenitsa93** [comment]
Should `fill_convert_request_operation` remove `convert_request_object` from Mongo or it is useless/disimproving?

**Comment by afalaleev** [comment]
For getting information better if it will be in one collection than two.

**Comment by maslenitsa93** [comment]
>  transfer_to_vesting (add information about GESTS value from dynamic_global_properties)
As far I know, transfer_to_vesting goes (for example from cli_wallet) in GOLOS.
I should convert GOLOS to GESTS and write _both_ ones to mongo? What formula?

**Comment by maslenitsa93** [comment]
@afalaleev 
For liquidity_reward I should write `liquidity_reward_balance_object`, yes? All these objects changing in apply_hardfork but I could use `hardfork_operation`

**Comment by afalaleev** [comment]
If you mean these lines https://github.com/GolosChain/golos/blob/56a0a8ecebf0c224561a8d47beb4cbbd556e16bf/libraries/chain/database.cpp#L4582-L4589 

Don't export weight, now. If it will be required we will add it in the future.

**Comment by maslenitsa93** [comment]
@afalaleev If operation updates dgp should I update it in mongo state in this operation handler?

**Comment by afalaleev** [comment]
No, you shouldn't.
You already has logic for storing of dgp, which changes on each block.
