### ISSUE TITLE
добавить доп. данные в плагин mongo_db

### ISSUE THREAD

**Issue by epexa** [GolosChain/golos#833]
необходимо добавить дополнительные данные в коллекции.

- [x] в "[comment_object](https://github.com/GolosChain/golos/blob/master/plugins/mongo_db/mongo_db_state.cpp#L62)":
- block_num

- [ ] в "[account_object](https://github.com/GolosChain/golos/blob/master/plugins/mongo_db/mongo_db_state.cpp#L172)":
- follower_count (кол-во подписок)
- following_count (кол-во подписчиков)
_эти данные можно получить через метод API get_follow_count_

**Comment by gropox** [comment]
Зачем опять добавлять поля, которые без плагина будут пустыми? Чистили-чистили от всякого. Не все пользуются плагинами

**Comment by afalaleev** [comment]
Эти  поля будут в Монге, мы не будем их добавлять их в демона.
Это для выдачи информации в эксплорере.

**Comment by maslenitsa93** [comment]
Which way is good to access `get_followers` and `get_followings` (which are in _follow_ plugin) from mongo plugin?
I could get golos::plugins::follow::plugin reference, it has such methods, but [they are declared with DECLARE_API](https://github.com/GolosChain/golos/blob/830-mongo-collections-with-transfer-info/plugins/follow/include/golos/plugins/follow/plugin.hpp#L45), i.e. requiring too complex arguments.
Also this plugin has "raw" methods: https://github.com/GolosChain/golos/blob/830-mongo-collections-with-transfer-info/plugins/follow/plugin.cpp#L332
But they are in plugin::impl (reference is private) and header hasn't declarations of them.
Should I rewrite follow plugin class to make these methods public as "raw"?
Or I should call methods which are for api?

And shouldn't I provide for such case: user have enabled mongo plugin and disabled follow plugin?
