### ISSUE TITLE
config replay_if_corrupted

### ISSUE THREAD

**Issue by t3ran13** [GolosChain/golos#850]
It is in releas
"New flag replay_if_corrupted = false has been implemented in configuration file that prevents automatic replay-procedure call. The flag is set to “false” by default."

but in real my 2 nodes went to replay this week  without  "replay_if_corrupted"  param in config

**Comment by afalaleev** [comment]
Yes, there is a bug in the release notes.
The default strategy of changes is to keep a default behavior.
The default value for the `replay-if-corrupted` is `true`:
https://github.com/GolosChain/golos/blob/74404a0d64a96eea89c4612b27ea8f9e0ebc8edd/plugins/chain/plugin.cpp#L233-L234

**Comment by t3ran13** [comment]
Add parametr to configs to see it

**Comment by afalaleev** [comment]
Add flag to configs 
https://github.com/GolosChain/golos/blob/3ce26242152a7b7a95d6354b6dd836636322c71d/share/golosd/config/config.ini#L112
