### ISSUE TITLE
Названия параметров в cli_wallet

### ISSUE THREAD

**Issue by gropox** [GolosChain/golos#858]
Раньше help выдавала список команд с названиями параметров, сейчас выдет вместо названий параметров их типы. Приходится по типу гадать, что ожидается в качестве параметра. 

Предлагаю вернуть названия параметров, вместо типов. Или расширенный help по каждой команде. Как то так к примеру
```
>>> help update_witness 
update_witness 
Updates witness account

Parameters:
   witness           std::string
   url               std::string
   owner             golos::protocol::public_key_type
   chain_props       optional<golos::protocol::chain_properties_18>
   broadcast         bool
```

**Comment by zxcat** [comment]
Для справки по команде есть команда `gethelp`, но она тоже не работала — в каком-то давнем рефакторинге сломали. Починил в #920

**Comment by afalaleev** [comment]
Tested on mainnet
