### ISSUE TITLE
Remove built-in NTP client

### ISSUE THREAD

**Issue by Nemo1369** [GolosChain/golos#88]
The blockchain daemon should not be an ntp client for several reasons sneak mentioned in https://github.com/steemit/steem/issues/727 and https://github.com/steemit/steem/issues/816

Seems to be a fine idea, so let us implement it.

**Comment by Nemo1369** [comment]
Closed by 766411b

**Comment by Nemo1369** [comment]
Closed by 79070d4

**Comment by afalaleev** [comment]
Closed by #753
