### ISSUE TITLE
Правки к штрафному 30-иминутном окну голосования

### ISSUE THREAD

**Issue by gropox** [GolosChain/golos#898]
Для борьбы с ботами было введено изначально тридцатиминутное штрафное окно. При голосовании в течении первых тридцати минут кураторские делятся пропорционально между автором и куратором. Таким образом это должно было заставить кураторов голосовать как можно позже, тем самым усложняя игровую составляющую голосования.

Но с появлением бустеров, авторы все чаще стали заказывать апвоуты в первые минуты после публикации поста, тем самым срезая выплаты кураторам. Тем самым еще больше убивая саму идею курирования контента. 

Потому предлагаю срезанные кураторские не отдавать автору поста, а оставлять в пуле авторских вознаграждений. Тем самым автору не будет мотивации срезать выплаты и кураторы получат возможность зарабатывать на курировании. 

Радикальное решение было бы конечно пересмотреть всю экономику голоса, но по крайней мере это решение должно помочь привлечь обычных пользователей, с небольшой СГ к курированию контента. 

Возможно авторам будет выгоднее тогда оттягивать покупку голосов, что бы привлечь голоса не участвующие в бустерах.

Это тема по крайней мере обсуждалась на steemit тоже. 

https://steemit.com/steem/@steemitblog/hardfork-20-velocity-development-update

На стимите так же предлагается уменьшить штрафное окно до 15 минут. Возможно стоит подумать о том, что бы сделать этот параметр голосуемым.

**Comment by t3ran13** [comment]
поддерживаю!
только к этому еще предлагаю сделать более равномерное распределение кураторских наград как на стиме. это не серьезно когда боты обкрадывают людей. пускай хотяб у людей и ботов приблизно одинаковые шансы будут- более равномерное распределение. я не говорю линейное, достаточно для функции a\*x\^2+b\*x+c сделать коэффициент a < 0.1

**Comment by tnam0rken** [comment]
Срезание кураторских - сейчас единственный способ выйти в + на голосе...

**Comment by denis-skripnik** [comment]
Предлагаю вообще убрать это окно, сделав равномерное распределение кураторских, когда бы апвоты не были поставлены: в любом случае автор получит 75%, а куратор - 25%. Хотя и варианты, предложенные @gropox мне нравятся.

**Comment by litrbooh** [comment]
@tnam0rken 
Наоборот, если у всех будет одинаковый размер кураторских, то цены просто упадут и всё. Зато не надо будет биться над срезкой. Дождался халявных апов, если такие будут - а потом пошел качать.

**Comment by litrbooh** [comment]
@gropox 
Лично, я считаю что это ничего не даст. Я предлагал радикальнее сделать:
1) поднять процент кураторских
2) зафиксировать его
3) сделать линейным

**Comment by gropox** [comment]
@litrbooh 
> Лично, я считаю что это ничего не даст. Я предлагал радикальнее сделать:

Согласен конечно с тем, что возможно надо пересматривать экономику, но проблема в том, что нормального обсуждения не ведется, какой должна быть хорошая экономика. Все остается на уровне "обсуждения на кухне, за стаканом чая". Слишком мало народу, понимающие о чем речь. 

И я бы не сказал, что совсем ничего не даст предложенное. Это конечно не радикальное решение, но простое  и понятное в реализации и в том, как оно работает. Минут десять специалисту что бы сделать, но возможно добавит игровой момент, вернее вернет его.

**Comment by t3ran13** [comment]
@litrbooh 
категорически против твоего "жадного" предложения)

**Comment by t3ran13** [comment]
> вернее вернет его.

ага,  я думаю что перед радикальной переделкой сперва стоит попробовать починить)

**Comment by litrbooh** [comment]
@t3ran13 
> категорически против твоего "жадного" предложения)

тогда не жалуй
тесь потом, что кураторство снова не работает :)

**Comment by afalaleev** [comment]
- [ ] Extend `chain_properties_19`
- Auction window  (default `STEEMIT_REVERSE_AUCTION_WINDOW_SECONDS`)

- [ ] Add calculation of median to `database::update_median_witness_props()`
- [ ] Add weight of auction window to `comment_object`
- [ ] Extend `comment_api_object` with weight of auction window
- [ ] Add calculation of auction window weight to `vote_evaluator`
- [ ] Add returning of auction rewards to reward pool in `database::pay_curators()`
- [ ] Fix calculation of pending rewards in `discussion_helper`
- [ ] Extend `update_chain_properties` command with auction window in cli_wallet
- [ ] Extend `info` command with auction window in cli_wallet
- [ ] Add unit-tests for auction window

**Comment by litrbooh** [comment]
afalaleev
Что конкретно делается, какая будет реализация? Можно для простых смертных на русском языке описать, я ваших коммитов не понимаю.

**Comment by afalaleev** [comment]
Реализацию можно разбить на два пункта:
- Размер штрафного окна выносится в список голосуемых параметров.
- Срезанные в штрафное окно кураторские возвращается в пул вознаграждений.

**Comment by t3ran13** [comment]
Мб не стоит в пул возращать, а отдавать другим кураторам нужно?

**Comment by gropox** [comment]
@t3ran13 по мне так это тоже самое, что и автору отдавать. Я вызваю бустера на первых минутах, а следом прихожу сам и голосую

**Comment by afalaleev** [comment]
Есть еще третий вариант - сжигать.

**Comment by gropox** [comment]
Про сжигание не знаю, это повлияет на инфляцию. чуть притормозит. Не думаю, что на очень большие значения, но все же. 

Я лично за возврат.так как это сохранит статус кво. Если что то сжигать, так это золотые - уменьшать долг. А это голоса.

**Comment by t3ran13** [comment]
- если ты заплатил за ап, то это втои проблемы кому и какие кураторские пойдут. Мб кто-то будет зарится на такие апы и следом ходить кураторские собирать, хз, но это оживит систему. 
- я вообще готов сам лично апать на старте свои посты привлекая мелочь кураторскими) это не минус а плюс)
- возврат в пул довольно стремно, если будут баги то хз как их отслеживать. может появится дырявое корыто, я против. 
- отправляя в пул ты фактически отправляешь 75% авторам, что работает точно так же как и срезка кураторских когда их получает автор поста.

**Comment by gropox** [comment]
@t3ran13 
> если ты заплатил за ап, то это втои проблемы кому и какие кураторские пойдут. Мб кто-то будет зарится на такие апы и следом ходить кураторские собирать, хз, но это оживит систему.

Да их будут всякие крокодилы так же резать. Немного людей занимаются покупкой апов. Это в основном касатки. Если они сейчас не гнушаются кураторскими, вызывая бустера на первой минуте, они и потом не будут гнушаться после вызова бустера проголосовать за свой пост. и срезать кураторские всем остальным, проголосовавшим позже.  

> возврат в пул довольно стремно, если будут баги то хз как их отслеживать. может появится дырявое корыто, я против.

Баг в любом из предложенных сценаривем может быть

> отправляя в пул ты фактически отправляешь 75% авторам, что работает точно так же как и срезка кураторских когда их получает автор поста.

Отправляя в пул, ты отдаешь другим и кураторам и авторам и самому себе в том числе. Выше пул, выше выплаты постам. У автора теряется мотивация манипулировать кураторскими.

Но возможно и распределять кураторские среди остальных кураторов. Может это и справедливее. Эх, вот если бы автор мог при создании поста выбирать )))

**Comment by t3ran13** [comment]
> Да их будут всякие крокодилы так же резать. Немного людей занимаются покупкой апов. Это в основном касатки. Если они сейчас не гнушаются кураторскими, вызывая бустера на первой минуте, они и потом не будут гнушаться после вызова бустера проголосовать за свой пост. и срезать кураторские всем остальным, проголосовавшим позже.

да какие срезы? сейчас апп кита отдает кураторские автору
- ты предлагаешь передавать эти курсроские опять в пул, т.е. 25% кураторам и 75% авторам
- я предлагаю кураторские от "спешащих" перераспределять между теми кто апает "в правильное время".
как в моем предложении можно срезать кураторские??? их можно только перераспределить между теми кто апает вовремя.

> Баг в любом из предложенных сценаривем может быть

вопрос не в том что может или не может.
а в том что в твоем сценарии его отследить невозможно. 
для контроля нужно создавать доп виртуальные операции. и фиг пойми как смотреть пополнение пула.

> Отправляя в пул, ты отдаешь другим и кураторам и авторам и самому себе в том числе. Выше пул, выше выплаты постам. У автора теряется мотивация манипулировать кураторскими.

это верно только для тех у кого нет силы. а вот для тех кто в состоянии распределить 10% пула и более, это как бы и хорошо, можно пользоваться)
а историй с распределением пула на голосе полно)

> Но возможно и распределять кураторские среди остальных кураторов. Может это и справедливее. Эх, вот если бы автор мог при создании поста выбирать )))

такая система работает на стиме. если честно я не встречал еще жалоб по этому вопросу, хотя я и не сильно мониторю "общественность" на стиме)

**Comment by gropox** [comment]
> да какие срезы? сейчас апп кита отдает кураторские автору

Я про то, что сейчас авторы покупают апвоут бустера сразу после создания поста. Тем самым они забирают (срезают) кураторские бустера себе. Так как основные rshares бустера были впереди, вес остальных кураторов очень мал и они вообще не получают кураторские. Это я и назваю срезание кураторкских. 

Ты предлагаешь распределять кураторские среди других. Я предполагаю, что автор в таком случае так и дальне будет покупать бустера пораньше, и потом голосвать за ним следом, что бы получить распределяемые кураторские опять же себе. Такие авторы обчно прокаченные косатки, вся мелочь, которая будет голосовать после них опять же ничего не получит. То есть выгоды вероятно от нововведения не будет никакой.  Потому я скорее всего за возврат в пул. 

>  в том что в твоем сценарии его отследить невозможно. 

Как и распределение вознаграждения среди других. При возврате я даже думаю можно ввести отдельную переменную, сколько вернулось, если так надо.


> такая система работает на стиме. если честно я не встречал еще жалоб по этому вопросу

На стимите как раз как у нас сейчас, это только в 20-ом хф будет, который в сентябре. Причем это будет разврат в пул )) Потому ты жалом и не встречал. Вот ниже из описания к 20-ому ХФ. Даже самим придумывать ничего не надо, имплементацию можно взять со стимита.

> Previously, if a vote was made within the first 30 minutes after a post was created, the voter would receive less curation rewards, as those rewards would go to the author instead. This amount has been changed from 30 minutes to 15 minutes. Additionally, the curation-rewards which previously went to the author, are now being returned to the reward pool.

**Comment by t3ran13** [comment]
> Ты предлагаешь распределять кураторские среди других. Я предполагаю, что автор в таком случае так и дальне будет покупать бустера пораньше, и потом голосвать за ним следом, что бы получить распределяемые кураторские опять же себе. Такие авторы обчно прокаченные косатки, вся мелочь, которая будет голосовать после них опять же ничего не получит. То есть выгоды вероятно от нововведения не будет никакой. Потому я скорее всего за возврат в пул.

что бы куратоские не срезались их нужно вернуть на место, не так ли?
а ты предлагаешь срезанное отдать другим. так это так срезанным и останется. и не важно кому оно достанется, если других кураторов общелили)
а вот если киты и касатки в окне голосуют, то вся мелочь получит их кураторские, так что мой вариант лучше)

> На стимите как раз как у нас сейчас, это только в 20-ом хф будет, который в сентябре. Причем это будет разврат в пул )) Потому ты жалоб и не встречал. Вот ниже из описания к 20-ому ХФ. Даже самим придумывать ничего не надо, имплементацию можно взять со стимита.

ты ошибаешься, они когда линейку вводили делали и пересмотр куратоских)

**Comment by t3ran13** [comment]
ок, сча на стиме ошрафованые кураторские идут другим куратораам, но они рещили отказаться и скидывать обратно в пул...
мне не шипко нравится эта затея, я писал выше - если накосячат то фиг кто разберется.
но по самому механизву, мне более привлекателен текущий стимовский вариант, хотя и не принципиален и в пул тоже сгодится)

**Comment by gropox** [comment]
@litrbooh это не прекратит и мое имхо почему я описал выше

**Comment by t3ran13** [comment]
Я за то, чб отдать куратрские другим кураторам. Нет смысла уменьшать кураторские, они ведь положены кураторам)

**Comment by tnam0rken** [comment]
Вот именно, что 25% положено КУРАТОРАМ, которые КУРАТОРСТВОМ вывели пост в топ. А если автор сам вывел пост в топ - то с какой радости что-то должно идти кураторам? Они не курировали пост. В выплате нет их доли. Я обеими руками за сохранение текущей возможности срезки кураторских. Либо (крайний случай, это хуже срезки кураторских) сделать так, чтобы при отключении кураторских они не сгорали, а шли автору. Тогда если собираешься качать пост - отключаешь кураторские. Не собираешься качать - оставляешь в надежде, что кураторы покажут пост китам.

**Comment by t3ran13** [comment]
@tnam0rken не все как вы покупают апы)
я лично когда апаю не смотрю когда был запощен пост и не против если мои кураторские пойдут не автору, а кураторам) мой выбор

а вот на покупке апов это не скажется. просто продавцы начнут учитывать это и продавать подешевле)

**Comment by tnam0rken** [comment]
Не смешно. Фиг они начнут понижать цену))
Когда я апаю фаворитов - я вообще на кураторские не смотрю. Раньше за легионом стоял, потом стал продавать часть апов

**Comment by afalaleev** [comment]
- [ ] Add extension to comment to select destination of returning (reward fund or curators)
- [ ] Add calculation with returning to curators
- [ ] Add virtual operation `return_to_reward_fund`

**Comment by t3ran13** [comment]
Чб не делать двойную работу вынесите вопрос на голосование делегатам
