### ISSUE TITLE
Отдельный пул вознаграждения для комментариев

### ISSUE THREAD

**Issue by gropox** [GolosChain/golos#901]
Сейчас, в отличии от стимита, на голосе один пул "авторских вознаграждений". Для постов и комментариев. 

Возможно было бы неплохой идеей сделать так же как и на стимите два раздельных пула вознаграждений. Потенциально это может снизить негативный эффект, если кто то начнет на автомате писать комментарии и и голосовать за них. Плюс добавить возможность голосовать за размер пула делегатам.

Во вторых возможность создавать раздельные пулы может потенциально пригодиться для реализации воркеров на голосе. К примеру отдельный пул, наполняемый из эмиссии для воркеров.

**Comment by afalaleev** [comment]
Они добавили Comment Reward Pool в 17 ХФ steemit#774 и удалили его в 18 steemit#983

Там сейчас один пул вознаграждений:
https://github.com/steemit/steem/blob/master/libraries/chain/database.cpp#L567-L570

**Comment by gropox** [comment]
Ну да, точно. Надо почитать, почему отказались. Возможно самоконментирование комментариев не так выгодно, как это себе представляется

**Comment by litrbooh** [comment]
@gropox 
при линейке в нем нет смысла, отдельный пул нужен были при квадрате

**Comment by gropox** [comment]
Я посчитал. Самоап приносит примерно столько же, сколько и продажа этого апа через бустер. Может чуть больше, за счет исключения посредника. 

Возможно поэтому и не получило такого большого распространения. Хотя по идее постить комментарий к какому нибудь старому посту и ставить себе ап выгоднее, чем самоап поста.

Вообщем не стоит свеч, да.
