### ISSUE TITLE
Change the discussion payout protocol

### ISSUE THREAD

**Issue by Nemo1369** [GolosChain/golos#91]
Inspired by https://github.com/steemit/steem/issues/769, but the final result supposed to have extendable payout periods.

Related to #62

**Comment by Nemo1369** [comment]
Closed by d771b32

**Comment by Nemo1369** [comment]
Closed by eda83ee

**Comment by erikkartmen** [comment]
10 GBG very big price for the day, why not 1-2 GBG? How many users will be able to pay this price?

**Comment by Nemo1369** [comment]
@erikkartmen Well, let us make it 1 GBG for a day. @serejandmyself ?

**Comment by erikkartmen** [comment]
The more tokens burn, the better. Then let's do it massively and 1-2 GBG will be much more interesting

**Comment by t3ran13** [comment]
Обоснуйте плиз, чем вызван выбор числа в 10 золотых??? это огромная сумма. и если ее заапрувить, то получится фича которой никто никогда не будет пользоваться.

**Comment by Nemo1369** [comment]
@t3ran13 It was a no-reason stub amount for tesing and development purposes. It should replaced. What do you think about 1 GBG for a day, as @erikkartmen proposed? We need some community opinion in here.

**Comment by erikkartmen** [comment]
The lower the price, the more it will be used. Or we can compare this possibility with the promo tab, which is dead

**Comment by Nemo1369** [comment]
So, let us make it 1 GBG for a day.

**Comment by t3ran13** [comment]
1 золотой это космическое число!
https://golos.io/ru--statistika/@arcange/ezhednevnyi-otchet-20171113
смотрите отчет арканжа
средняя сумма за пост 40 рублей (~7 золотых.) но таких постов мало, потому что половина постов получает около 2 рублей (0,5 золотых). С учтом что меньше половины постов, всего смогут испол

**Comment by t3ran13** [comment]
опять же, сам по себе спрос на такую фичу будет ограничен. кому она будет нужна, какой аудитории? неужели вы думаете что ей захочет воспользоваться абсолютно каждый?

только, возможно, ученые. авторы книг, стихов, даже не уверен с фото. много у нас таких? в основном однодневный контент без смысла пробления выплат

**Comment by Nemo1369** [comment]
@t3ran13 Alright, we could reduce the cost even more. Let us make it 0.2 GBG for a day and in the next version we will make it votable, just like lots of other params.

**Comment by t3ran13** [comment]
@Nemo1369 
спасибо

**Comment by vista7** [comment]
@erikkartmen  @t3ran13 я согласен, что слишком большие суммы за дополнительные окна делать не стоит. Не все же на Голосе богачи и готовы раскидываться золотыми.  На чём сошлись то в обсуждениях? на 0,2 ГБГ?  И сколько можно будет таких дополнительных окон делать?

**Comment by Nemo1369** [comment]
@vista7 The additional cashout windows amount is not limited. 0.2 GBG.

**Comment by vista7** [comment]
@Nemo1369 that*s good :) А почему вы по английски пишите всегда на гитхабе, кстати? ;) Для того чтобы иностранные инвесторы могли понимать суть если вдруг зайдут сюда почитать? ) Или какая-то другая причина есть?

**Comment by t3ran13** [comment]
@vista7,  топовые авторы, "богачи", если подумать, то не нуждаются в продлении выплат.
А вот наличие фишки, с доступной пролонгацией и выплатами, может привлечьдополнительных авторов долгоживущего контента - бонально писателей)

@Nemo1369  
ксатти, продление сразу на все периоды оплачивается, или продление выплат для кадого периоода отдельно заказывается?

**Comment by vista7** [comment]
@t3ran13 

> ксатти, продление сразу на все периоды оплачивается, или продление выплат для кадого периоода отдельно заказывается?
> могу я сразу указать продление на год и оплатить, или нет?
Это хороший вопрос. Думаю, пока в коде заложена схема с ручным продлением каждого периода, без возможности заказать продление сразу на несколько дней/недель/месяцев.

**Comment by t3ran13** [comment]
@vista7  если так, то это маленькое идевательство)))

**Comment by vista7** [comment]
@t3ran13 может и изменят на автоматическое продление периодов, посмотрим) Мы для этого тут и находимся чтобы предлагать какие-то свои идеи и фишки :)
