### ISSUE TITLE
В get_content, total_payout_value содержит не полную сумму

### ISSUE THREAD

**Issue by gropox** [GolosChain/golos#921]
В get_content, total_payout_value содержит не полную сумму, без учета выплат бенефициантам.

Вот пример

http://ropox.tools/steemjs/api/social_network/get_content?blockchain=Golos.io&ws=wss%3A%2F%2Fws.golos.io&prefix=GLS&chain_id=782a3039b478c839e4cb0c941ff4eaeb7df40bdd68bd441afd444b9da763de12&author=d0z4t0r&permlink=ru-ya-poijmal-slona-dlya-yestafety-ot-slon21veka-opyatx&voteLimit=0

![image](https://user-images.githubusercontent.com/26039472/43741133-a6093a92-99cd-11e8-8a2d-40794cfba99f.png)

https://github.com/GolosChain/golos/blob/master/libraries/chain/database.cpp#L2255

sbd_payout содержит только выплаты автору.

Логичнее было бы, если это поле содержало полную сумму, ну и дополнительно можно заэкспозить beneficiary_payout_value. Сейчас get_content не выдает это значение.

**Comment by afalaleev** [comment]
В 0.18.4 мы расширили информацию о выплате по посту:

https://github.com/GolosChain/golos/blob/59b58b83377020bbcda6e8436065e4e57585435c/libraries/api/include/golos/api/comment_api_object.hpp#L48-L57

Там есть выплаты и кураторам и бенефициарам и автору.

Чтобы не ломать совместимость для клиентов (это все таки SoftFork) , в `total_payout_value` по прежнему содержатся авторские за вычетом бенефициарских. Но сейчас появится возможность посчитать полную выплату. 

Точно также появилась возможность посмотреть предполагаемые выплаты:

https://github.com/GolosChain/golos/blob/59b58b83377020bbcda6e8436065e4e57585435c/libraries/api/include/golos/api/discussion.hpp#L20-L29
