### ISSUE TITLE
Фича для ХФ - key-value storage

### ISSUE THREAD

**Issue by t3ran13** [GolosChain/golos#924]
Создать плагин для  key-value хранилища, реализация в 2 строчки кода.
можно взять за основу гет пост и выкинуть все лишнее

**Comment by gropox** [comment]
Храни все в metadata аккаунта

**Comment by t3ran13** [comment]
мы за правильные "стильные" решения)
приватные сообщения ведь запилили, хотя для низ можно было и левый сервис заюзать) дешевле и быстре)

**Comment by gropox** [comment]
Ну да, красивее было бы что то вроде

set_value account key value 
get_value account key

Но надо ограничивать, по СГ аккаунта. Причем сильно. Что бы не надували ноды всяким хламом.

**Comment by t3ran13** [comment]
Ну да, это как раз простимулирует покупку голосов)
если перевод на бэндвиз влияет х10, то тут можно смело делать Х30-50
в идеале параметров вынести для делегатов.

**Comment by asuleymanov** [comment]
Идея конечно здравая. Думаю только сделать ограничение по количеству таких записей в зависимости от СГ. А уж что там хранить каждый может решать сам. Вот только надо тогда делать так чтобы это смог запостить и получить только один и тот же человек. 
Также можно добавить шарить остальным такие записи.

**Comment by On1x** [comment]
Поддерживаю, ОЧЕНЬ НУЖНАЯ ВОЗМОЖНОСТЬ! Только в виде отдельного плагина, отдельные операции под это не надо делать, обойдемся форматом в custom_json.

**Comment by afalaleev** [comment]
с custom_json_operation есть момент - если плагин на делегатской ноде будет выключен, то операция будет включена в блок-лог без валидации.
естестевенно, что бендвич по операциям в плагинах не посчитаешь, так как на одних нодах плагин выключен, на других включен.

можно захардкодить определенный тип custom_json_operation на бендвич, но в  чем тогда разница с обычной операцией? можно просто добавить set_value и считать по нему бендвич нормально. а чтобы иметь возможность не хранить на ноде key-value хранилище, то сделать настройку в конфиге.

лично мне больше нравится - блокировать часть СГ на хранение данных, чем бендвич. бендвич он только на траффик через ноду работает,  и не работает на объем. 
как вариант - можно сделать уменьшение объема бендвича на объем хранимых данных.

чтение под копотом ноды можно не контролировать - берешь собираешь ноду без контроля и получаешь данные без ограничений. 

поскольку данные нода никак не валидирует, для нее value просто blob, то туда можно класть хоть зашифрованные данные.

**Comment by t3ran13** [comment]
Ваш менеджер жалуется что у вас времени нет, так что хватит простенького варианта как предложил оникс

**Comment by maslenitsa93** [comment]
@gropox @t3ran13 @On1x I'm gonna implement it.
Какая в итоге реализация нужна?

**Comment by gropox** [comment]
Есть два варианта, 

# Вариант 1

один дешевый, неконсенсусный. Написать плагин, который бы сохранял последние последние custom_json-ы с отправленные пользователем. С ID в качестве ключа. 

И метод, что бы их извлечь. К примеру get_custom_json("ropox", "state") возвратит "json" аттрибут последней custom_json операции, с ID "state". 

Минусы такого варианта: **Неконсенсусно**, Непонятно как ограничивать объем хранения по пользователю. Хотя можно наверное ограничить максимально 10 записей (10 x 63kb = 640кб макс. на пользователя), старые удалять.

# Вариант 2 

Второй вариант - консенсусный

добавить операцию для сохранения значения с ключем. Таже custom_json, только 

`set_value( "ropox", "balance$t3ran13", "{'USD': '1000.00'}")`
`set_value( "ropox", "ropox11", "['t3ran13', 'on1x']")`
И геттер
`get_value("ropox", "balance$t3ran13")`

Которое вернет `{"USD": "1000.00"}`

Тут тоже надо думать, как ограничивать. Думаю дать делегатам определять цену памяти в голосах, так как у них на серверахз все будет храниться. Сколько стоит один байт или килобайт в Голосах. Допустим 1024 Байт RAM стоит 100 Голосов, при 100к Голосах в СГ, можно сохранить данных на 1 мегабайт. Так проще наверно, чем делать вариант EOS с покупкой RAM. На голосе можно нарегать адресов почти бесплатно и делегировать им сколько угодно CГ тем самым зарезервировав "адресное пространство" )) 

Альтернативно "стоимости", можно задать максимальный размер пула памяти и распределять его сообразно СГ. Допустим определить как 2Gb (определяется делегатами). При наличии 100кСГ получается ~0.11% (согласно steemul) от всего стэка голосов, то есть от 2GB выходит примерно 2 мегабайта? Что в принципе неплохо.

Плюс такого варианта, можно привлекать желающих купить токенов, что бы хранить данные. 

При понижении СГ, удалять старые данные сначала. 

*Я лично за второй вариант.*

**Comment by maslenitsa93** [comment]
@t3ran13 **Будет первый.**
А зачем черный и белый лист юзеров?

**Comment by gropox** [comment]
Что бы в приватной ноде не хранить все подряд

**Comment by maslenitsa93** [comment]
@t3ran13 А одного списка не хватит - либо черный, либо белый?
Цель вообще какая? Если сделать для всех кроме некоторых, то черный. Если сделать только для некоторых - то белый. Как лучше?

**Comment by gropox** [comment]
Сделать как в opration_history

**Comment by gropox** [comment]
Если делать плагином, то надо в любом случае ограничивать, что бы не грузить ноду лишними данными. Сделать максимальное число сохранённых данных или как в opration_history удалять по прошествии заданного в конфиге колличество блоков. Наверное последнее лучше. Плюс в приватной ноде не хочется хранить чужие данные, хватило бы и белого списка. А вот в публичной, образцово-показательной ноде golos-js.io лучше хранить все и на всякий случай дать возможность исключать злоупотребляющих доверием.

**Comment by gropox** [comment]
Сорри, как в account_history плагине

**Comment by afalaleev** [comment]
Я тоже за плагин. 
Вопрос в том, чтобы не злоупотребляли, потому что делегатские ноды custom_json не обрабатывают.
Но на делегатских нодах можно считать бендвич на все (без разбора на какой плагин) custom_json операции. А делегатам вынести параметры xN (как для трансферов x10) насколько увеличивать потребление бендвича по custom_json операциям.

**Comment by maslenitsa93** [comment]
- [ ] Create new plugin `account_notes`. Do next steps inside the plugin
- [ ] Implement config like in account_history-plugin, but with blacklist too:

- tracked_account
- tracked_accounts
- untracked_account
- untracked_accounts

**Comment by afalaleev** [comment]
@maslenitsa93, Looks good!
Small improvements:
- [ ]  `tracked_account` and `untracked_account` are not needed. `tracked_accounts` and `untracked_accounts` are enough
- [ ] Add configuration for limit on size of stored key/value
- [ ] Add calculation of bandwidth for custom_json like for transfers
- [ ] Add param to chain_properties for xN (default x10) of bandwidth for custom_json

**Comment by maslenitsa93** [comment]
- [ ] Create new plugin `account_notes`. Do next steps inside the plugin.
- [ ] Implement config like in account_history-plugin, but also with blacklist:

- tracked_accounts
- untracked_accounts

- [ ] Add config key for limit on size of stored key
- [ ] Add config key for limit on size of stored value
- [ ] Add config key to limit on count of notes per account
- [ ] Add `account_note_object`. For value use `buffer_type`. Add index of these objects.
- [ ] Add operation `set_value_operation` (to be sending with custom_json)
- [ ] Define API method `get_value` (parameters are account and key) to return the value.
- [ ] Add calculation of bandwidth for custom_json like for transfers
- [ ] Add param to chain_properties for xN (default x10) of bandwidth for custom_json
- [ ] Write checklists for pull request
- [ ] Write unit-tests for plugin_tests

**Comment by maslenitsa93** [comment]
@t3ran13 @gropox @On1x  Продолжаем работу над #924 !
На данный момент у нас есть такая реализация плагина:
https://github.com/GolosChain/golos/pull/958
Там единственный коммит, весь код в нём. 
Возникла пара вопросов. Например, не нужно ли нам шифрование value, как encrypted_message в private_message (а то, в теории, ничто не мешает брутом подобрать аккаунт и key и получить чужое value)? И не нужен ли хеш вместо key (про хеш - это уже скорее будет внутренняя кухня)?

**Comment by gropox** [comment]
Шифрование и хэши не нужны. Шифровать можно и в приложении при необходимости. С хэшами тоже самое

**Comment by t3ran13** [comment]
+1 к гороху
