### ISSUE TITLE
Установить минимальный процент кураторских в 25%

### ISSUE THREAD

**Issue by yurgent71** [GolosChain/golos#927]
Сделать 25% минимально возможной долей кураторских. Это позволит стимулировать желание увеличивать силу голоса
https://goldvoice.club/@yurgent71/yekonomika-golosa-perekhod-na-lineijku/

**Comment by afalaleev** [comment]
Схожее предложение есть в #898

**Comment by yurgent71** [comment]
Можно сделать и как gorox предлагает, но в том предложении страдают инвесторы, не знакомые с правилами начисления кураторских. Мне кажется довольно глупым вариант, когда читающий не может сразу "лайкнуть" пост и вынужден ждать 15-30 минут.

**Comment by afalaleev** [comment]
Closed in HF-19
