### ISSUE TITLE
расширить get_ops_in_block

### ISSUE THREAD

**Issue by t3ran13** [GolosChain/golos#936]
добавить в метод get_ops_in_block инфу облоке как в get_block
сделать тело ответа get_block  и get_ops_in_block  идентичными

**Comment by gropox** [comment]
Сделать выхлоп get_block и get_ops_in_block взаимозаменяемым, одинковым по структуре

**Comment by afalaleev** [comment]
We will add the new API method to operation_history:
get_block_with_ops

**Comment by afalaleev** [comment]
- [ ] Move `signed_block_with_info` from `library/wallet` to `libraries/api`.
- [ ] Rename `signed_block_with_info` to `annotated_signed_block`
- [ ] Move `block_operations` from `plugins/database_api` to `libraries/api`
- [ ] Add `block_operations`  to `annotated_signed_block`
- [ ] Remove `block_with_vops` from `plugins/database_api`
- [ ] Refactor `database_api::set_block_applied_callback` to use `annotated_signed_block`
- [ ] Refactor `database_api::get_block` to use `annotated_signed_block`
- [ ] Refactor using of `signed_block_with_info` to `annotate_signed_block` in `libraries/wallet`
- [ ] Add `get_block_with_virtual_ops` to `plugins/operation_history` with result `annotated_signed_block`
