### ISSUE TITLE
Кнопка Отблагодарить

### ISSUE THREAD

**Issue by yurgent71** [GolosChain/golos#941]
Предлагаю сделать автозаполнение поля мемо в окне перевода токенов, которое открывается по нажатии кнопки "Отблагодарить" внизу любого поста. Заполнять поле мемо примерно таким текстом "Спасибо за ваш пост {url-поста}" (ну или что-то в этом роде). 
Иначе автор, получающий платеж не поймет, за что именно он получен (многие могут подумать, что вообще ошибка). А тут видно будет сразу. Заставлять пересылающего писать самому не стоит, ибо поленятся. 
Можно еще ввести сумму перевода по-умолчанию, напр. 1 golos и сделать ползунок, как при апвоте, когда можно варирьировать силу голоса. Но это уже не так важно, как заполнение поля мемо.

Повторюсь, цель предложения - показать, автору что это именно благодарность за конкретную работу, а не просто какой-то левый трансфер непонятно за что.

Боюсь, нынешний интерфейс "Отблагодарить" отпугивает меценатов....

**Comment by afalaleev** [comment]
У golos io есть свой репозиторий: https://github.com/GolosChain/tolstoy

**Comment by yurgent71** [comment]
перенес туда. Этот можно закрыть
