### ISSUE TITLE
Fix history-blocks option

### ISSUE THREAD

**Issue by AKorpusenko** [GolosChain/golos#943]
# Description
In 18.4 `history-blocks` and  `history-start-block` are broken. Fix needed. 
- Fix `set_program_options` in `operation_history`

**Comment by gropox** [comment]
Так же пожалуйста проверьте white-list и blacklist опции. 18.4 их тоже не читает из конфига. Не получается задать список операций для operation-history плагина

**Comment by AKorpusenko** [comment]
@gropox 
Fixed

**Comment by afalaleev** [comment]
PR #944
