### ISSUE TITLE
БАГ! Эммисия золотых при долге выше 10%

### ISSUE THREAD

**Issue by t3ran13** [GolosChain/golos#952]
Насколько нам известно - эммисия золотых при долге выше 10% должна останавливаться.
Но на сегодня идет эммисия за хранение золотых при долге выше 10%.

Белая бумага голоса вопрос долга системы (эммисии золотых) не регулирует и вопрос на совести делегатов

В таких условиях делегатам следует определится 
- либо останавливать выплату процентов за хранение при долге выше 10% ( на уровне кода ноды)
- либо снять лимит на 10% либо увеличить его.

я за снятие лимита по эммисии золотых.

**Comment by afalaleev** [comment]
#817

**Comment by t3ran13** [comment]
Это НЕвзаимосвязанные вещи)
Если долг зависит от курса золотого, то курс золотого не должен зависить от долга.

**Comment by bitfag** [comment]
Печать GBG при достижении ситуации чёрного лебедя действительно выглядит странно. Возможно, стоит сделать жёсткое ограничение - sbd_interest_rate принудительно 0% при достижении долга по GBG 10%.

**Comment by litrbooh** [comment]
@t3ran13 
> Это НЕвзаимосвязанные вещи)

Нет, это связанные вещи!

@afalaleev @marijadia 
Необходимо ввести ограничение эмиссии GBG при достижении 10% от капитализации независимо от %, которые дают делегаты.

**Comment by t3ran13** [comment]
@litrbooh 
не, ты не прав)
если ты пообщел в самом начале насыпать голосов по стоимости 1 мг золота, то это на эммисию не влияет не как. долг будет расти относительно стоимости всех токенов голоса, но в золотом эквиваленте при стопе эммисии останется тот же.

так что курс не связан с эммисией никак.

а вот начисление процентов, если хотят останавливать эммисию, логично тоже ограничить

П.С.
но я против лимиту по эммисии золотого) это клевая тема! 
Начисление процентов можно и уменьшить, но саму эммисию ограничивать не стоит)

**Comment by afalaleev** [comment]
Я не понимаю, откуда такое сильное желание увеличить денежную массу в системе :)
Это буквально проскакивает во всех предложениях - увеличивать выплаты по GBG и ни в коем случае не ограничивать проценты по выплатам, увеличить эмиссию для оплаты воркерам ....

Это как в России с ценами на бензин: нефть дорожает - бензин в цене растет, нефть дешевеет - бензин в цене растет.

Штаты чтобы поднять планку долга собирают конгресс. Безлимитных долгов не бывает, безлимитный долг - это вариация на тему черного лебедя.

Я солидарен с @litrbooh и @bitfag  - масса GBG только растет, и никогда не сгорает - закон сохранения энергии не работает.

**Comment by t3ran13** [comment]
Мы тут и решаем чтотлучше)
Но для начало, представим что не золотого и все платилось изначально в голосах и сг. Так вот чем лучше это чем опрала части в золотых?)

На голосе, будет ли ограничение по золотым или нет, или вообще все будет в голосах, нет систем усменьшающих количество токенов или хотя бы механизмов связанных с заморозкой ликвида.
Да, есть акк null, но пока его эффективность в этом деле ровна нулю.

По штатам у них внешний долг выше годового профита. У нас до этого как до луны. Не говоря о том что тут своеобразный консенсус - обналичивать золотые можно, но нет смысла, стейбл коин это страховка и безопасность. Анологично атака в 51% процент на многие бч - возможна, но практически вы сильно много о таких атаках на практике слышали?
Иметь возможность делать и делать не одно и тоже. Для этого на биржах вообще появились новые активы, не на саму акцию, а лишь на возможность ее покупки по фикс прайсу) вы сильно недооцениваете роль золотых и их возможности.

Опять же, можно ограничить скорость эммисии золотых, но не их количество

**Comment by afalaleev** [comment]
Граница работает как маркер, что что-то не так: собраться и обсудить какие проблемы привели к такому положению вещей.
И Штаты именно это и делают: выставили планку, подбираются к планке и решают - надо планку поднять, или что то можно сделать.
Опять же для внешних инвесторов - это сигнал о том, что система контролируется.
Убрать маркер - это забить на систему.

Опять же - если бы GBG аккумулировал в себе текущие Golos, я бы согласился, что он работает как сжигатель. Но он же представляет из себя стабильный фонд-резерв. Он работает как неконтролируемая эмиссия через APR.

Если посмотреть как работают другие stable/smart coin-ы то они как раз резервируют часть основного актива, и если обеспечения не хватает, то его надо добавить, а не нагенерировать.
В случае GBG, оно работает по другому: обязательство берет на себя БЧ - это просто нагенерить дополнительное количество монеток в случае необходимости, он ничего не сжигает. 10% активов привязана к внешнему рынку, ты же предлагаешь убрать границу совсем. Из этого peg актив уж точно не получится, он совсем уж виртуальный - генерит сколько надо в любой момент времени.

**Comment by t3ran13** [comment]
>Граница работает как маркер, что что-то не так: собраться и обсудить какие проблемы привели к такому положению вещей.

Убери границу, ограничь скорость эммисии и задай ее в пределах "так" и не нужно будет собиратся и обсуждать что не так, когда эммисия будет предсказуема и в ожидаемых пределах. И пофиг не лимит)



>Опять же - если бы GBG аккумулировал в себе текущие Golos, я бы согласился, что он работает как сжигатель. Но он же представляет из себя стабильный фонд-резерв. Он работает как неконтролируемая эмиссия через APR.

В данном случае проблема не в золотом, а в голосах. Именно падение курса голоса увеличивает относительную массу золотого. Не золотой вызыыает проблемы, а голоса. Но золотой помогает справится с кризисом в рамках ограниченных правил. Т.е. если ктото за хочет рискнуть в лится золотой и дождаться падения голоса, он может получить профит. Это обычная биржа.

>Из этого peg актив уж точно не получится, он совсем уж виртуальный - генерит сколько надо в любой момент времени.

У нас вся крипта виртуальная, и ниодна крипта не в состоянииобналичить всю массу своих активов и не повлиять на курс токена. Это не проблема золотого, у золотого лишь свои правила

**Comment by afalaleev** [comment]
@t3ran13  
> У нас вся крипта виртуальная, и ниодна крипта не в состоянииобналичить всю массу своих активов и не повлиять на курс токена. Это не проблема золотого, у золотого лишь свои правила

Тут основная проблема в формулировках.
В других криптах ответственность персональная, за счет наличия залога.
ГБГ создает видимомость стейбл-коинов, когда в качестве гаранта выступает эфимерный БЧ, но на самом деле нагрузка перекладывается на все сообщество.
Поэтому наличие границы - это еще и договоренность с сообществом со стороны владельцев ГБГ.

**Comment by t3ran13** [comment]
@afalaleev


>Поэтому наличие границы - это еще и договоренность с сообществом со стороны владельцев ГБГ.

Все гарантии прописаны в белой бумаге и там о долге ничего нет.
Более того, ни кф ни ктото из команды никогда не говорил о долге и о функции защиты инвесторов ни на этапе ико ни до нахождения багов. Это все фантазии)

В белой бумаге ясно сказано - гбг стабилизирован за счет конверсии в голоса. И стабильный курс не идет в разрез с белой бумагой и эммисия за счет конверсии тоже. Все предупреждены и тайн никаких нету.

А вот об ограничении долга нигде кроме кода не сказано и уж о том что долг может влиять на гарантированный курс, значит второе - бага, а первое - на усмотрение сообщества и делегатов)

**Comment by litrbooh** [comment]
@afalaleev зачем это запихали в 0.19.0? я так понимаю консенсуонального решения ещё нет и оно с делегатами не обсуждалось :)

**Comment by litrbooh** [comment]
@afalaleev 
> Нет консенсуса по 10% лимиту на gbg

если не менять логику эмиссии ГБГ и не делать обеспечение за счет СГ, то у меня предложений нет

**Comment by t3ran13** [comment]
Чб был консенсус нужно собираться, например в дискорде, и обсуждать) но видимо так оно всем нужно)))
