### ISSUE TITLE
Ошибка при запросе GET_CONFIG

### ISSUE THREAD

**Issue by asuleymanov** [GolosChain/golos#964]
У меня при обычном вызове get_config выдает ошибку : 
```
Адрес  "wss://api.golos.cf"
2018/09/27 08:56:37 call failed: jsonrpc2: code -32602 message: Bad Cast (7)
Invalid cast from object_type to Array

exit status 1

Адрес "wss://ws.golos.io"
2018/09/27 09:11:28 call failed: jsonrpc2: code -32600 message: A member "args" should be array
exit status 1
```
Что такого меняли в вызовах апи.
Проверял на двух адресах.

**Comment by asuleymanov** [comment]
Полный запрос вот такой
`{"method":"call","params":["database_api","get_config",{}],"id":0,"jsonrpc":"2.0"}`

**Comment by zxcat** [comment]
Последний элемент в `params` должен быть `[]`, а не `{}`

**Comment by asuleymanov** [comment]
Все нашел проблемму. Спасибо за наводку.
