### ISSUE TITLE
Лоадер крутится после закрытия окна "Войти" при отмене делегирования

### ISSUE THREAD

**Issue by daryasattarova** [GolosChain/golos#974]
Воспроизведение:
1. открыть https://sandbox.golos.io/
2. авторизоваться
3. зайти в "Кошелек"
4. перейти в пункт "Делегирование"
5. (при условии, что вы осуществили делегирование) нажать на "крестик" для отмены делегирования
6. нажать "ок" в окне подтверждения
7. (появится модальное окно "Войти") закрыть окно "Войти", нажатием на крестик

Ожидаемый результат: должно отобразиться
![image.png](https://images.zenhubusercontent.com/5b851e384b5806bc2be425f1/a7778610-0d61-4e01-87e2-f98e8f028d4a)
Реальный результат: лоадер крутится 
![image.png](https://images.zenhubusercontent.com/5b851e384b5806bc2be425f1/dbbb804a-1b5f-49c7-8018-45376bdd9e75)

**Comment by afalaleev** [comment]
Wrong repository.
